let DB={cards:[]}, META={cards:{}}, CATALOG={cards:[]}, OVERLAP={conflicts:[]}, filter='all', query='', sortMode='box', selectedTeam=[], verifyLimit=30, inventory={}, inventoryFilter='review', inventoryQuery='', rarityFilter='', typeFilter='', classFilter='', categoryFilter='', linkFilter='', ezaFilter='', favoriteOnly=false, favorites=new Set();
const norm=s=>(s??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function boot(){
  DB=await fetch('collection.json').then(r=>r.ok?r.json():fetch('data.json').then(x=>x.json()));
  try{META=await fetch('card-meta.json').then(r=>r.ok?r.json():({cards:{}}))}catch(e){META={cards:{}}}
  try{CATALOG=await fetch('catalog.json').then(r=>r.ok?r.json():({cards:[]}))}catch(e){CATALOG={cards:[]}}
  try{OVERLAP=await fetch('overlap-conflicts.json').then(r=>r.ok?r.json():({conflicts:[]}))}catch(e){OVERLAP={conflicts:[]}}
  applyMetadata(); restoreEdits(); initAdvancedFilters();
  render(); stats(); renderDuplicates(); renderMissing(); renderInventory(); renderManualOwned(); renderTeam(); renderAnalysis();
}
function localized(m){if(!m)return null;let fr=m.fr||{};return {...m,name:fr.name||m.name,title:fr.title||m.title,type:fr.type||m.type,class:fr.class||m.class,categories:fr.categories||m.categories,links:fr.links||m.links,leader:fr.leader||m.leader,passive:fr.passive||m.passive,superAttack:fr.superAttack||m.superAttack,active:fr.active||m.active}}
function applyMetadata(){DB.cards.forEach(c=>{let m=localized(META.cards?.[String(c.candidateId)]);if(m)Object.assign(c,m)})}
function confClass(c){return c==='Très forte'?'tf':c==='Forte'?'f':c==='Moyenne'?'m':c==='Validée manuellement'?'manual':'v'}
function restoreEdits(){
  let edits=[]; try{edits=JSON.parse(localStorage.getItem('dokkanos-edits')||'[]')}catch(e){}
  edits.forEach(a=>{let c=DB.cards.find(x=>x.boxId===a.boxId);if(!c)return;Object.assign(c,a);if(a.candidateId){c.image='assets/cards/'+a.candidateId+'.webp';let m=localized(META.cards?.[String(a.candidateId)]);if(m)Object.assign(c,m)}});
  try{selectedTeam=JSON.parse(localStorage.getItem('dokkanos-team')||'[]').filter(id=>DB.cards.some(c=>c.boxId===id)).slice(0,6)}catch(e){selectedTeam=[]}
  try{inventory=JSON.parse(localStorage.getItem('dokkanos-inventory')||'{}')}catch(e){inventory={}}
  try{favorites=new Set(JSON.parse(localStorage.getItem('dokkanos-favorites')||'[]'))}catch(e){favorites=new Set()}
}
function searchText(c){return norm([c.boxId,c.candidateId,c.name,c.title,c.rarity,c.type,c.class,c.leader,c.passive,c.superAttack,c.active,...(c.categories||[]),...(c.links||[])].join(' '))}
function visibleCards(){
  let a=DB.cards.filter(c=>(filter==='all'||(filter==='valid'&&c.validated)||(filter==='check'&&!c.validated))&&(!query||searchText(c).includes(query))&&(!rarityFilter||c.rarity===rarityFilter)&&(!typeFilter||c.type===typeFilter)&&(!classFilter||c.class===classFilter)&&(!categoryFilter||(c.categories||[]).includes(categoryFilter))&&(!linkFilter||(c.links||[]).includes(linkFilter))&&(!ezaFilter||(ezaFilter==='yes'?!!c.eza:!c.eza))&&(!favoriteOnly||favorites.has(c.boxId)));
  if(sortMode==='confidence')a.sort((x,y)=>(y.inliers||0)-(x.inliers||0));
  if(sortMode==='id')a.sort((x,y)=>String(x.candidateId).localeCompare(String(y.candidateId)));if(sortMode==='name')a.sort((x,y)=>(x.name||'').localeCompare(y.name||'','fr'));if(sortMode==='rarity'){let r={LR:5,UR:4,SSR:3,SR:2,R:1,N:0};a.sort((x,y)=>(r[y.rarity]??-1)-(r[x.rarity]??-1))}if(sortMode==='type'){let t={AGI:0,TEC:1,INT:2,PUI:3,END:4};a.sort((x,y)=>(t[x.type]??9)-(t[y.type]??9))}
  return a;
}
function initAdvancedFilters(){let cats=[...new Set(DB.cards.flatMap(c=>c.categories||[]))].sort((a,b)=>a.localeCompare(b,'fr')),links=[...new Set(DB.cards.flatMap(c=>c.links||[]))].sort((a,b)=>a.localeCompare(b,'fr'));$('#categoryFilter').innerHTML='<option value="">Catégorie</option>'+cats.map(x=>`<option>${x}</option>`).join('');$('#linkFilter').innerHTML='<option value="">Lien</option>'+links.map(x=>`<option>${x}</option>`).join('')}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('dokkanos-favorites',JSON.stringify([...favorites]));render();openCard(id)}
function activeFilterSummary(){let x=[];if(query)x.push('Recherche');if(filter!=='all')x.push(filter==='valid'?'Validées':'À vérifier');if(rarityFilter)x.push(rarityFilter);if(typeFilter)x.push(typeFilter);if(classFilter)x.push(classFilter);if(categoryFilter)x.push(categoryFilter);if(linkFilter)x.push(linkFilter);if(ezaFilter)x.push(ezaFilter==='yes'?'EZA':'Non-EZA');if(favoriteOnly)x.push('★ Favoris');let el=$('#activeFilters');if(el)el.innerHTML=x.length?x.map(v=>`<span>${v}</span>`).join(''):''}
function render(){
  let a=visibleCards();activeFilterSummary();
  $('#grid').innerHTML=a.map(c=>`<article class="unit" onclick="openCard('${c.boxId}')"><i class="dot ${confClass(c.confidence)}"></i>${favorites.has(c.boxId)?'<b class="favmark">★</b>':''}<img loading="lazy" src="${c.image}" onerror="this.classList.add('imgfail')"><div class="meta"><strong>${c.name||'ID '+(c.candidateId||'—')}</strong><small>${c.boxId} · ${c.confidence}</small></div></article>`).join('')||'<div class="empty">Aucune carte</div>';
  $('#resultCount').textContent=a.length+' résultat'+(a.length>1?'s':'');
  renderVerify();
}
function stats(){
  let v=DB.cards.filter(c=>c.validated).length, unique=new Set(DB.cards.filter(c=>c.candidateId).map(c=>c.candidateId)).size;
  $('#nAll').textContent=DB.cards.length;$('#nVal').textContent=v;$('#nCheck').textContent=DB.cards.length-v;$('#nUnique').textContent=unique;
  $('#progressBar').style.width=(DB.cards.length?Math.round(v/DB.cards.length*100):0)+'%';
  $('#progressText').textContent=(DB.cards.length?Math.round(v/DB.cards.length*100):0)+'% validé';
}
function renderVerify(){
  let priority=new Set((OVERLAP.conflicts||[]).flatMap(x=>x.observations||[])), pending=DB.cards.filter(c=>!c.validated).sort((a,b)=>(priority.has(b.boxId)?1:0)-(priority.has(a.boxId)?1:0)), a=pending.slice(0,verifyLimit);
  $('#verifyList').innerHTML=a.map(c=>`<div class="panel"><b>${c.boxId}</b><p class="muted">${c.capture} · ${c.position} · ${c.confidence}</p><div class="verify"><div><img src="${c.crop}"><label>Ta capture</label></div><div><img src="${c.image}"><label>ID ${c.candidateId}</label></div><div><img src="${c.runnerImage}"><label>ID ${c.runnerId}</label></div><button onclick="choose('${c.boxId}','${c.candidateId}')">Choisir 1</button><button onclick="choose('${c.boxId}','${c.runnerId}')">Choisir 2</button><button onclick="choose('${c.boxId}','')">Aucun</button></div></div>` ).join('')+(pending.length>verifyLimit?`<button class="loadmore" onclick="loadMoreVerify()">Afficher ${Math.min(30,pending.length-verifyLimit)} de plus · ${pending.length-verifyLimit} restantes</button>`:'')||'<div class="empty">Tout est validé 🎉</div>';
}
function loadMoreVerify(){verifyLimit+=30;renderVerify()}
function saveEdits(){localStorage.setItem('dokkanos-edits',JSON.stringify(DB.cards.filter(x=>x._edited).map(x=>({boxId:x.boxId,candidateId:x.candidateId,validated:x.validated,confidence:x.confidence,_edited:true}))))}
function choose(id,val){
  let c=DB.cards.find(x=>x.boxId===id);if(!c)return;c._edited=true;
  if(val){c.candidateId=val;c.image='assets/cards/'+val+'.webp';let m=localized(META.cards?.[String(val)]);if(m)Object.assign(c,m);c.validated=true;c.confidence='Validée manuellement'}
  else{c.candidateId='';c.validated=false;c.confidence='À revoir'}
  saveEdits();render();stats();renderAnalysis();
}
function skillText(v){if(!v)return '—';if(typeof v==='string')return v;if(Array.isArray(v))return v.map(skillText).join(' · ');return [v.name,v.description,v.condition].filter(Boolean).join(' — ')||'—'}
function tagBlock(title,arr){return arr?.length?`<section class="detail-section"><h3>${title}</h3><div class="tags">${arr.map(x=>`<span>${x}</span>`).join('')}</div></section>`:''}
function statsBlock(c){let vals=[['PV',c.maxHP||c.rainbowHP],['ATQ',c.maxATK||c.rainbowATK],['DEF',c.maxDEF||c.rainbowDEF],['Coût',c.cost],['Niv. max',c.maxLevel],['SP max',c.maxSALevel]].filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=='');return vals.length?`<section class="detail-section"><h3>Statistiques</h3><div class="statline">${vals.map(([k,v])=>`<span><small>${k}</small><b>${Number(v).toLocaleString('fr-FR')}</b></span>`).join('')}</div></section>`:''}
function openCard(id){
  let c=DB.cards.find(x=>x.boxId===id), inTeam=selectedTeam.includes(id);
  let sa=skillText(c.superAttack),usa=skillText(c.ultraSuperAttack),trans=(c.transformations||[]).map(x=>x.name||x.id||x), active=skillText(c.active);
  $('#sheet').innerHTML=`<button onclick="closeSheet()" class="close">Fermer</button><div class="hero"><img src="${c.image}"><div><h2>${c.name||'Carte '+(c.candidateId||'—')}</h2><div>${c.title||''}</div><div class="card-badges"><span>${c.rarity||'—'}</span><span>${c.type||'—'}</span>${c.class?'<span>'+c.class+'</span>':''}${c.eza?'<span>EZA</span>':''}</div><p class="muted">ID ${c.candidateId||'—'} · ${c.confidence}</p><div class="detail-actions"><button class="primary" onclick="toggleTeam('${id}')">${inTeam?'Retirer de l’équipe':'Ajouter à l’équipe'}</button><button class="favorite-btn ${favorites.has(id)?'on':''}" onclick="toggleFavorite('${id}')">${favorites.has(id)?'★ Favori':'☆ Ajouter aux favoris'}</button></div></div></div><section class="detail-section"><h3>Aptitude Leader</h3><p>${c.leader||'—'}</p></section><section class="detail-section"><h3>Passif${c.passiveName?' · '+c.passiveName:''}</h3><p>${c.passive||'—'}</p></section><section class="detail-section"><h3>Attaque spéciale</h3><p>${sa}</p>${usa!=='—'?'<h4>Ultra attaque spéciale</h4><p>'+usa+'</p>':''}</section>${active!=='—'?'<section class="detail-section"><h3>Compétence active</h3><p>'+active+'</p></section>':''}${statsBlock(c)}${tagBlock('Catégories',c.categories)}${tagBlock('Liens',c.links)}${trans.length?tagBlock('Transformations',trans):''}<section class="detail-section provenance"><small>Source des données : ${c.source?.provider||c.sources?.map(x=>x.provider).join(' + ')||'DokkanOS'} · Fiche ${c.fr?'française':'source'}</small></section>`;
  $('#sheet').classList.add('on')
}
function closeSheet(){$('#sheet').classList.remove('on')}
function toggleTeam(id){
  if(selectedTeam.includes(id))selectedTeam=selectedTeam.filter(x=>x!==id);else if(selectedTeam.length<6)selectedTeam.push(id);else return alert('Équipe complète : 6 cartes maximum.');
  localStorage.setItem('dokkanos-team',JSON.stringify(selectedTeam));renderTeam();openCard(id);
}
function commonValues(cards,key){if(cards.length<2)return[];let count={};cards.forEach(c=>new Set(c[key]||[]).forEach(v=>count[v]=(count[v]||0)+1));return Object.entries(count).filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]).slice(0,8)}
function teamInsights(){let cards=selectedTeam.map(id=>DB.cards.find(c=>c.boxId===id)).filter(Boolean),cats=commonValues(cards,'categories'),links=commonValues(cards,'links');if(!cards.length)return '<p class="muted">Ajoute des cartes pour analyser les synergies.</p>';return `<div class="team-insights"><h3>Synergies détectées</h3><p class="muted">${cards.filter(c=>c.name||c.categories?.length||c.links?.length).length}/${cards.length} cartes avec données enrichies</p>${cats.length?`<h4>Catégories communes</h4><div class="tags">${cats.map(([x,n])=>`<span>${x} · ${n}</span>`).join('')}</div>`:''}${links.length?`<h4>Liens communs</h4><div class="tags">${links.map(([x,n])=>`<span>${x} · ${n}</span>`).join('')}</div>`:''}${!cats.length&&!links.length?'<p class="muted">Les synergies apparaîtront automatiquement à mesure que les fiches seront enrichies.</p>':''}</div>`}
function renderDuplicates(){let el=$('#duplicateList');if(!el)return;let groups={};DB.cards.filter(c=>c.candidateId).forEach(c=>(groups[c.candidateId]??=[]).push(c));let d=Object.entries(groups).filter(([,a])=>a.length>1).sort((a,b)=>b[1].length-a[1].length);$('#dupCount').textContent=d.length+' IDs';el.innerHTML=d.map(([id,a])=>`<div class="panel dup-row clickable" onclick="openCard('${a[0].boxId}')"><img src="${a[0].image}"><div><b>${a[0].name||'ID '+id}</b><p class="muted">${a.length} exemplaires · ${a.length-1} doublon(s)</p><small>${a.map(x=>x.boxId).join(' · ')}</small></div></div>`).join('')||'<div class="empty">Aucun doublon détecté.</div>'}
function renderMissing(){let el=$('#missingList');if(!el)return;let owned=ownedIds(),allowed=new Set(['SSR','UR','LR']);let a=(CATALOG.cards||[]).filter(c=>allowed.has(c.rarity)&&inventory[String(c.id)]==='missing');$('#missingCount').textContent=a.length;el.innerHTML=a.slice(0,300).map(c=>`<article class="unit"><img loading="lazy" src="${c.image||''}"><div class="meta"><strong>${c.name||'ID '+c.id}</strong><small>${c.rarity||''} · ${c.type||''}</small></div></article>`).join('')||'<div class="empty">Le catalogue global est en cours de génération.</div>'}
function inventoryState(card){let id=String(card.id||card.candidateId||'');if(inventory[id])return inventory[id];return DB.cards.some(c=>c.validated&&String(c.candidateId)===id)?'owned':'review'}
function ownedIds(){let s=new Set(DB.cards.filter(c=>c.validated&&c.candidateId).map(c=>String(c.candidateId)));Object.entries(inventory).forEach(([id,state])=>{if(state==='owned')s.add(id);if(state==='missing')s.delete(id)});return s}
function setInventory(id,state){id=String(id);inventory[id]=state;localStorage.setItem('dokkanos-inventory',JSON.stringify(inventory));renderInventory();renderMissing();renderManualOwned();renderDuplicates();stats();renderAnalysis()}
function renderInventory(){let el=$('#inventoryList');if(!el)return;let base=(CATALOG.cards||[]).filter(c=>['SSR','UR','LR'].includes(c.rarity));if(!base.length)base=Object.entries(META.cards||{}).map(([id,c])=>({id,name:c.fr?.name||c.name,title:c.fr?.title||c.title,rarity:c.rarity,type:c.fr?.type||c.type,image:'assets/cards/'+id+'.webp'}));let q=norm(inventoryQuery),a=base.filter(c=>(inventoryFilter==='all'?true:inventoryState(c)===inventoryFilter)&&(!q||norm(`${c.id} ${c.name} ${c.title} ${c.rarity} ${c.type}`).includes(q))).slice(0,300);$('#inventoryCount').textContent=a.length;el.innerHTML=a.map(c=>{let id=String(c.id||''),st=inventoryState(c);return `<div class="panel inventory-row"><img src="${c.image||('assets/cards/'+id+'.webp')}" onerror="this.classList.add('imgfail')"><div class="inventory-info"><b>${c.name||'ID '+id}</b><small>${c.rarity||''} · ${c.type||''} · ID ${id}</small><div class="inventory-actions"><button class="${st==='owned'?'selected':''}" onclick="setInventory('${id}','owned')">✓ Je possède</button><button class="${st==='missing'?'selected':''}" onclick="setInventory('${id}','missing')">✕ Non</button><button class="${st==='review'?'selected':''}" onclick="setInventory('${id}','review')">? À vérifier</button></div></div></div>`}).join('')||'<div class="empty">Aucune carte dans ce filtre.</div>'}
function openMetaCard(id){let m=localized(META.cards?.[String(id)]);if(!m)return;let temp={boxId:'MANUAL-'+id,candidateId:String(id),confidence:'Confirmée manuellement',image:'assets/cards/'+id+'.webp',...m};DB.cards.push(temp);openCard(temp.boxId);DB.cards.pop()}
function renderManualOwned(){let el=$('#manualOwned');if(!el)return;let ids=Object.entries(inventory).filter(([,s])=>s==='owned').map(([id])=>id),cards=ids.map(id=>{let m=localized(META.cards?.[id])||{},cat=(CATALOG.cards||[]).find(x=>String(x.id)===id)||{};return {id,...cat,...m,image:cat.image||('assets/cards/'+id+'.webp')}});el.innerHTML=cards.map(x=>`<article class="unit manual-owned" onclick="openMetaCard('${x.id}')"><i class="dot manual"></i><img loading="lazy" src="${x.image}" onerror="this.classList.add('imgfail')"><div class="meta"><strong>${x.name||'ID '+x.id}</strong><small>${x.rarity||''} · confirmé manuellement</small></div></article>`).join('');$('#manualOwnedTitle').style.display=cards.length?'flex':'none'}
function renderTeam(){
  let el=$('#teamSlots');if(!el)return;
  el.innerHTML=[0,1,2,3,4,5].map(i=>{let id=selectedTeam[i],c=DB.cards.find(x=>x.boxId===id);return c?`<button class="slot filled" onclick="openCard('${id}')"><img src="${c.image}"><small>${c.name||c.candidateId}</small></button>`:`<div class="slot"><b>+</b><small>Slot ${i+1}</small></div>`}).join('');
  $('#teamCount').textContent=selectedTeam.length+'/6';let ins=$('#teamInsights');if(ins)ins.innerHTML=teamInsights();
}
function countBy(cards,key){let o={};cards.forEach(c=>{let v=c[key];if(v)o[v]=(o[v]||0)+1});return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function topMulti(cards,key,n=12){let o={};cards.forEach(c=>(c[key]||[]).forEach(v=>o[v]=(o[v]||0)+1));return Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,n)}
function bars(title,rows,total){return `<div class="panel collection-panel"><h3>${title}</h3>${rows.map(([k,n])=>`<div class="metric-row"><div><span>${k}</span><b>${n}</b></div><div class="metric-track"><i style="width:${Math.max(2,Math.round(n/Math.max(1,total)*100))}%"></i></div></div>`).join('')||'<p class="muted">Pas encore de données.</p>'}</div>`}
function renderAnalysis(){
  let el=$('#analysisContent');if(!el)return;
  let valid=DB.cards.filter(c=>c.validated&&c.candidateId),manualIds=Object.entries(inventory).filter(([,s])=>s==='owned').map(([id])=>id),seen=new Set(),owned=[];
  valid.forEach(c=>{let id=String(c.candidateId);if(!seen.has(id)){seen.add(id);owned.push(c)}});
  manualIds.forEach(id=>{if(seen.has(id))return;let m=localized(META.cards?.[id]);if(m){seen.add(id);owned.push({candidateId:id,...m})}});
  let copies={};valid.forEach(c=>copies[c.candidateId]=(copies[c.candidateId]||0)+1);let duplicateCopies=Object.values(copies).reduce((n,x)=>n+Math.max(0,x-1),0);
  let conf={};DB.cards.forEach(c=>conf[c.confidence]=(conf[c.confidence]||0)+1);
  let rarity=countBy(owned,'rarity'),types=countBy(owned,'type'),classes=countBy(owned,'class'),cats=topMulti(owned,'categories'),links=topMulti(owned,'links');
  let eza=owned.filter(c=>c.eza).length,lr=owned.filter(c=>c.rarity==='LR').length,fav=favorites.size,review=DB.cards.filter(c=>!c.validated).length;
  el.innerHTML=`<div class="collection-kpis"><div><b>${owned.length}</b><span>cartes uniques possédées</span></div><div><b>${lr}</b><span>LR</span></div><div><b>${eza}</b><span>EZA</span></div><div><b>${duplicateCopies}</b><span>copies en doublon</span></div><div><b>${fav}</b><span>favoris</span></div><div><b>${review}</b><span>positions à vérifier</span></div></div><div class="analysis-grid">${bars('Raretés',rarity,owned.length)}${bars('Types',types,owned.length)}${bars('Classes',classes,owned.length)}<div class="panel collection-panel"><h3>Origine de l’inventaire</h3><div class="row"><span>Confirmées depuis les captures</span><b>${new Set(valid.map(c=>String(c.candidateId))).size}</b></div><div class="row"><span>Ajouts manuels uniques</span><b>${manualIds.filter(id=>!new Set(valid.map(c=>String(c.candidateId))).has(id)).length}</b></div><div class="row"><span>Progression de validation</span><b>${Math.round((DB.cards.length-review)/Math.max(1,DB.cards.length)*100)}%</b></div></div></div><div class="panel"><h3>Catégories les plus représentées</h3><div class="rank-grid">${cats.map(([x,n])=>`<button onclick="useCollectionFilter('category','${String(x).replace(/'/g,"\\'")}')"><span>${x}</span><b>${n}</b></button>`).join('')}</div></div><div class="panel"><h3>Liens les plus représentés</h3><div class="rank-grid">${links.map(([x,n])=>`<button onclick="useCollectionFilter('link','${String(x).replace(/'/g,"\\'")}')"><span>${x}</span><b>${n}</b></button>`).join('')}</div></div><div class="panel"><h3>Qualité des identifications</h3>${Object.entries(conf).map(([k,v])=>`<div class="row"><span><i class="legend ${confClass(k)}"></i>${k}</span><b>${v}</b></div>`).join('')}</div>`;
}
function useCollectionFilter(kind,value){if(kind==='category'){categoryFilter=value;$('#categoryFilter').value=value}else{linkFilter=value;$('#linkFilter').value=value}switchView('box');render()}
function switchView(v){$$('.view').forEach(x=>x.classList.remove('on'));$('#'+v).classList.add('on');$$('nav button').forEach(x=>x.classList.toggle('on',x.dataset.v===v));if(v==='duplicates')renderDuplicates();if(v==='inventory')renderInventory();if(v==='catalog')renderMissing();if(v==='teams')renderTeam();if(v==='analysis')renderAnalysis()}
document.addEventListener('click',e=>{if(e.target.id==='resetFilters'){rarityFilter=typeFilter=classFilter=categoryFilter=linkFilter=ezaFilter='';favoriteOnly=false;['rarityFilter','typeFilter','classFilter','categoryFilter','linkFilter','ezaFilter'].forEach(id=>$('#'+id).value='');$('#favoriteFilter').classList.remove('on');render()}if(e.target.id==='favoriteFilter'){favoriteOnly=!favoriteOnly;e.target.classList.toggle('on',favoriteOnly);render()}if(e.target.matches('.invchip')){$('.invchip').forEach(x=>x.classList.remove('on'));e.target.classList.add('on');inventoryFilter=e.target.dataset.invf;renderInventory()}if(e.target.matches('.chip')){$$('.chip').forEach(x=>x.classList.remove('on'));e.target.classList.add('on');filter=e.target.dataset.f;render()}if(e.target.matches('nav button'))switchView(e.target.dataset.v)});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=norm(e.target.value);render()}if(e.target.id==='inventorySearch'){inventoryQuery=e.target.value;renderInventory()}});
document.addEventListener('change',e=>{if(e.target.id==='sort')sortMode=e.target.value;if(e.target.id==='rarityFilter')rarityFilter=e.target.value;if(e.target.id==='typeFilter')typeFilter=e.target.value;if(e.target.id==='classFilter')classFilter=e.target.value;if(e.target.id==='categoryFilter')categoryFilter=e.target.value;if(e.target.id==='linkFilter')linkFilter=e.target.value;if(e.target.id==='ezaFilter')ezaFilter=e.target.value;render()});
window.addEventListener('online',()=>document.body.classList.remove('offline'));window.addEventListener('offline',()=>document.body.classList.add('offline'));if(!navigator.onLine)document.body.classList.add('offline');
boot().catch(()=>{document.body.innerHTML='<div class="fatal"><h2>DokkanOS</h2><p>Impossible de charger la Box. Réessaie avec une connexion internet.</p><button onclick="location.reload()">Réessayer</button></div>'});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
