
let DB={cards:[]}, filter='all', query='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function boot(){DB=await fetch('data.json').then(r=>r.json()); render(); stats();}
function confClass(c){return c==='Très forte'?'tf':c==='Forte'?'f':c==='Moyenne'?'m':'v'}
function visibleCards(){return DB.cards.filter(c=>(filter==='all'||(filter==='valid'&&c.validated)||(filter==='check'&&!c.validated)) && (!query||(`${c.boxId} ${c.candidateId} ${c.name} ${c.title}`).toLowerCase().includes(query)))}
function render(){let a=visibleCards(); $('#grid').innerHTML=a.map(c=>`<article class="unit" onclick="openCard('${c.boxId}')"><i class="dot ${confClass(c.confidence)}"></i><img loading="lazy" src="${c.image}"><div class="meta"><strong>${c.name||'ID '+c.candidateId}</strong><small>${c.boxId} · ${c.confidence}</small></div></article>`).join('')||'<div class="empty">Aucune carte</div>'; renderVerify();}
function stats(){let v=DB.cards.filter(c=>c.validated).length; $('#nAll').textContent=DB.cards.length;$('#nVal').textContent=v;$('#nCheck').textContent=DB.cards.length-v;}
function renderVerify(){let a=DB.cards.filter(c=>!c.validated).slice(0,30);$('#verifyList').innerHTML=a.map(c=>`<div class="panel"><b>${c.boxId}</b><p style="color:#8c98aa;font-size:12px">${c.capture} · ${c.position} · ${c.confidence}</p><div class="verify"><div><img src="${c.crop}"><label>Ta capture</label></div><div><img src="${c.image}"><label>ID ${c.candidateId}</label></div><div><img src="${c.runnerImage}"><label>ID ${c.runnerId}</label></div><button onclick="choose('${c.boxId}','${c.candidateId}')">Choisir 1</button><button onclick="choose('${c.boxId}','${c.runnerId}')">Choisir 2</button><button onclick="choose('${c.boxId}','')">Aucun</button></div></div>`).join('');}
function choose(id,val){let c=DB.cards.find(x=>x.boxId===id);if(!c)return;if(val){c.candidateId=val;c.image='assets/cards/'+val+'.webp';c.validated=true;c.confidence='Validée manuellement'}else{c.validated=false;c.confidence='À revoir'};localStorage.setItem('dokkanos-edits',JSON.stringify(DB.cards.map(x=>({boxId:x.boxId,candidateId:x.candidateId,validated:x.validated,confidence:x.confidence}))));render();stats();}
function openCard(id){let c=DB.cards.find(x=>x.boxId===id);$('#sheet').innerHTML=`<button onclick="closeSheet()" style="float:right;background:#222c3c;color:white;border:0;border-radius:10px;padding:8px 12px">Fermer</button><div class="hero"><img src="${c.image}"><div><h2>${c.name||'Carte '+c.candidateId}</h2><div>${c.title||'Fiche à enrichir'}</div><p style="color:#8c98aa">${c.confidence}</p></div></div>${[['ID Dokkan',c.candidateId],['Capture',c.capture+' '+c.position],['Rareté',c.rarity||'—'],['Type',c.type||'—'],['Classe',c.class||'—'],['EZA / SEZA',(c.eza||'—')+' / '+(c.seza||'—')],['Leader',c.leader||'—'],['Passif',c.passive||'—'],['SP',c.superAttack||'—'],['Active',c.active||'—'],['Catégories',(c.categories||[]).join(', ')||'—'],['Liens',(c.links||[]).join(', ')||'—']].map(x=>`<div class="kv"><span>${x[0]}</span><span>${x[1]}</span></div>`).join('')}`;$('#sheet').classList.add('on')}
function closeSheet(){$('#sheet').classList.remove('on')}
function switchView(v){$$('.view').forEach(x=>x.classList.remove('on'));$('#'+v).classList.add('on');$$('nav button').forEach(x=>x.classList.toggle('on',x.dataset.v===v));}
document.addEventListener('click',e=>{if(e.target.matches('.chip')){$$('.chip').forEach(x=>x.classList.remove('on'));e.target.classList.add('on');filter=e.target.dataset.f;render()}if(e.target.matches('nav button'))switchView(e.target.dataset.v)});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value.toLowerCase();render()}});
boot().then(()=>{let e=JSON.parse(localStorage.getItem('dokkanos-edits')||'[]');e.forEach(a=>{let c=DB.cards.find(x=>x.boxId===a.boxId);if(c)Object.assign(c,a,{image:'assets/cards/'+a.candidateId+'.webp'})});render();stats()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
