/* A separate session ledger. Never writes inventory or the classic team. */
(function(){'use strict';
const M=window.DokkanBattlefieldModel,E=window.DokkanTeamEngine,esc=teamEsc,clone=x=>JSON.parse(JSON.stringify(x)),cid=c=>String(c.candidateId||c.id);
let state={version:1,active:'global-109',sessions:{}},mode='classic',data=null,error='',status='',busy=false,job=0,worker=null,rejectJob=null,backup=null,bossId='yamu',search='',poolCache=null,lastRenderMs=0;
try{const raw=storageRead(M.key);if(raw)state=M.validate(JSON.parse(raw));}catch(e){error='Le suivi enregistré est illisible. Il est conservé ; exporte une sauvegarde avant de réinitialiser.';}
const session=()=>state.sessions[state.active]||M.empty(),edition=()=>data?.editions.find(x=>x.id===state.active),boss=()=>edition()?.bosses.find(b=>b.id===bossId)||edition()?.bosses[0];
const pool=()=>poolCache||(poolCache=[...new Map(teamOwnedCards().filter(isPlayableCard).map(c=>[cid(c),c])).values()]);
window.addEventListener('dokkanos-state-change',()=>{poolCache=null;});
function save(s){if(error)throw Error(error);M.validate(s);if(!storageWrite(M.key,JSON.stringify(s)))throw Error('Le suivi n’a pas pu être sauvegardé.');state=s;backup=null;}
function saveSession(s){const n=clone(state);n.sessions[n.active]=s;save(n);}
function cancel(){job++;worker?.terminate();worker=null;const reject=rejectJob;rejectJob=null;busy=false;reject?.(Error('Recherche annulée.'));}
function modeBar(){return '<div class="bf-modes" role="group" aria-label="Mode de composition"><button data-bf-mode="classic" aria-pressed="'+(mode==='classic')+'">Équipe classique</button><button data-bf-mode="battlefield" aria-pressed="'+(mode==='battlefield')+'">Battlefield</button></div>';}
function leaderDetails(e){if(!e?.cover)return '';const range=(field,n)=>{const values=e.cover.map(a=>a[n][field]),lo=Math.min(...values),hi=Math.max(...values);return lo===hi?lo:lo+' à '+hi;};return '<p class="muted">Bonus réels selon les sept cartes : '+[0,1].map(n=>(n?'Sous-leader':'Leader')+' Ki +'+range('ki',n)+' · PV +'+range('hp',n)+' % · ATT +'+range('atk',n)+' % · DÉF +'+range('def',n)+' %').join(' / ')+'.</p>'+(e.profiles?.some(p=>!p.complete)?'<p class="muted">Certains kits sont incomplets : vérifie les passifs et conditions dans les fiches avant de jouer.</p>':'');}
function teamRows(ids,replaceable){const mine=new Map(pool().map(c=>[cid(c),c]));return '<div class="bf-cards">'+ids.map((i,n)=>{const c=mine.get(i);return '<article class="bf-card">'+(c?teamImage(c):'')+'<div><small>'+(['Leader','Sous-leader'][n]||'Partenaire')+' · '+esc(c?.type||'?')+'</small><b>'+esc(c?.name||'Carte indisponible')+'</b><span>'+esc(c?.title||i)+'</span>'+(replaceable?'<button data-bf-replace="'+n+'" '+(busy?'disabled':'')+'>Remplacer automatiquement</button>':'')+'</div></article>';}).join('')+'</div>';}
function render(){const started=performance.now();poolCache=null;const host=document.querySelector('#teams main');if(!host)return;const ed=edition(),s=session(),b=boss(),mine=pool(),spent=M.used(s),done=M.won(s),assigned=new Set(Object.values(s.plan).flat()),ids=s.plan[b?.id]||[],team=ids.map(i=>mine.find(c=>cid(c)===i));
 host.dataset.teamMode='battlefield';host.innerHTML=modeBar()+'<div class="team-heading"><div><span class="eyebrow">PLANIFICATEUR DE SESSION</span><h2>Battlefield</h2><p class="muted">Ta Box confirmée · derniers éveils uniquement · aucun leader ami.</p></div></div>';
 if(!ed||!b){host.insertAdjacentHTML('beforeend','<p role="status">'+esc(status||'Chargement des données Battlefield…')+'</p>');return;}
 const evaluation=team.length===7&&team.every(Boolean)?M.assess(E,team,b,teamKnown()):null;
 const expired=Date.now()>Date.parse(ed.end);
 host.insertAdjacentHTML('beforeend',`<section class="panel bf-panel"><h3>${esc(ed.name)}</h3><p>${spent.size}/${ed.slotLimit} emplacements utilisés · ${assigned.size} cartes planifiées · ${Math.max(0,ed.slotLimit-spent.size-assigned.size)} emplacements de secours · ${mine.length} cartes éligibles</p><p class="muted">${expired?'Édition terminée : ce plan reste consultable. ':''}Données du ${esc(data.verifiedAt)}. Première édition prise en charge : GLOBAL #${ed.number}. Aucun format ancien ni Frontier n’est appliqué ici.</p><p class="muted">Deux leaders internes couvrent les sept cartes. Les kits sélectionnés dans tes fiches sont utilisés, sans supposer que tu as réalisé un éveil Z. Le calcul est une recherche heuristique, pas une garantie de victoire ni d’optimum absolu.</p><div class="bf-actions"><button data-bf-action="generate" ${busy||error?'disabled':''}>Préparer / recalculer le parcours</button>${busy?'<button data-bf-action="cancel">Annuler</button>':''}<button data-bf-action="reset" ${busy?'disabled':''}>Nouvelle session</button>${state.previous?'<button data-bf-action="restore">Récupérer la session précédente</button>':''}</div><p id="bfStatus" role="status" aria-live="polite">${esc(error||status)}</p></section>
 <section class="panel bf-panel"><label for="bfBoss">Combat à préparer</label><select id="bfBoss">${ed.bosses.map(x=>'<option value="'+x.id+'" '+(b.id===x.id?'selected':'')+'>Niveau '+x.level+' · '+esc(x.name)+' · '+x.type+(done.has(x.id)?' · gagné':'')+'</option>').join('')}</select><h3>${esc(b.name)} · ${b.type}</h3><p>${(b.hp/1000000).toLocaleString('fr-FR')} millions de PV · avantage de type : ${M.advantage[b.type]}</p><ul>${b.effects.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul><p>${b.tips.map(esc).join(' ')}</p><p class="muted">ATT/DÉF et dégâts SP exacts inconnus. Une immunité non recensée n’est pas considérée comme une vulnérabilité confirmée. Vérifie les restrictions dans le jeu.</p>${b.optionalType?'<label><input id="bfMission" type="checkbox" '+(s.missionTypes[b.id]?'checked':'')+' '+(busy?'disabled':'')+'> Mission : sept cartes INT</label>':''}<p><a href="${ed.source}" target="_blank" rel="noopener noreferrer">Source de cette édition</a></p></section>
 <section class="panel bf-panel"><h3>Équipe du combat${done.has(b.id)?' · victoire enregistrée':''}</h3>${ids.length?teamRows(ids,true):'<p class="muted">Aucune équipe prévue. Lance le calcul du parcours, ou compose une équipe de secours avec les cartes libres.</p>'}${evaluation?'<p class="muted">'+(evaluation.valid?'Sept cartes couvertes par les deux leaders.':'Équipe devenue incompatible : recalcule le parcours.')+' '+''+'</p>'+leaderDetails(evaluation):''}<div class="bf-actions">${ids.length?'<button data-bf-action="lock" '+(busy?'disabled':'')+'>'+(s.locked.includes(b.id)?'Déverrouiller':'Conserver cette équipe au recalcul')+'</button>':''}<button data-bf-action="backup" ${busy||done.has(b.id)||error?'disabled':''}>Chercher une équipe de secours</button></div>${backup&&backup.boss===b.id?'<h4>Secours proposé · sept autres cartes</h4>'+teamRows(backup.cards,false)+'<button data-bf-action="useBackup">Utiliser ce secours pour ce combat</button>':''}${ids.length&&!done.has(b.id)?'<div class="bf-result"><label for="bfHP">PV ennemis restants après défaite (%) — facultatif</label><input id="bfHP" type="number" min="0" max="100" step="0.1" inputmode="decimal"><div class="bf-actions"><button data-bf-action="victory" '+(busy?'disabled':'')+'>Enregistrer une victoire</button><button data-bf-action="defeat" '+(busy?'disabled':'')+'>Enregistrer une défaite</button></div><small>À renseigner après le combat réel. Les sept cartes deviennent utilisées, même après une défaite.</small></div>':''}</section>
 <details class="panel bf-panel"><summary>Réserver des cartes pour ${esc(b.name)}</summary><p class="muted">Les réservations imposent une carte à ce boss et l’écartent des autres équipes au recalcul. Une carte exclue est écartée de toute la session.</p><div class="bf-actions">${(s.reserved[b.id]||[]).map(i=>'<button data-bf-release="'+i+'">Retirer : '+esc(mine.find(c=>cid(c)===i)?.name||i)+'</button>').join('')}</div><label for="bfSearch">Chercher dans les cartes confirmées disponibles</label><input id="bfSearch" type="search" value="${esc(search)}" placeholder="Nom ou ID"><div id="bfSearchResults"></div>${s.excluded.length?'<p>'+s.excluded.length+' carte(s) exclue(s). <button data-bf-action="unexclude">Réintégrer les cartes exclues</button></p>':''}</details>
 <details class="panel bf-panel"><summary>Parcours · ${done.size}/${ed.bosses.length} victoires</summary><p class="muted">Le calcul réserve les cartes pour les combats difficiles en premier. L’ordre ci-dessous n’impose pas les déblocages du jeu.</p>${ed.bosses.map(x=>'<details><summary>Niveau '+x.level+' · '+esc(x.name)+(done.has(x.id)?' · gagné':s.plan[x.id]?' · équipe prête':' · non préparé')+'</summary>'+(s.plan[x.id]?teamRows(s.plan[x.id],false)+'<button data-bf-free="'+x.id+'" '+(busy?'disabled':'')+'>Libérer cette équipe du plan</button>':'')+'</details>').join('')}</details>
 <details class="panel bf-panel"><summary>Historique · ${s.attempts.length} combat(s)</summary>${s.attempts.map(a=>'<p>'+esc(ed.bosses.find(x=>x.id===a.boss)?.name||a.boss)+' · '+(a.result==='victory'?'Victoire':'Défaite')+(a.hp!==null?' · '+a.hp+' % PV restants':'')+' · '+esc(new Date(a.date).toLocaleString('fr-FR'))+'</p>').join('')}${s.attempts.length?'<button data-bf-action="undo">Annuler le dernier résultat</button>':''}</details><p class="muted">Les missions de tours et les catégories non identifiées restent à vérifier en jeu. Ton suivi est sauvegardé localement et inclus dans l’export de sauvegarde de Mes outils.</p>`);
 renderSearch();lastRenderMs=performance.now()-started;
}
function renderSearch(){const host=document.getElementById('bfSearchResults');if(!host)return;const s=session(),spent=M.used(s),taken=new Set(Object.values(s.reserved).flat()),q=search.toLocaleLowerCase('fr-FR');host.innerHTML=pool().filter(c=>!spent.has(cid(c))&&!taken.has(cid(c))&&!s.excluded.includes(cid(c))&&(!q||((c.name||'')+' '+(c.title||'')+' '+cid(c)).toLocaleLowerCase('fr-FR').includes(q))).slice(0,12).map(c=>'<div class="bf-search-row"><span>'+esc(c.name)+' · '+esc(c.type)+' · '+cid(c)+'</span><button data-bf-reserve="'+cid(c)+'" '+(busy?'disabled':'')+'>Réserver</button><button data-bf-exclude="'+cid(c)+'" '+(busy?'disabled':'')+'>Exclure</button></div>').join('');}
const classic=renderTeam;
renderTeam=function(){if(mode==='battlefield')render();else{const host=document.querySelector('#teams main');if(host)host.dataset.teamMode='classic';classic();if(host&&!host.querySelector('.bf-modes'))host.insertAdjacentHTML('afterbegin',modeBar());}};
async function execute(r,token){
 const fallback=()=>r.action==='replace'?M.replace(E,r.pool,r.team,r.boss,r.known,r.index,r.reserved):r.action==='backup'?M.compose(E,r.pool,r.boss,r.known,[],()=>{},()=>token!==job):M.plan(E,r.pool,r.edition,r.session,r.known,progress,()=>token!==job);
 function progress(message){if(token!==job)return;status=message;const el=document.getElementById('bfStatus');if(el)el.textContent=message;}
 if(typeof Worker==='undefined')return fallback();
 return new Promise((resolve,reject)=>{rejectJob=reject;try{worker=new Worker('battlefield-worker.js?v=2700');worker.onmessage=e=>{if(token!==job)return;if(e.data.progress){progress(e.data.progress);return;}worker.terminate();worker=null;rejectJob=null;e.data.error?reject(Error(e.data.error)):resolve(e.data.value);};worker.onerror=()=>{worker?.terminate();worker=null;rejectJob=null;reject(Error('Le calcul en arrière-plan a échoué. Réessaie après avoir rechargé l’app.'));};worker.postMessage(r);}catch(e){worker?.terminate();worker=null;rejectJob=null;Promise.resolve().then(fallback).then(resolve,reject);}});
}
function freePool(current,excludeCurrent=true){const s=session(),spent=M.used(s),reserved=new Set(Object.entries(s.reserved).filter(([k])=>k!==current).flatMap(([,a])=>a)),assigned=new Set(Object.entries(s.plan).filter(([k])=>excludeCurrent||k!==current).flatMap(([,a])=>a));return pool().filter(c=>!spent.has(cid(c))&&!assigned.has(cid(c))&&!reserved.has(cid(c))&&!s.excluded.includes(cid(c))&&(!s.missionTypes[current]||c.type===s.missionTypes[current]));}
async function calculate(action,index){if(busy||error)return;const ed=edition(),b=boss();if(!ed||!b)return;const s=session(),token=++job,r={action,known:teamKnown(),boss:b};
 if(action==='generate')Object.assign(r,{pool:pool(),edition:ed,session:clone(s)});
 else if(action==='replace')Object.assign(r,{pool:freePool(b.id,false),team:(s.plan[b.id]||[]).map(i=>pool().find(c=>cid(c)===i)),index,reserved:s.reserved[b.id]||[]});
 else{if(M.used(s).size+new Set(Object.values(s.plan).flat()).size+7>ed.slotLimit){status='Pas assez d’emplacements libres pour sept cartes de secours. Libère une équipe future ou recalcule le parcours.';render();return;}r.pool=freePool(b.id);}
 busy=true;status='Recherche en arrière-plan…';render();const started=performance.now();
 try{const value=await execute(r,token);if(token!==job)return;if(!value)throw Error('Aucune alternative compatible trouvée parmi les cartes libres.');
 if(action==='backup'){backup={boss:b.id,cards:value.cards};status='Équipe de secours proposée.';}
 else{const next=clone(session());if(action==='generate')next.plan=value.plan;else next.plan[b.id]=value.cards;saveSession(next);status=(action==='generate'?(value.warnings.length?value.warnings.join(' '):'Parcours préparé sans réutiliser de carte.'):'Seule la carte choisie a été remplacée.')+' · '+((performance.now()-started)/1000).toFixed(1)+' s';}
 }catch(e){if(token===job)status=e.message;}finally{if(token===job){busy=false;render();}}
}
document.addEventListener('input',e=>{if(e.target.id==='bfSearch'){search=e.target.value;renderSearch();}});
document.addEventListener('change',e=>{if(e.target.id==='bfBoss'){cancel();backup=null;bossId=e.target.value;render();}if(e.target.id==='bfMission'){cancel();try{const s=clone(session()),b=boss();if(e.target.checked)s.missionTypes[b.id]=b.optionalType;else delete s.missionTypes[b.id];delete s.plan[b.id];s.locked=s.locked.filter(k=>k!==b.id);saveSession(s);status='Mission modifiée : recalcule le parcours.';}catch(x){status=x.message;}render();}});
document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const d=button.dataset;
 if(d.bfMode){cancel();mode=d.bfMode;renderTeam();return;}
 if(d.bfReplace!==undefined){calculate('replace',Number(d.bfReplace));return;}
 if(!d.bfAction&&!d.bfReserve&&!d.bfRelease&&!d.bfExclude&&!d.bfFree)return;
 if(d.bfAction==='cancel'){cancel();status='Recherche annulée ; le plan précédent est conservé.';render();return;}
 if(busy)return;
 if(['generate','backup'].includes(d.bfAction)){calculate(d.bfAction);return;}
 try{let s=clone(session()),b=boss();
 if(d.bfReserve){if((s.reserved[b.id]||[]).length>=7)throw Error('Sept réservations maximum par boss.');s.reserved[b.id]=[...new Set([...(s.reserved[b.id]||[]),d.bfReserve])];s.locked=s.locked.filter(k=>k!==b.id);s.plan={};s.locked=[];status='Carte réservée. Recalcule le parcours pour appliquer les réservations.';}
 else if(d.bfFree){delete s.plan[d.bfFree];s.locked=s.locked.filter(i=>i!==d.bfFree);status='Sept emplacements libérés du plan ; les réservations restent en place.';}
 else if(d.bfRelease){s.reserved[b.id]=(s.reserved[b.id]||[]).filter(i=>i!==d.bfRelease);}
 else if(d.bfExclude){s.excluded=[...new Set([...s.excluded,d.bfExclude])];s.plan={};s.locked=[];status='Carte exclue de la session ; Box inchangée.';}
 else if(d.bfAction==='lock'){s.locked=s.locked.includes(b.id)?s.locked.filter(i=>i!==b.id):[...s.locked,b.id];}
 else if(d.bfAction==='useBackup'){if(!backup||backup.boss!==b.id)throw Error('Secours indisponible.');const available=new Set(freePool(b.id).map(cid));if(backup.cards.some(i=>!available.has(i)))throw Error('Le secours n’est plus disponible.');s.plan[b.id]=backup.cards;s.locked=s.locked.filter(k=>k!==b.id);s.reserved[b.id]=[];status='Secours utilisé. L’ancienne équipe redevient libre.';}
 else if(['victory','defeat'].includes(d.bfAction)){const input=document.getElementById('bfHP').value,hp=input===''?null:Number(input);if(!confirm('Confirmer le résultat réel ? Les sept cartes de cette équipe seront marquées utilisées dans la session, pas dans ta Box.'))return;s=M.result(s,edition(),b.id,d.bfAction,hp,pool());status='Résultat enregistré. Les autres équipes prévues sont conservées.';}
 else if(d.bfAction==='undo'){if(!confirm('Annuler le dernier résultat ? Le parcours devra être recalculé.'))return;s.attempts.pop();s.plan={};s.locked=[];status='Dernier résultat annulé ; cartes à nouveau disponibles.';}
 else if(d.bfAction==='unexclude'){s.excluded=[];}
 else if(d.bfAction==='reset'){if(!confirm('Commencer une nouvelle session Battlefield ? La session précédente restera récupérable. Ta Box ne change pas.'))return;if(error){if(!confirm('Le suivi est illisible. Son remplacement est irréversible sans export. As-tu conservé ta sauvegarde ?'))return;error='';state={version:1,active:'global-109',sessions:{}};}const n=clone(state);n.previous=s;n.sessions[n.active]=M.empty();save(n);status='Nouvelle session prête.';render();return;}
 else if(d.bfAction==='restore'){if(!state.previous||!confirm('Récupérer la session précédente et échanger avec la session actuelle ?'))return;const n=clone(state);n.sessions[n.active]=n.previous;n.previous=s;save(n);status='Session précédente récupérée.';render();return;}
 else return;
 saveSession(s);
 }catch(x){status=x.message;}render();
});
const ready=fetch('battlefield-data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(d.schema!=='dokkanos-battlefield-v1'||!Array.isArray(d.editions)||!d.editions.length)throw Error();data=d;if(!edition())state.active=d.editions[0].id;if(mode==='battlefield')render();return d;}).catch(()=>{status='Données Battlefield indisponibles. Recharge l’app avec une connexion.';if(mode==='battlefield')render();return null;});
window.addEventListener('dokkanos-data-ready',()=>{poolCache=null;if(mode==='battlefield')render();});
window.DokkanBattlefield={ready,open(){cancel();mode='battlefield';switchView('teams');},calculate,cancel,getState:()=>clone(state),getPool:pool,getTiming:()=>({lastRenderMs})};
})();
