/* Catalogue and card sheets. Z kits are independent versions of the same card. */
(function(){
'use strict';
const CM=window.DokkanCatalogModel,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let indexArray,indexLength=-1,index=new Map(),report={status:'pending'},page=0,sheetId='',sheetTab='info',sheetVersion='base';
let settings={scope:'all',forms:'final',rarity:'',type:'',class:'',z:'',kit:'',sort:'recent'};
try{const s=JSON.parse(storageRead('dokkanos-catalogue-v4')||'{}');for(const k of Object.keys(settings))if(typeof s?.[k]==='string')settings[k]=s[k]}catch(e){}
for(const [k,values] of Object.entries({scope:['all','owned','missing','review'],forms:['final','all'],rarity:['','SSR','UR','LR'],type:['','AGI','TEC','INT','PUI','END'],class:['','Super','Extrême'],z:['','any','none',...Object.keys(CM.labels)],kit:['','complete','partial'],sort:['recent','name','id']}))if(!values.includes(settings[k]))settings[k]=values[0];
let selectedKits={};try{const s=JSON.parse(storageRead('dokkanos-kit-versions-v4')||'{}');if(record(s))selectedKits=s}catch(e){}
function lookup(id){const cards=CATALOG.cards||[];if(indexArray!==cards||indexLength!==cards.length){indexArray=cards;indexLength=cards.length;index=new Map(cards.map(c=>[String(c.id),c]));}return index.get(String(id))||{}}
localAssetIdFor=function(cardId){cardId=String(cardId||'');const c=lookup(cardId),m=META.cards?.[cardId]||{};return String(c.resourceId||c.resource_id||m.resourceId||m.resource_id||c.imageId||m.imageId||cardId)};
localCardImage=function(id,preferred){const c=lookup(id);return c.image||preferred||'assets/cards/'+localAssetIdFor(id)+'.webp'};
verifyCandidate=function(id){id=String(id||'');const raw=META.cards?.[id],cat=lookup(id);if(!raw&&!cat.id)return null;const m=localized(raw)||{};return {id,...m,...cat,rarity:cat.rarity||m.rarity,type:cat.type||m.type,class:cat.class||m.class,name:bestFrenchName({...m,id},cat),title:frTerm(cat.titleFr||cat.fr?.title||m.title||cat.title),categories:frList(cat.fr?.categories||m.categories||cat.categories),links:frList(cat.fr?.links||m.links||cat.links),image:localCardImage(id,cat.image||m.image),zAwakenings:m.zAwakenings||cat.zAwakenings||[]}};
verifyCatalogue=function(){return(CATALOG.cards||[]).filter(CM.allowed).map(c=>verifyCandidate(c.id)).filter(isPlayableCard)};
teamCatalog=function(){return verifyCatalogue()};
const resolveOriginal=resolveCard,ownedOriginal=ownedTeamCards;
resolveCard=function(id){if(String(id).startsWith('CATALOG-')){const c=verifyCandidate(String(id).slice(8));return c?{...c,candidateId:c.id,boxId:id,_catalogue:true,confidence:'Catalogue vérifié par ID'}:null;}const c=resolveOriginal(id);if(!c)return null;const data=verifyCandidate(c.candidateId),merged={...c,zAwakenings:data?.zAwakenings||c.zAwakenings||[],image:localCardImage(c.candidateId,c.image)};return CM.selectKit(merged,selectedKits[String(c.candidateId)]||'base')};
ownedTeamCards=function(){return ownedOriginal().map(c=>CM.selectKit({...c,zAwakenings:verifyCandidate(c.candidateId)?.zAwakenings||c.zAwakenings||[]},selectedKits[String(c.candidateId)]||'base'))};
const image=c=>'<img loading="lazy" src="'+esc(c.image)+'" alt="'+esc(c.name)+'" onerror="imageFallback(this,\''+esc(c.candidateId||c.id)+'\',\'\')">';
const option=(v,l,current)=>'<option value="'+esc(v)+'" '+(v===current?'selected':'')+'>'+esc(l)+'</option>';
function field(key,label,values){return '<label>'+label+'<select data-catalog-filter="'+key+'">'+values.map(([v,l])=>option(v,l,settings[key])).join('')+'</select></label>';}
function currentCards(){return (CATALOG.cards||[]).filter(CM.allowed).map(c=>{const card=verifyCandidate(c.id);return {...card,_state:inventoryState(card)}}).filter(isPlayableCard);}
renderMissing=function(){
 const host=document.querySelector('#catalog main');if(!host)return;
 const all=currentCards(),filtered=CM.filter(all,{...settings,query:missingQuery}),pages=Math.max(1,Math.ceil(filtered.length/60));page=Math.min(page,pages-1);
 const rows=filtered.slice(page*60,(page+1)*60);
 const verified=report.status==='complete',date=report.checkedAt?new Date(report.checkedAt).toLocaleDateString('fr-FR'):'en cours';
 host.innerHTML='<div class="section-title"><div><span class="eyebrow">SSR · UR · LR</span><h2>Catalogue Dokkan</h2><p class="muted">Une fiche par carte ; les kits Z restent dans son onglet Éveils Z.</p></div><span id="missingCount" class="badge neutral">'+filtered.length+'</span></div>'+
 '<div class="catalog-summary"><span><b>'+all.length+'</b> formes référencées</span><span><b>'+all.filter(c=>c._state==='owned').length+'</b> formes de cartes possédées</span><span><b>'+all.filter(c=>CM.variants(c).length).length+'</b> fiches avec kit Z vérifié</span></div>'+
 '<p class="muted" id="catalogDataStatus">Mise à jour : '+esc(date)+(verified?' · collecte et images contrôlées.':' · '+esc(report.note||'Contrôle complet en cours, les données partielles restent signalées.'))+'</p>'+
 '<label>Rechercher<input id="missingQuery" type="search" class="search" placeholder="Nom, SSJ3, ID, catégorie ou lien…" value="'+esc(missingQuery)+'"></label>'+
 '<div class="catalog-scopes">'+[['all','Toutes'],['owned','Mes cartes'],['missing','Non possédées'],['review','À confirmer']].map(([v,l])=>'<button data-catalog-scope="'+v+'" aria-pressed="'+(settings.scope===v)+'">'+l+'</button>').join('')+'</div>'+
 '<details class="panel catalog-filters"><summary>Filtres et affichage</summary><div class="catalog-filter-grid">'+
 field('forms','Formes',[['final','Éveils maximum'],['all','Toutes les SSR / UR / LR']])+field('rarity','Rareté',[['','Toutes'],['SSR','SSR'],['UR','UR'],['LR','LR']])+
 field('type','Type',[['','Tous'],...['AGI','TEC','INT','PUI','END'].map(v=>[v,v])])+field('class','Classe',[['','Toutes'],['Super','Super'],['Extrême','Extrême']])+
 field('z','Éveil Z',[['','Tous'],['any','Avec kit Z'],['none','Sans kit Z vérifié'],...Object.entries(CM.labels)])+
 field('kit','Informations',[['','Toutes'],['complete','Kit vérifié'],['partial','Fiche à compléter']])+field('sort','Tri',[['recent','Sorties récentes'],['name','Nom A → Z'],['id','ID décroissant']])+
 '</div><button data-catalog-reset>Réinitialiser les filtres</button></details>'+
 '<div id="missingList" class="grid catalog-grid">'+rows.map(c=>'<article class="unit"><button class="catalog-open" data-catalog-open="'+esc(c.id)+'">'+image(c)+'<div class="meta"><strong>'+esc(c.name)+'</strong><small>'+esc(c.title)+'</small><small>'+c.rarity+' · '+esc(c.type)+' · ID '+esc(c.id)+'</small><span class="catalog-owned">'+({owned:'✓ Possédée',missing:'Non possédée',review:'À confirmer'}[c._state])+'</span><div class="catalog-z-badges">'+CM.variants(c).map(v=>'<span>'+v.label+'</span>').join('')+'</div>'+(c.dataStatus?.kit==='verified'?'':'<small class="ai-warning">Informations partielles</small>')+'</div></button></article>').join('')+(rows.length?'':'<p class="empty">Aucune carte pour ces filtres.</p>')+'</div>'+
 '<div class="catalog-pages"><button data-catalog-page="'+(page-1)+'" '+(!page?'disabled':'')+'>Précédent</button><span>Page '+(page+1)+' / '+pages+'</span><button data-catalog-page="'+(page+1)+'" '+(page>=pages-1?'disabled':'')+'>Suivant</button></div>';
};
function skill(value){return esc(skillText(value));}
function stats(c){const items=[['PV',c.maxHP],['ATT',c.maxATK],['DÉF',c.maxDEF],['Coût',c.cost],['Niveau max.',c.maxLevel],['ATT SP max.',c.maxSALevel]].filter(([,v])=>v!==undefined&&v!==null);return items.length?'<section class="detail-section"><h3>Statistiques hors potentiel</h3><div class="statline">'+items.map(([l,v])=>'<span><small>'+l+'</small><b>'+esc(Number(v).toLocaleString('fr-FR'))+'</b></span>').join('')+'</div>':'';}
function tags(label,values){return values?.length?'<section class="detail-section"><h3>'+label+'</h3><div class="tags">'+values.map(v=>'<span>'+esc(v)+'</span>').join('')+'</div>':'';}
function kit(c){const extras=(c.supers||[]).filter(s=>s.name!==c.superAttack?.name&&s.name!==c.ultraSuperAttack?.name);return '<section class="detail-section"><h3>Aptitude leader</h3><p>'+skill(c.leader)+'</p></section><section class="detail-section"><h3>Passif'+(c.passiveName?' · '+esc(c.passiveName):'')+'</h3><p>'+skill(c.passive)+'</p></section><section class="detail-section"><h3>Attaque spéciale</h3><p>'+skill(c.superAttack)+'</p>'+(c.ultraSuperAttack?'<h4>Ultra attaque spéciale</h4><p>'+skill(c.ultraSuperAttack)+'</p>':'')+extras.map(s=>'<h4>'+esc(s.name)+'</h4><p>'+skill(s)+(s.condition?'<br>'+esc(s.condition):'')+'</p>').join('')+'</section>'+(c.active?'<section class="detail-section"><h3>Aptitude active</h3><p>'+skill(c.active)+'</p></section>':'')+stats(c);}
function source(c){const s=c._kitSource||c.source||{},url=s.url;return '<section class="detail-section provenance"><small>'+esc(s.provider||'DokkanOS')+'</small>'+(typeof url==='string'&&/^https:\/\//.test(url)?'<a target="_blank" rel="noopener" href="'+esc(url)+'">Consulter la fiche source</a>':'')+'</section>';}
openCard=function(id){sheetId=String(id);sheetTab='info';const c=resolveCard(id);sheetVersion=selectedKits[String(c?.candidateId)]||'base';renderSheet();};
function renderSheet(){
 const card=resolveCard(sheetId);if(!card)return;
 const data=verifyCandidate(card.candidateId)||card,base={...card,...data,boxId:card.boxId,candidateId:card.candidateId},versions=CM.variants(base),view=CM.selectKit(base,sheetVersion),owned=ownedOriginal().some(c=>String(c.candidateId)===String(card.candidateId)),ownedId=ownedOriginal().find(c=>String(c.candidateId)===String(card.candidateId))?.boxId;
 const chosen=versions.find(v=>v.kind===sheetVersion);const medalContent=chosen?.medals?.length?'<section class="detail-section"><h3>Médailles nécessaires</h3><ul>'+chosen.medals.map(m=>'<li>'+esc(m.name)+' · '+esc(m.quantity)+'</li>').join('')+'</ul></section>':'';
 const zContent=versions.length?'<p class="muted">Choisis la version à consulter. Cela ne confirme pas que tu as réalisé cet éveil.</p><div class="card-version-buttons">'+[['base','Avant éveil Z'],...versions.map(v=>[v.kind,v.label])].map(([v,l])=>'<button data-card-version="'+v+'" aria-pressed="'+(sheetVersion===v)+'">'+l+'</button>').join('')+'</div><h3>'+esc(view._kitLabel)+'</h3>'+kit(view)+medalContent+(sheetVersion!=='base'?'<p class="muted">Kit contrôlé sur la version précise de l’éveil.</p>':'')+(owned?'<button data-card-use-kit="'+esc(sheetVersion)+'">Utiliser cette version pour mes équipes</button><p class="muted">À utiliser si cet éveil correspond à ta carte en jeu.</p>':'')+source(view):'<p>Aucun kit Z vérifié pour cette fiche.</p><p class="muted">Une mention d’éveil sans ses aptitudes contrôlées ne suffit pas à créer une version.</p>';
 const chain=familyFor(card.candidateId).filter(c=>CM.allowed(c));const chainContent=chain.length>1?'<section class="detail-section"><h3>Chaîne d’éveil</h3><div class="card-chain">'+chain.slice().reverse().map(c=>'<button data-catalog-open="'+esc(c.id)+'">'+image({...c,name:frCardName(c.name)})+'<small>'+esc(c.rarity)+' · '+esc(c.id)+'</small></button>').join('')+'</div></section>':'';
 document.querySelector('#sheet').innerHTML='<button class="close" onclick="closeSheet()">Fermer</button><div class="hero">'+image(base)+'<div><h2>'+esc(base.name)+'</h2><p>'+esc(base.title)+'</p><div class="card-badges"><span>'+esc(base.rarity)+'</span><span>'+esc(base.type)+'</span><span>'+esc(base.class||'')+'</span>'+versions.map(v=>'<span>'+v.label+'</span>').join('')+(rainbow100.has(String(base.candidateId))?'<span>🌈 Potentiel 100 %</span>':'')+'</div><p class="muted">ID '+esc(base.candidateId)+'</p><div class="detail-actions">'+(owned?'<button data-card-favorite="'+esc(ownedId)+'">'+(favorites.has(ownedId)?'★ Favori':'☆ Ajouter aux favoris')+'</button><button data-card-team="'+esc(ownedId)+'">'+(selectedTeam.includes(ownedId)?'Retirer de l’équipe':'Ajouter à l’équipe')+'</button><button data-card-rainbow="'+esc(ownedId)+'">'+(rainbow100.has(String(base.candidateId))?'🌈 Retirer le 100 %':'🌈 Marquer potentiel 100 %')+'</button>':'<button class="primary" data-card-own="'+esc(base.candidateId)+'">Je possède cette carte</button>')+'</div></div></div><div class="card-sheet-tabs" role="tablist"><button role="tab" data-card-tab="info" aria-selected="'+(sheetTab==='info')+'">Informations</button><button role="tab" data-card-tab="z" aria-selected="'+(sheetTab==='z')+'">Éveils Z · '+versions.length+'</button></div><div id="cardSheetContent" role="tabpanel">'+(sheetTab==='z'?zContent:((base.dataStatus?.kit==='verified'?'':'<p class="ai-warning">Certaines informations restent à compléter ou à contrôler.</p>')+'<p class="muted">Aptitudes avant éveil Z. Les autres versions sont dans Éveils Z.</p>'+kit(base)+tags('Catégories',base.categories)+tags('Liens',base.links)+tags('Transformations',(base.transformations||[]).map(x=>x.name||x.id))+chainContent+source(base)))+'</div>';
 document.querySelector('#sheet').classList.add('on');
}
document.addEventListener('input',e=>{if(e.target.id==='missingQuery'){missingQuery=e.target.value;page=0;renderMissing();const input=document.querySelector('#missingQuery');input?.focus();input?.setSelectionRange?.(missingQuery.length,missingQuery.length);}});
document.addEventListener('change',e=>{const k=e.target.dataset.catalogFilter;if(!Object.hasOwn(settings,k))return;settings[k]=e.target.value;page=0;storageWrite('dokkanos-catalogue-v4',JSON.stringify(settings));renderMissing();});
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const d=b.dataset;
 if(d.catalogScope){settings.scope=d.catalogScope;page=0;storageWrite('dokkanos-catalogue-v4',JSON.stringify(settings));renderMissing();}
 if(d.catalogPage!==undefined){page=Math.max(0,Number(d.catalogPage)||0);renderMissing();document.querySelector('#catalog main')?.scrollIntoView?.({block:'start'});}
 if(d.catalogReset!==undefined){settings={scope:'all',forms:'final',rarity:'',type:'',class:'',z:'',kit:'',sort:'recent'};missingQuery='';page=0;storageWrite('dokkanos-catalogue-v4',JSON.stringify(settings));renderMissing();}
 if(d.catalogOpen)openCard('CATALOG-'+d.catalogOpen);
 if(d.cardTab){sheetTab=d.cardTab;renderSheet();}
 if(d.cardVersion){sheetVersion=d.cardVersion;renderSheet();}
 if(d.cardOwn){setInventory(d.cardOwn,'owned');renderSheet();}
 if(d.cardFavorite){toggleFavorite(d.cardFavorite);renderSheet();}
 if(d.cardTeam){toggleTeam(d.cardTeam);renderSheet();}
 if(d.cardRainbow){toggleRainbowFromCard(d.cardRainbow,String(resolveOriginal(d.cardRainbow)?.candidateId));renderSheet();}
 if(d.cardUseKit){const id=String(resolveCard(sheetId)?.candidateId);selectedKits[id]=d.cardUseKit;storageWrite('dokkanos-kit-versions-v4',JSON.stringify(selectedKits));renderTeam();renderSheet();}
});
fetch('catalogue-report.json').then(r=>r.ok?r.json():null).then(r=>{if(r&&typeof r.status==='string')report=r;if(document.querySelector('#catalog')?.classList.contains('on'))renderMissing();}).catch(()=>{});
window.DokkanCatalogUI={currentCards,settings,get page(){return page},renderSheet};
})();
