/* Advice describes verified kits and composition; it never simulates a victory. */
(function(root){'use strict';
const text=x=>typeof x==='string'?x:Array.isArray(x)?x.map(text).join(' '):x?.description||'';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
function conditions(c,team,context,E){const p=E.passive(c,team,context);return p.effects.map(e=>{const n=norm(e.condition),tips=[];if(/avant.*attaque|1re|1er/.test(n))tips.push('Effet à surveiller avant sa première attaque ou en première position.');if(/lors.*attaque|chaque attaque portee|chaque att sp/.test(n))tips.push('Le bonus arrive en attaquant ; ne le compte pas avant cette attaque.');if(/encaisser|recu|recues/.test(n))tips.push('Le bonus dépend des coups reçus ; vérifie sa protection avant de le laisser encaisser.');if(/esquive|esquiver/.test(n))tips.push(context.disableDodge?'Cette condition peut être inaccessible : esquive désactivée pour cet objectif.':'Il faut réellement esquiver ; ce bonus n’est pas assuré au début du combat.');if(/ki|sph/.test(n))tips.push('Vérifie le ki ou les sphères obtenues avant de lancer le tour.');if(/tour|apparition/.test(n))tips.push('Compte les tours selon la condition exacte : tour du combat et tour depuis apparition peuvent différer.');if(/pv|hp/.test(n))tips.push('Vérifie les PV au moment prévu par le kit.');if(/allie|perso|categorie/.test(n))tips.push('La composition du tour peut différer de celle de toute l’équipe.');if(!tips.length&&e.state!=='active')tips.push('Vérifie la condition exacte en jeu avant de compter ce bonus.');return {...e,tips};});}
function equipment(c,team,context,E){const p=E.passive(c,team,context),sa=norm(text(c.superAttack)+' '+text(c.ultraSuperAttack)),base=norm(p.effects.filter(x=>x.state==='active').map(x=>x.text).join(' ')),all=norm(text(c.passive)),rows=[],blocked=context.disableDodge===true;
 const stacks=/augmente.*def|augmente.*att|raises/.test(sa),alwaysCrit=/coup critique garanti|critique garanti/.test(base);
 if(stacks)rows.push({key:'additional',label:'Attaque supplémentaire',priority:3,reason:'Ton attaque spéciale augmente des statistiques. Une ATT SP supplémentaire peut renouveler ce bonus ; sa durée reste celle du kit.'});
 if(alwaysCrit)rows.push({key:'critical',label:'Critique',priority:0,reason:'Un critique garanti apparaît dans les effets actifs détectés. Ajouter du critique n’apporte rien pendant cette garantie ; vérifie les autres phases.'});else rows.push({key:'critical',label:'Critique',priority:context.combat==='short'?3:2,reason:/critique/.test(all)?'Le kit possède déjà du critique conditionnel. Son intérêt dépend de la condition réellement atteinte.':'Option offensive si la carte ne dispose pas déjà du critique voulu en combat.'});
 if(!stacks)rows.push({key:'additional',label:'Attaque supplémentaire',priority:2,reason:'Option pour multiplier les attaques. Vérifie si le passif dépend du nombre d’attaques portées ou des ATT SP.'});
 rows.push({key:'dodge',label:'Esquive',priority:blocked?0:/apres.*esquiv|avoir esquive/.test(all)?3:/encaisser|attaques.*recues/.test(all)?1:2,reason:blocked?'À éviter pour cet objectif : l’esquive y est désactivée.':/encaisser|attaques.*recues/.test(all)?'Une esquive peut retarder un bonus qui demande d’encaisser. Choisis selon le rôle de la carte.':/apres.*esquiv|avoir esquive/.test(all)?'Des bonus du kit demandent une esquive réussie ; cette option peut aider, sans la garantir.':'Option de protection aléatoire ; ne remplace pas une défense suffisante.'});
 rows.push({key:'defense',label:'Équipement DÉF / PV',priority:context.combat==='short'?1:3,reason:'Piste de survie à comparer aux équipements disponibles. Aucun seuil de dégâts n’est calculé.'});return rows.sort((a,b)=>b.priority-a.priority);}
function guide(team,leader,friend,mission,context,E){const all=friend?[...team,friend]:team,e=E.evaluate(team,leader,friend,mission,context.known||[],context),rotations=e.rotations;const fixed=new Set(rotations.flatMap(r=>[E.instance?E.instance(r.a):r.a.boxId,E.instance?E.instance(r.b):r.b.boxId]));return {evaluation:e,rotations,floaters:all.filter(c=>!fixed.has(c.boxId)),cards:all.map(c=>({card:c,conditions:conditions(c,all,context,E),active:text(c.active),transformations:c.transformations||[]})),steps:[{turn:'Premières apparitions',action:'Repère les deux duos proposés. Réorganise-les progressivement selon l’ordre de départ et les attaques ennemies.'},{turn:'Tours de mise en place',action:'Garde les duos en positions 1 et 2 lorsque leur protection le permet. La troisième position fait circuler un personnage ; il revient trois tours plus tard.'},{turn:'Une fois les rotations établies',action:'Surveille les bonus temporaires, les attaques nécessaires et les PV. Consulte les conditions des actives et transformations avant de les utiliser.'}]};}
function explainDefeat(input,team,leader,friend,mission,context,E){const card=team.find(c=>E.identity(c)===String(input.card)),all=friend?[...team,friend]:team,p=card?E.passive(card,all,context):null,rows=[];if(!card)return [{title:'Choisis la carte touchée',detail:'L’analyse a besoin d’une carte de la composition actuelle.'}];const coverage=E.coverage(leader,card,context.known||[]);if(!coverage.covered)rows.push({title:'Vérifier le leader',detail:'Cette carte est hors couverture ou sa couverture est inconnue. Ajuste le leader ou remplace-la.'});if(+input.slot===1&&(/avant/.test(input.moment)||p.slot1<32))rows.push({title:'Tester une autre première position',detail:'La carte peut dépendre de bonus obtenus en attaquant. Consulte la rotation et essaie un partenaire protégé avant attaque.'});if(context.disableDodge)rows.push({title:'Ne pas compter sur l’esquive',detail:'L’objectif désactive l’esquive. Privilégie les protections compatibles et revois les équipements.'});if(input.cause==='super')rows.push({title:'Revoir la répartition des attaques',detail:'Une ATT SP ennemie peut dépasser les protections de cette carte. Si sa position est connue en jeu, envisage un autre placement ou une aptitude disponible.'});if(input.cause==='ki')rows.push({title:'Préparer les sphères',detail:'Consulte les seuils de ki et les liens du duo. Un soutien ou un changement de sphères de ta Box peut faciliter le départ.'});if(input.cause==='timer')rows.push({title:'Comparer une priorité dégâts',detail:'Teste la priorité Dégâts dans Équipes tout en conservant les quotas et une protection suffisante.'});for(const x of conditions(card,all,context,E).filter(x=>x.state==='missing').slice(0,2))rows.push({title:'Condition non remplie',detail:x.condition});if(+input.turn>6)rows.push({title:'Relire les durées des bonus',detail:'Un bonus temporaire peut avoir expiré. La durée dépend de la fiche et de la première apparition, pas seulement du tour saisi.'});rows.push({title:'Comparer un remplacement',detail:'Consulte les gains et pertes dans Équipes. Change un seul élément puis note le résultat dans ton carnet.'});return rows;}
function objectives(event,stage,missions,EM){return missions.map(m=>({id:m.id,title:m.description||m.title,mission:EM.combine(event,stage,[m.id])}));}
function cover(team,leader,friend,objective,known,E){return team.length===6&&team.every(c=>E.coverage(leader,c,known).covered)&&!!friend&&team.every(c=>E.coverage(friend,c,known).covered)&&E.constraints(team,objective.mission,friend).ok;}
function multiPlan({pool,leader,friend,context,known,objectives,current,locked=[],excluded=[]},E,progress=()=>{}){const targets=objectives.slice(0,12),uncovered=new Set(targets.map(m=>m.id)),candidates=[];const add=(team,lead,ami)=>{if(team.length!==6)return;const covers=targets.filter(m=>cover(team,lead,ami,m,known,E)).map(m=>m.id);if(covers.length&&!candidates.some(x=>x.team.map(E.identity).sort().join('|')===team.map(E.identity).sort().join('|')&&E.identity(x.leader)===E.identity(lead)))candidates.push({team,leader:lead,friend:ami,covers});};if(current?.length)add(current,leader,friend);if(targets.length&&candidates[0]?.covers.length===targets.length)return {groups:[candidates[0]],uncovered:[],approximate:false};let attempts=0;
 const jointRules=new Map();for(const r of targets.flatMap(x=>x.mission.requirements||[])){const k=JSON.stringify([r.kind,r.value,r.includeFriend,r.ids]),old=jointRules.get(k);if(!old||(r.count||1)>(old.count||1))jointRules.set(k,r);}const jointMission={requirements:[...jointRules.values()],manualCheck:targets.some(x=>x.mission.manualCheck),disableDodge:targets.some(x=>x.mission.disableDodge)};
 const joint=E.build(pool,leader,{friend,mission:jointMission,known,context,locked,excluded});if(!joint.error){add(joint.team,leader,friend);const one=candidates.find(c=>c.covers.length===targets.length);if(one)return {groups:[one],uncovered:[],approximate:true};}
 for(const o of targets){progress({attempt:++attempts,total:targets.length});const result=E.build(pool,leader,{friend,mission:o.mission,known,context:{...context,disableDodge:context.disableDodge||o.mission.disableDodge},locked,excluded});if(!result.error)add(result.team,leader,friend);}
 // Grow a feasible bundle of quotas. Keep each original objective for final independent checks.
 let bundle=[];for(const o of targets){if(bundle.length>=8)break;const unique=new Map();for(const r of [...bundle,o].flatMap(x=>x.mission.requirements||[])){const k=JSON.stringify([r.kind,r.value,r.includeFriend,r.ids]),old=unique.get(k);if(!old||(r.count||1)>(old.count||1))unique.set(k,r);}const mission={requirements:[...unique.values()],manualCheck:[...bundle,o].some(x=>x.mission.manualCheck)},result=E.build(pool,leader,{friend,mission,known,context,locked,excluded});if(!result.error&&[...bundle,o].every(x=>cover(result.team,leader,friend,x,known,E))){bundle.push(o);add(result.team,leader,friend);}}
 // Greedy coverage selection, not a claim of globally minimal teams.
 const groups=[];while(uncovered.size&&groups.length<6){let best=candidates.map(c=>({...c,gain:c.covers.filter(id=>uncovered.has(id)).length})).sort((a,b)=>b.gain-a.gain)[0];if(!best?.gain)break;const chosen=best.covers.filter(id=>uncovered.has(id));groups.push({...best,covers:chosen});chosen.forEach(id=>uncovered.delete(id));}return {groups,uncovered:[...uncovered],approximate:true};}
function missingCandidates(team,leader,friend,candidates,alternatives,mission,known,context,E){if(team.length!==6||!leader)return {missing:[],owned:[]};const base=E.evaluate(team,leader,friend,mission,known,{...context,quick:true});const rank=pool=>pool.filter(c=>!team.some(t=>E.identity(t)===E.identity(c))&&E.coverage(leader,E.combatCard(c,context),known).covered).map(c=>{c=E.combatCard(c,context);let best=null;for(let i=0;i<team.length;i++){if(E.identity(team[i])===E.identity(leader))continue;const proposed=team.map((t,j)=>j===i?c:t),e=E.evaluate(proposed,leader,friend,mission,known,{...context,quick:true});if(e.check.deficit>base.check.deficit||e.friendCover.filter(x=>!x.covered).length>base.friendCover.filter(x=>!x.covered).length)continue;if(!best||e.score>best.e.score)best={card:c,replaces:team[i],e,gain:e.score-base.score};}return best;}).filter(x=>x&&x.gain>1).sort((a,b)=>b.gain-a.gain).slice(0,5);return {missing:rank(candidates),owned:rank(alternatives),base};}
function share(snapshot,guide,name){return {format:'DokkanOS-team',version:1,name:String(name||'Mon équipe').slice(0,80),createdAt:new Date().toISOString(),cards:snapshot.cards.map(c=>({id:String(c.id),kit:c.kit||'base',projected:c.projected===true})),leader:snapshot.leader,friend:snapshot.friend,settings:{event:snapshot.event||'',eventStage:snapshot.settings.eventStage||'',eventMissions:snapshot.missions||[],friend:snapshot.settings.friend||'mirror',combat:snapshot.settings.combat,useZA:snapshot.settings.useZA!==false,disableDodge:snapshot.settings.disableDodge===true,category:snapshot.settings.category||'',count:snapshot.settings.count||6,types:snapshot.settings.types||0},rotations:guide.rotations.map(r=>({first:String(r.a.candidateId||r.a.id),second:String(r.b.candidateId||r.b.id),floater:r.third?String(r.third.candidateId||r.third.id):'',links:r.links})),objective:snapshot.objective||'Équipe libre'};}
function parseShare(raw){if(typeof raw!=='string'||raw.length>80000)throw Error('Code trop volumineux.');let x;try{x=JSON.parse(raw,(key,value)=>{if(['__proto__','constructor','prototype'].includes(key))throw Error();return value;});}catch(e){throw Error('Code d’équipe illisible.');}if(x?.format!=='DokkanOS-team'||x.version!==1||typeof x.name!=='string'||x.name.length>80||!Array.isArray(x.cards)||!x.cards.length||x.cards.length>6||x.cards.some(c=>!c||!/^\d+$/.test(c.id)||!['base','ztur','zlr','superZtur','superZlr'].includes(c.kit))||new Set(x.cards.map(c=>c.id)).size!==x.cards.length||!x.cards.some(c=>c.id===x.leader)||!x.settings||Array.isArray(x.settings)||typeof x.settings!=='object')throw Error('Ce code n’est pas une équipe DokkanOS compatible.');const s=x.settings;if(s.eventMissions&&!Array.isArray(s.eventMissions)||s.eventMissions?.some(id=>typeof id!=='string')||s.eventMissions?.length>12)throw Error('Missions du code invalides.');return x;}
function farmSteps(card,family,variants,version){const target=family[0]||card,steps=family.slice().reverse().map((c,i)=>({key:'form-'+c.id,label:(i?'Éveiller vers ':'Confirmer la forme ')+c.rarity+' · '+c.name,id:String(c.id),medals:[],source:c.source?.url||''}));const z=variants.find(v=>v.kind===version);if(z)steps.push({key:'z-'+z.kind,label:'Réaliser '+z.label,id:String(target.id),medals:(z.medals||[]).filter(m=>typeof m.name==='string'&&Number.isFinite(+m.quantity)&&+m.quantity>0).map(m=>({...m,quantity:+m.quantity})),source:z.source?.url||target.source?.url||''});return steps;}
function resourceBalance(rows){return rows.map(r=>({...r,remaining:r.have!==null&&r.have!==''&&Number.isFinite(+r.need)&&Number.isFinite(+r.have)?Math.max(0,+r.need-+r.have):null}));}
const API={text,norm,conditions,equipment,guide,explainDefeat,objectives,cover,multiPlan,missingCandidates,share,parseShare,farmSteps,resourceBalance};if(typeof module!=='undefined')module.exports=API;root.DokkanCopilotModel=API;
})(typeof window!=='undefined'?window:globalThis);
