/* Event progress is local and explicitly confirmed; composition never completes a mission. */
(function(root){'use strict';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
function status(e,now=Date.now()){const start=Date.parse(e.start),end=Date.parse(e.end);if(Number.isFinite(start)&&now<start)return'upcoming';if(Number.isFinite(end)&&now>=end)return'closed';if(e.permanent)return'permanent';return ['active','closed','upcoming'].includes(e.status)?e.status:'unknown';}
function done(m,progress){return progress[m.id]?.done===true;}
function rewards(m){return(m.rewards||[]).filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.amount)&&r.amount>0);}
function progress(e,state){const missions=e.missions||[],completed=missions.filter(m=>done(m,state)).length,claimed=missions.filter(m=>state[m.id]?.claimed===true).length;return {total:missions.length,completed,claimed,percent:missions.length?Math.round(100*completed/missions.length):0};}
function stones(e,state,onlyRemaining=true){return(e.missions||[]).filter(m=>!onlyRemaining||state[m.id]?.claimed!==true&&(!m.end||Date.parse(m.end)>Date.now())&&(!m.start||Date.parse(m.start)<=Date.now())).flatMap(rewards).filter(r=>r.kind==='stones').reduce((s,r)=>s+r.amount,0);}
function filter(events,settings,state,now=Date.now()){const query=norm(settings.query);return events.filter(e=>!e.hidden&&(!query||norm([e.name,e.kind,...(e.missions||[]).map(m=>m.title)].join(' ')).includes(query))&&(!settings.kind||e.kind===settings.kind)&&(!settings.status||settings.status==='all'||(settings.status==='available'?['active','permanent'].includes(status(e,now)):status(e,now)===settings.status))&&(!settings.todo||(e.missions||[]).some(m=>!done(m,state)))&&(!settings.favorite||settings.favorites.includes(e.id))).sort((a,b)=>settings.sort==='stones'?stones(b,state)-stones(a,state):settings.sort==='name'?a.name.localeCompare(b.name,'fr'):(Date.parse(a.end)||Infinity)-(Date.parse(b.end)||Infinity)||a.name.localeCompare(b.name,'fr'));}
function combine(event,stageId,missionIds){const stage=(event?.stages||[]).find(s=>String(s.id)===String(stageId)),missions=(event?.missions||[]).filter(m=>missionIds.includes(m.id)),requirements=[...(stage?.requirements||[]),...missions.flatMap(m=>m.requirements||[])];const unique=new Map();for(const r of requirements){const key=JSON.stringify([r.kind,r.value,r.ids,r.includeFriend]);const old=unique.get(key);if(!old||r.count>old.count)unique.set(key,{...r});}return {requirements:[...unique.values()],stage,missions,manualCheck:!!stage?.manualCheck||missions.some(m=>m.manualCheck),title:missions.map(m=>m.title).join(' + ')||stage?.name||event?.name||'',notes:[...(stage?.notes||[]),...missions.map(m=>m.notes).filter(Boolean)].join('\n'),disableDodge:!!stage?.disableDodge};}
const API={norm,status,done,rewards,progress,stones,filter,combine};if(typeof module!=='undefined')module.exports=API;root.DokkanEventModel=API;
})(typeof window!=='undefined'?window:globalThis);
