/* Shared mobile workflows. Existing game data and action handlers stay authoritative. */
(function(){'use strict';
const KEY='dokkanos-ui-v1',clone=x=>JSON.parse(JSON.stringify(x)),esc=teamEsc;
let prefs=storedJSON(KEY,{});if(!record(prefs))prefs={};let replaying=false,history=[],positions={},sheetOrigin=null,undo=null,transaction=null,scheduled=false;
const labels={home:'Aujourd’hui',box:'Ma Box',catalog:'Catalogue',teams:'Équipes',events:'Événements',duplicates:'Potentiel',inventory:'Inventaire',verify:'À vérifier',analysis:'Analyse',copilot:'Copilote',tools:'Mes outils'};
const save=()=>storageWrite(KEY,JSON.stringify(prefs));
function navState(view){return {view,scroll:window.scrollY||0,tool:view==='copilot'?storedJSON('dokkanos-copilot-v1',{}).tool:view==='tools'?storedJSON('dokkanos-companion-v1',{}).tool:'',event:view==='events'?clone(eventSettings):null};}
function node(html){const d=document.createElement('div');d.innerHTML=html;return d.firstElementChild;}
function buttons(items,attr,current){return items.map(([id,label])=>'<button '+attr+'="'+id+'" aria-pressed="'+(id===current)+'">'+label+'</button>').join('');}
function notify(message,canUndo=false){let t=document.getElementById('uxToast');if(!t){t=node('<div id="uxToast" class="ux-toast" role="status" aria-live="polite"></div>');document.body.append(t);}t.innerHTML='<span>'+esc(message)+'</span>'+(canUndo?'<button data-ux-undo>Annuler</button>':'')+'<button data-ux-toast-close aria-label="Fermer le message">×</button>';t.hidden=false;}
function detail(panel,key){if(!panel||panel.dataset.uxFold)return;panel.dataset.uxFold=key;const heading=panel.querySelector('h2,h3');if(!heading)return;const d=node('<details class="ux-secondary" data-ux-detail="'+key+'"><summary>'+esc(heading.textContent)+'</summary></details>');d.open=prefs.details?.[key]===true;heading.remove();while(panel.firstChild)d.append(panel.firstChild);panel.append(d);}
function secondary(buttonsNode){if(!buttonsNode||buttonsNode.dataset.uxGrouped)return;buttonsNode.dataset.uxGrouped='yes';const candidates=[...buttonsNode.querySelectorAll(':scope > button')].filter(b=>!b.classList.contains('primary')&&b.dataset.teamAction!=='save'&&b.dataset.teamLoad===undefined&&b.dataset.battleReview===undefined&&b.id!=='autoTeam'&&b.dataset.teamAction!=='cancel');if(candidates.length<4)return;const more=node('<details class="ux-more-actions"><summary aria-label="Autres actions">⋯</summary></details>');candidates.slice(2).forEach(b=>more.append(b));buttonsNode.append(more);}
function home(){const host=document.querySelector('#home main');if(!host||host.querySelector('.ux-resume'))return;const saved=teamSaved(),current=saved.find(s=>s.id===teamSettings.savedSource),last=current||saved.at(-1),e=teamEvents.events.find(e=>e.id===teamSettings.event),cards=teamCards();host.prepend(node('<section class="panel ux-resume"><span class="eyebrow">REPRENDRE MON AVENTURE</span><h2>'+esc(e?.name||'Mon prochain combat')+'</h2><p>'+esc(teamMission().title||'Choisis un événement et prépare ton équipe.')+'</p><div class="ux-mini-roster">'+cards.map(c=>'<button data-team-open="'+esc(c.boxId)+'" aria-label="Voir '+esc(c.name)+'">'+teamImage(c)+'</button>').join('')+'</div><div class="companion-actions"><button class="primary" data-open-view="teams">Reprendre '+(cards.length?'mon équipe':'ma préparation')+'</button>'+(e?'<button data-ux-current-event>Voir mon objectif</button>':'<button data-open-view="events">Choisir un événement</button>')+'</div>'+(last?'<p>Dernière composition : <b>'+esc(last.name)+'</b></p><button data-battle-review="'+esc(last.id)+'">Recharger cette composition</button>':'')+'</section>'));host.querySelectorAll('.companion-columns > .panel').forEach((p,i)=>{if(i>0)detail(p,'home-'+i)});}
function box(){const host=document.querySelector('#box');if(!host.querySelector('.ux-search-dock')){const d=node('<div class="ux-search-dock"><label for="uxBoxSearch">Rechercher dans ma Box</label><input id="uxBoxSearch" type="search" placeholder="Nom, catégorie, lien ou ID…"><button data-ux-scroll="boxTools">Filtres</button></div>');host.querySelector('.box-tools').id='boxTools';host.querySelector('.collection-heading').after(d);}if(host.querySelector('#uxBoxSearch').value!==query)host.querySelector('#uxBoxSearch').value=query;const chips=document.getElementById('activeFilters');if(chips){const specs=[['query',query],['filter',filter==='all'?'':filter],['rarityFilter',rarityFilter],['typeFilter',typeFilter],['classFilter',classFilter],['categoryFilter',categoryFilter],['linkFilter',linkFilter],['ezaFilter',ezaFilter],['favoriteOnly',favoriteOnly?'Favoris':'']];const html=specs.filter(([,v])=>v).map(([k,v])=>'<button data-ux-box-clear="'+k+'">'+esc(({all:'Toutes',valid:'Validées',check:'À vérifier',yes:'Avec éveil Z',no:'Sans éveil Z'})[v]||v)+' ×</button>').join('');const signature=JSON.stringify(specs);if(chips.dataset.uxSignature!==signature){chips.dataset.uxSignature=signature;chips.innerHTML=html;}}}
function teams(){const host=document.querySelector('#teams main');if(!host||host.querySelector('.ux-team-roster'))return;const mini=node('<div class="ux-team-roster" aria-label="Composition actuelle">'+teamCards().map((c,i)=>'<button data-team-open="'+esc(c.boxId)+'" title="'+esc(c.name)+'">'+teamImage(c)+'<small>'+(i===0?'Leader':i+1)+'</small></button>').join('')+(selectedTeam.length?'<button data-ux-scroll="teamComposition">'+selectedTeam.length+'/6 · Ajuster</button>':'<span>Choisis ton objectif et ton leader</span>')+'</div>');host.querySelector('.ux-team-steps')?.after(mini);const saved=document.getElementById('teamSaved');if(saved){const filters=node('<div class="ux-saved-filters"><label>Rechercher une équipe ou un événement<input id="uxSavedQuery" type="search" value="'+esc(prefs.savedQuery||'')+'" placeholder="Nom, événement ou mission…"></label><div class="ux-segments">'+buttons([['all','Toutes'],['untested','À tester'],['works','Fonctionnent'],['review','À revoir']],'data-ux-saved-filter',prefs.savedFilter||'all')+'</div><p id="uxSavedEmpty" hidden>Aucune équipe pour ces critères. Change le filtre ou sauvegarde une nouvelle composition.</p></div>');saved.querySelector('.team-toolbar').after(filters);filterSaved();}host.querySelectorAll('.team-toolbar,.companion-team-tools .companion-actions').forEach(secondary);}
function filterSaved(){const list=teamSaved(),q=norm(prefs.savedQuery||''),filter=prefs.savedFilter||'all';let count=0;document.querySelectorAll('.battle-saved').forEach((p,i)=>{const s=list[i];if(!s)return;const status=window.DokkanBattleModel.summary(window.DokkanBattles.rows(),s).status;p.hidden=!(norm([s.name,s.objective?.eventName,s.objective?.stageName,...(s.objective?.missions||[]).map(m=>m.title)].join(' ')).includes(q)&&(filter==='all'||status===filter));if(!p.hidden)count++});const empty=document.getElementById('uxSavedEmpty');if(empty)empty.hidden=count>0||!list.length;}
function eventTabs(){const root=document.getElementById('eventDetail');if(!root||root.querySelector('.ux-event-tabs'))return;const groups={levels:node('<section data-ux-event-panel="levels"></section>'),missions:node('<section data-ux-event-panel="missions"></section>'),rewards:node('<section data-ux-event-panel="rewards"><h4>Récompenses de ce combat</h4></section>'),teams:node('<section data-ux-event-panel="teams"><h4>Mes équipes pour ce combat</h4></section>')};const stage=root.querySelector('[data-event-setting="stage"]')?.closest('label');if(stage)groups.levels.append(stage);root.querySelectorAll('.event-combat,.event-team-action').forEach(n=>groups.levels.append(n));const grid=root.querySelector('.event-missions');if(grid){let n=grid.previousElementSibling;if(n?.tagName==='P')groups.missions.append(n);n=grid.previousElementSibling;if(n?.tagName==='H4')groups.missions.prepend(n);groups.missions.append(grid);}root.querySelectorAll('.event-pagination').forEach(n=>groups.missions.append(n));root.querySelectorAll('.event-rewards').forEach(n=>groups.rewards.append(n));const e=teamEvents.events.find(e=>e.id===eventSettings.selected),s=e?.stages?.find(s=>String(s.id)===eventSettings.stage);if(s?.rewards?.length)groups.rewards.append(node('<p>'+esc(eventRewardText(s))+'</p>'));const saved=root.parentElement.querySelector('.battle-event-teams');if(saved)groups.teams.append(saved);else groups.teams.append(node('<p>Aucune équipe sauvegardée pour cette sélection. Prépare une équipe depuis Niveaux, puis sauvegarde-la dans Équipes.</p>'));const tabs=node('<nav class="ux-event-tabs ux-segments" aria-label="Sections du combat">'+buttons([['all','Vue d’ensemble'],['levels','Niveaux'],['missions','Missions'],['rewards','Récompenses'],['teams','Mes équipes']],'data-ux-event-tab',prefs.eventTab||'all')+'</nav>');root.querySelector('.event-detail-heading')?.after(tabs);Object.values(groups).forEach(p=>root.append(p));applyEventTab(prefs.eventTab||'all');}
function applyEventTab(tab){document.querySelectorAll('[data-ux-event-panel]').forEach(p=>p.hidden=tab!=='all'&&p.dataset.uxEventPanel!==tab);document.querySelectorAll('[data-ux-event-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.uxEventTab===tab)));}
function events(){const host=document.querySelector('#events main');if(!host||host.querySelector('.ux-event-shortcuts'))return;const saved=teamSaved(),ids=[...new Set([teamSettings.event,...saved.map(s=>s.settings.event),...eventSettings.favorites])].filter(Boolean);const e=ids.map(id=>teamEvents.events.find(e=>e.id===id)).filter(Boolean).slice(0,6);host.querySelector('.event-heading')?.after(node('<section class="ux-event-shortcuts"><h3>Mes combats et favoris</h3><div class="ux-segments">'+e.map(e=>'<button data-event-open="'+esc(e.id)+'">'+esc(e.name)+'</button>').join('')+'</div>'+(e.length?'':'<p>Ajoute un événement aux favoris ou prépare une équipe pour le retrouver ici.</p>')+'</section>'));eventTabs();}
function potential(){const host=document.querySelector('#duplicates main');if(!host||host.querySelector('.ux-potential-filters'))return;host.prepend(node('<div class="ux-potential-filters"><label>Rechercher une carte<input id="uxPotentialQuery" type="search" value="'+esc(uxPotentialQuery)+'"></label><div class="ux-segments">'+buttons([['all','Toutes'],['complete','Cartes à compléter'],['rainbow','Potentiel 100 %']],'data-ux-potential-filter',uxPotentialFilter)+'</div><p class="muted">Les 0 à 4 doublons renseignés aident à suivre le potentiel ; les voies ouvertes restent à confirmer en jeu.</p></div>'));}
function analysis(){const host=document.getElementById('analysisContent');if(!host||host.querySelector('.ux-findings'))return;const pool=ownedTeamCards(),review=DB.cards.filter(c=>!c.validated).length,lr=pool.filter(c=>c.rarity==='LR').length;host.prepend(node('<div class="ux-findings"><button data-open-view="verify"><b>'+review+'</b><span>positions à vérifier →</span></button><button data-ux-analysis="owned"><b>'+pool.length+'</b><span>cartes confirmées →</span></button><button data-ux-analysis="lr"><b>'+lr+'</b><span>LR dans ma Box →</span></button></div>'));const kpis=host.querySelector('.collection-kpis');if(kpis){const fold=node('<details class="ux-secondary panel" data-ux-detail="collection-kpis"><summary>Vue complète de la collection</summary></details>');fold.open=prefs.details?.['collection-kpis']===true;kpis.before(fold);fold.append(kpis);}[...host.querySelectorAll(':scope > .panel')].forEach((p,i)=>detail(p,'analysis-'+i));host.querySelectorAll('.analysis-grid .panel').forEach((p,i)=>{const heading=p.querySelector('h3');if(heading)detail(p,'stats-'+i)});}
function tools(){const host=document.querySelector('#tools main');if(!host||host.querySelector('.ux-tools-groups'))return;const comp=storedJSON('dokkanos-companion-v1',{});host.querySelector('.section-title')?.after(node('<nav class="ux-tools-groups ux-segments" aria-label="Rubriques des outils"><button data-c-tool="plan">Progression</button><button data-c-tool="journal">Carnet</button><button data-c-tool="backup">Sauvegarde et restauration</button><button data-pilot="performance">Stockage et réglages</button><button data-c-tool="freshness">Données</button></nav><p class="ux-last-backup">Dernière sauvegarde préparée : '+esc(comp.lastExport?new Date(comp.lastExport).toLocaleString('fr-FR'):'aucune · prépare un export pour conserver tes données')+'</p>'));}
function inventoryView(){const host=document.querySelector('#inventory main');if(!host||host.querySelector('.ux-inventory-help'))return;host.querySelector('.section-title')?.after(node('<div class="ux-inventory-help"><button class="primary" data-open-view="verify">Comparer mes captures</button><button data-pilot="capture">Ajouter une capture</button><p>Confirme une carte, indique qu’elle manque ou garde-la à vérifier. Les choix sont enregistrés immédiatement.</p></div>'));}
function verification(){const root=document.getElementById('verifyList');if(!root)return;const confirm=document.getElementById('verifyConfirm');if(confirm)confirm.textContent='Confirmer cette carte';const skip=document.getElementById('verifySkip');if(skip)skip.textContent='Ignorer pour le moment';const status=document.getElementById('verificationStatus');if(status&&!status.hidden&&!status.querySelector('[data-ux-next-verify]')&&verifyPending().length)status.append(node('<button data-ux-next-verify>Vérifier la carte suivante →</button>'));}
function sheet(){const root=document.getElementById('sheet');if(!root?.classList.contains('on'))return;const kit=root.querySelectorAll('#cardSheetContent > .detail-section');kit.forEach((p,i)=>{if(root.querySelector('[data-card-tab="info"][aria-selected="true"]')&&i>0&&!p.querySelector('h3')?.textContent.startsWith('Passif'))detail(p,'sheet-section-'+i)});secondary(root.querySelector('.detail-actions'));}
function enhance(){const view=document.body.dataset.view;({home,box,teams,events,duplicates:potential,analysis,tools,inventory:inventoryView,verify:verification})[view]?.();sheet();const source=document.getElementById('autoTeam');let cta=document.getElementById('uxTeamCTA');if(view==='teams'&&source){if(!cta){cta=node('<div id="uxTeamCTA" class="ux-team-cta"><button class="primary" data-ux-generate>Créer l’équipe automatiquement</button><button data-ux-scroll="teamSaved">Sauvegarder / résultats</button></div>');document.body.append(cta);}cta.hidden=false;cta.querySelector('[data-ux-generate]').disabled=source.disabled;}else if(cta)cta.hidden=true;document.querySelectorAll('.view.on img:not([loading])').forEach(img=>{img.loading='lazy';img.decoding='async'});const nav=document.getElementById('uxBack');if(nav){nav.hidden=!history.length;nav.textContent=history.length?'‹ '+(labels[history.at(-1)?.view]||'Retour'):'';}}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()});}
const originalSwitch=switchView;switchView=function(view){const old=document.body.dataset.view;if(!replaying&&view!==old&&document.getElementById(view)?.classList.contains('view')){positions[old]=window.scrollY||0;history.push(navState(old));history=history.slice(-30);}const result=originalSwitch(view);enhance();return result;};
const originalOpen=openCard;openCard=function(id){if(!document.getElementById('sheet').classList.contains('on'))sheetOrigin={view:document.body.dataset.view,scroll:window.scrollY||0,focus:document.activeElement};const r=originalOpen(id);sheet();return r;};
const originalClose=closeSheet;closeSheet=function(){originalClose();if(sheetOrigin?.view===document.body.dataset.view){window.scrollTo({top:sheetOrigin.scroll,behavior:'auto'});sheetOrigin.focus?.focus?.({preventScroll:true});}sheetOrigin=null;};
const header=document.querySelector('.header-context');if(header)header.append(node('<button id="uxBack" class="ux-back" hidden>‹ Retour</button>'));
// Snapshot only direct reversible user actions, never background synchronization.
function begin(target){if(transaction)return;const btn=target.closest?.('button,input,form');if(!btn)return;const reversible=btn.matches('#verifyConfirm,[data-card-own],[data-card-favorite],[data-card-rainbow],[data-team-action="save"],[data-team-delete],[data-battle-attempt-delete],[data-event-done],[data-event-claimed],[data-team-completed]')||/setInventory|changePotentialDuplicate|toggleRainbow100/.test(btn.getAttribute('onclick')||'')||btn.dataset.battleForm;if(!reversible)return;transaction={before:{},runtime:{inventory:clone(inventory),favorites:[...favorites],rainbow:[...rainbow100],potential:clone(potentialManual),selected:[...selectedTeam],leader:teamLeader,settings:clone(teamSettings),eventProgress:clone(eventProgress),draft:clone(verifyDraft),cards:btn.id==='verifyConfirm'?clone(DB.cards):null}};setTimeout(()=>{const t=transaction;transaction=null;if(!t||!Object.keys(t.before).length)return;t.after=Object.fromEntries(Object.keys(t.before).map(k=>[k,storageRead(k)]));undo=t;notify(btn.dataset.battleForm?'Résultat et essais enregistrés.':btn.id==='verifyConfirm'?'Carte confirmée.':btn.dataset.teamAction==='save'?'Équipe sauvegardée.':'Modification enregistrée.',true);});}
const write=storageWrite;storageWrite=function(key,value){const previous=storageRead(key),ok=write(key,value);if(ok&&transaction&&key!==KEY&&key.startsWith('dokkanos-')&&!(key in transaction.before))transaction.before[key]=previous;return ok;};
document.addEventListener('click',e=>{const b=e.target.closest?.('button'),view=document.body.dataset.view;if(!replaying&&b&&(view==='copilot'&&b.dataset.pilot||view==='tools'&&b.dataset.cTool||view==='events'&&b.dataset.eventOpen)){history.push(navState(view));history=history.slice(-30);}begin(e.target);},true);document.addEventListener('change',e=>begin(e.target),true);document.addEventListener('submit',e=>begin(e.target),true);
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const d=b.dataset;
 if(b.id==='uxBack'){const prior=history.pop();if(prior){replaying=true;if(prior.event){Object.assign(eventSettings,prior.event);eventSave();}originalSwitch(prior.view);if(prior.tool&&prior.view==='copilot')window.DokkanCopilot.open(prior.tool);if(prior.tool&&prior.view==='tools')document.querySelector('[data-c-tool="'+prior.tool+'"]')?.click();replaying=false;enhance();window.scrollTo({top:prior.scroll||0,behavior:'auto'});}return;}
 if(d.uxUndo!==undefined&&undo){const t=undo;undo=null;if(Object.entries(t.after).some(([k,v])=>storageRead(k)!==v)){notify('D’autres modifications ont été faites depuis. Cette annulation n’est plus disponible.');return;}for(const [key,value] of Object.entries(t.before)){if(value===null){try{localStorage.removeItem(key)}catch(e){}}else write(key,value);}const r=t.runtime;const keys=Object.keys(t.before);if(keys.includes('dokkanos-inventory'))inventory=r.inventory;if(keys.includes('dokkanos-favorites'))favorites=new Set(r.favorites);if(keys.includes('dokkanos-rainbow100'))rainbow100=new Set(r.rainbow);if(keys.includes('dokkanos-potential-manual'))potentialManual=r.potential;if(keys.includes('dokkanos-team'))selectedTeam=r.selected;if(keys.includes('dokkanos-team-leader'))teamLeader=r.leader;if(keys.includes('dokkanos-team-settings-v2'))teamSettings=r.settings;if(keys.some(k=>k==='dokkanos-events-progress-v1'||k.startsWith('dokkanos-mission-done-')))eventProgress=r.eventProgress;if(r.cards){DB.cards=r.cards;verifyDraft=r.draft;}render();renderTeam();renderDuplicates();renderInventory();renderEvents();if(document.getElementById('sheet').classList.contains('on'))window.DokkanCatalogUI.renderSheet();enhance();notify('Modification annulée.');return;}
 if(d.uxToastClose!==undefined)document.getElementById('uxToast').hidden=true;
 if(d.uxGenerate!==undefined)document.getElementById('autoTeam')?.click();if(d.uxScroll){const target=document.getElementById(d.uxScroll);if(target?.tagName==='DETAILS')target.open=true;target?.scrollIntoView({behavior:'smooth',block:'start'});}
 if(d.uxCurrentEvent!==undefined){eventSettings.selected=teamSettings.event;eventSettings.stage=teamSettings.eventStage;eventSettings.missions=[...teamSettings.eventMissions];eventSave();switchView('events');document.getElementById('eventDetail')?.scrollIntoView({block:'start'});}
 if(d.uxSavedFilter){prefs.savedFilter=d.uxSavedFilter;save();document.querySelectorAll('[data-ux-saved-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filterSaved();}
 if(d.uxEventTab){prefs.eventTab=d.uxEventTab;save();applyEventTab(d.uxEventTab);}
 if(d.uxPotentialFilter){uxPotentialFilter=d.uxPotentialFilter;uxPotentialLimit=80;renderDuplicates();document.querySelectorAll('[data-ux-potential-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}
 if(b.id==='uxInventoryMore'){uxInventoryLimit+=80;renderInventory();}if(b.id==='uxManualMore'){uxManualLimit+=80;renderManualOwned();}if(b.id==='uxPotentialMore'){uxPotentialLimit+=80;renderDuplicates();}
 if(d.uxNextVerify!==undefined){const next=verifyPending()[0];if(next)verifySelectPosition(String(next.boxId));}
 if(d.uxAnalysis){rarityFilter=d.uxAnalysis==='lr'?'LR':'';filter='valid';$('#rarityFilter').value=rarityFilter;switchView('box');}
 if(d.uxBoxClear){const key=d.uxBoxClear;if(key==='query'){query='';$('#search').value='';}if(key==='filter')filter='all';if(key==='rarityFilter')rarityFilter='';if(key==='typeFilter')typeFilter='';if(key==='classFilter')classFilter='';if(key==='categoryFilter')categoryFilter='';if(key==='linkFilter')linkFilter='';if(key==='ezaFilter')ezaFilter='';if(key==='favoriteOnly')favoriteOnly=false;const input=document.getElementById(key);if(input&&input.tagName==='SELECT')input.value='';render();box();}
});
document.addEventListener('input',e=>{if(e.target.id==='uxBoxSearch'){const input=document.getElementById('search');input.value=e.target.value;input.dispatchEvent(new Event('input',{bubbles:true}));box();}if(e.target.id==='uxSavedQuery'){prefs.savedQuery=e.target.value;filterSaved();}if(e.target.id==='uxPotentialQuery'){uxPotentialQuery=e.target.value;uxPotentialLimit=80;renderDuplicates();}});
document.addEventListener('change',e=>{if(e.target.id==='uxSavedQuery')save();});
document.addEventListener('toggle',e=>{const key=e.target.dataset?.uxDetail;if(key){prefs.details=prefs.details||{};prefs.details[key]=e.target.open;save();}},true);
window.addEventListener('dokkanos-view-change',enhance);window.addEventListener('dokkanos-sheet-render',sheet);window.addEventListener('dokkanos-state-change',schedule);
const observer=new MutationObserver(m=>{if(m.some(x=>!x.target.closest?.('#uxToast')))schedule()});document.querySelectorAll('.view,#sheet').forEach(root=>observer.observe(root,{childList:true,subtree:true}));
window.DokkanExperience={enhance,notify,get prefs(){return prefs},back(){document.getElementById('uxBack').click()}};enhance();
})();
