/* Survival groups have one leader each, individual HP and a manual battle ledger. */
(function(root){'use strict';
const key='dokkanos-frontier-v1',id=c=>String(c.candidateId||c.id),copy=x=>JSON.parse(JSON.stringify(x)),record=x=>x&&typeof x==='object'&&!Array.isArray(x),ids=a=>Array.isArray(a)&&a.every(x=>typeof x==='string'&&/^\d{1,20}$/.test(x))&&new Set(a).size===a.length;
const empty=()=>({cards:[],locked:[],mission:false,board:null,completed:false,missionDone:false,history:[]});
const initial=cards=>({turn:1,active:'A',heat:{A:0,B:0},gauge:0,hp:Object.fromEntries(cards.map(i=>[i,100])),lost:[]});
function validateBoard(b,cards){if(!record(b)||!Number.isInteger(b.turn)||b.turn<1||b.turn>999||!['A','B'].includes(b.active)||!record(b.heat)||['A','B'].some(g=>!Number.isInteger(b.heat[g])||b.heat[g]<0||b.heat[g]>99)||!Number.isInteger(b.gauge)||b.gauge<0||b.gauge>99||!record(b.hp)||Object.keys(b.hp).length!==cards.length||cards.some(i=>!Object.hasOwn(b.hp,i)||!Number.isFinite(b.hp[i])||b.hp[i]<0||b.hp[i]>100)||!ids(b.lost)||b.lost.some(i=>!cards.includes(i)))throw Error('Suivi de survie invalide.');return b;}
function validateSession(s){if(!record(s)||!ids(s.cards)||![0,6].includes(s.cards.length)||!Array.isArray(s.locked)||new Set(s.locked).size!==s.locked.length||s.locked.some(i=>!Number.isInteger(i)||i<0||i>5||!s.cards[i])||typeof s.mission!=='boolean'||typeof s.completed!=='boolean'||typeof s.missionDone!=='boolean'||!Array.isArray(s.history)||s.history.length>30||s.missionDone&&!s.completed)throw Error('Session Frontier invalide.');if(s.board)validateBoard(s.board,s.cards);for(const b of s.history)validateBoard(b,s.cards);return s;}
function validate(x){if(!record(x)||x.version!==1||typeof x.active!=='string'||!/^[a-z0-9-]{1,80}$/.test(x.active)||!record(x.sessions)||Object.keys(x.sessions).length>100||Object.keys(x.sessions).some(k=>!/^[a-z0-9-]{1,80}$/.test(k)))throw Error('Sauvegarde Frontier invalide.');Object.values(x.sessions).forEach(validateSession);return x;}
const category=(E,c,v)=>{const aliases={cyborg:['Cyborg','Cyborge','Androids'],'destructeurs de planetes':['Destructeurs de planètes','Destruction planétaire','Planetary Destruction']};return (aliases[E.norm(v)]||[v]).some(a=>E.inCategory(c,a));};
const counter={AGI:'TEC',TEC:'INT',INT:'END',PUI:'AGI',END:'PUI'};
function context(node,phase){const phases=phase===undefined?node.phases:[node.phases[phase]||node.phases[0]];return {combat:'survival',useZA:false,quick:true,disableDodge:phases.some(p=>p.disableDodge),boss:{available:false,pressure:true,bossTypes:phases.flatMap(p=>p.enemies.map(b=>b.type)),growth:true,immuneStun:true,immuneSeal:true,immuneAtk:phases.some(p=>p.atkImmune),immuneDef:phases.some(p=>p.defImmune)}};}
function quota(E,cards,node,mission){return !mission||!node.mission.category||cards.filter(c=>category(E,c,node.mission.category)).length>=node.mission.count;}
function group(E,cards,node,known,team=cards){if(cards.length!==3)return {valid:false,score:-Infinity};const ctx=context(node),cover=cards.map(c=>E.coverage(cards[0],c,known));if(cover.some(c=>!c.covered))return {valid:false,score:-Infinity};const profiles=cards.map(c=>E.passive(c,team,ctx));let score=cover.reduce((n,c)=>n+(c.hp+c.atk+c.def)/9,0)+profiles.reduce((n,p)=>n+p.defense*1.7+p.offense*(node.offensive?1.8:1)+p.utility,0);score+=Math.min(...profiles.map(p=>p.defense))*1.4;score-=profiles.some(p=>p.slot1>=32)?0:55;
for(let i=0;i<3;i++){const good=node.phases.flatMap(p=>p.enemies).filter(b=>counter[b.type]===cards[i].type).length,bad=node.phases.flatMap(p=>p.enemies).filter(b=>counter[cards[i].type]===b.type).length;score+=(good-bad)*12/node.phases.length;if(node.avoidType===cards[i].type)score-=35;for(let j=i+1;j<3;j++)score+=E.links(cards[i],cards[j]).length*5;}
if(!Number.isFinite(score))throw Error('Score Frontier invalide.');return {valid:true,score,cover,profiles};}
function assess(E,cards,node,known,mission=false){if(cards.length!==6||cards.some(c=>!c)||new Set(cards.map(id)).size!==6||node.category&&cards.some(c=>!category(E,c,node.category))||!quota(E,cards,node,mission))return {valid:false,score:-Infinity};node={...node,offensive:mission&&['turns','damage'].includes(node.mission.kind)};const A=group(E,cards.slice(0,3),node,known,cards),B=group(E,cards.slice(3),node,known,cards);return {valid:A.valid&&B.valid,score:A.score+B.score+Math.min(A.score,B.score)*.35,groups:[A,B]};}
async function compose(E,pool,node,known,session=empty(),progress=()=>{},cancel=()=>false){validateSession(session);node={...node,offensive:session.mission&&['turns','damage'].includes(node.mission.kind)};const cards=[...new Map(pool.filter(c=>!node.category||category(E,c,node.category)).map(c=>[id(c),c])).values()];if(cards.length<6)return null;const fixed=session.locked.map(i=>session.cards[i]);if(fixed.some(i=>!cards.some(c=>id(c)===i)))throw Error('Une carte verrouillée n’est plus disponible dans ta Box.');const ctx=context(node),ranks=new Map(cards.map(c=>{const p=E.passive(c,cards,ctx);return [id(c),p.defense*1.7+p.offense*(node.offensive?1.8:1)+p.utility];})),lists=[[],[]];
for(let g=0;g<2;g++)for(const lead of cards.filter(c=>c.leader&&E.coverage(c,c,known).covered)){
if(cancel())throw Error('Recherche annulée.');if(session.locked.includes(g*3)&&id(lead)!==session.cards[g*3])continue;
const allowed=cards.filter(c=>id(c)!==id(lead)&&E.coverage(lead,c,known).covered).sort((a,b)=>ranks.get(id(b))-ranks.get(id(a))),needed=session.locked.filter(i=>Math.floor(i/3)===g&&i%3).map(i=>session.cards[i]);
const shortlist=[...new Map([...allowed.slice(0,12),...allowed.filter(c=>needed.includes(id(c))),...(session.mission&&node.mission.category?allowed.filter(c=>category(E,c,node.mission.category)).slice(0,8):[])].map(c=>[id(c),c])).values()];
for(let a=0;a<shortlist.length;a++)for(let b=a+1;b<shortlist.length;b++){
let trio=[lead,shortlist[a],shortlist[b]];if(needed.some(i=>!trio.some(c=>id(c)===i)))continue;
if(session.locked.includes(g*3+1)&&id(trio[1])!==session.cards[g*3+1])trio=[lead,trio[2],trio[1]];if(session.locked.some(i=>Math.floor(i/3)===g&&id(trio[i%3])!==session.cards[i]))continue;
const evaluation=group(E,trio,node,known),count=node.mission.category?trio.filter(c=>category(E,c,node.mission.category)).length:0;lists[g].push({cards:trio,ids:trio.map(id),score:evaluation.score,count});}
progress('Recherche du groupe '+(g?'B':'A')+'…');await new Promise(r=>setTimeout(r,0));}
// Keep alternatives at each quota, so a high-scoring non-mission group cannot erase valid pairs.
for(let g=0;g<2;g++)lists[g]=[0,1,2,3].flatMap(n=>lists[g].filter(x=>x.count===n).sort((a,b)=>b.score-a.score).slice(0,100));
const pairs=[];for(let a=0;a<lists[0].length;a++){if(cancel())throw Error('Recherche annulée.');const A=lists[0][a];for(const B of lists[1]){if(A.ids.some(i=>B.ids.includes(i))||session.mission&&node.mission.category&&A.count+B.count<node.mission.count)continue;const score=A.score+B.score+Math.min(A.score,B.score)*.35;pairs.push({cards:[...A.cards,...B.cards],score});}if(a%25===0)await new Promise(r=>setTimeout(r,0));}
let best=null;for(const p of pairs.sort((a,b)=>b.score-a.score).slice(0,40)){const e=assess(E,p.cards,node,known,session.mission);if(e.valid&&(!best||e.score>best.score))best={cards:p.cards.map(id),score:e.score};}return best;}
async function replace(E,pool,cards,node,known,session,index,cancel=()=>false){if(!Number.isInteger(index)||index<0||index>5||session.locked.includes(index))throw Error('Déverrouille cette carte avant de la remplacer.');if(cards.length!==6||cards.some(c=>!c))throw Error('Recalcule les groupes avant de remplacer une carte.');let best=null;for(let n=0;n<pool.length;n++){if(cancel())throw Error('Recherche annulée.');const c=pool[n];if(cards.some(x=>id(x)===id(c)))continue;const proposed=cards.map((x,i)=>i===index?c:x),e=assess(E,proposed,node,known,session.mission);if(e.valid&&(!best||e.score>best.score))best={cards:proposed.map(id),score:e.score};if(n%50===0)await new Promise(r=>setTimeout(r,0));}return best;}
function editBoard(s,values){validateSession(s);if(!s.board)throw Error('Démarre le suivi du combat.');const n=copy(s),b=copy(values);validateBoard(b,s.cards);b.lost=[...new Set([...s.board.lost,...b.lost,...s.cards.filter(i=>b.hp[i]===0)])];n.history=[...n.history,copy(n.board)].slice(-30);n.board=b;return validateSession(n);}
function exchange(s,cost){validateSession(s);if(!s.board||![1,2,3].includes(cost)||s.board.gauge<cost)throw Error('Jauge insuffisante pour cet échange.');const b=copy(s.board),target=b.active==='A'?'B':'A',out=s.cards.slice(b.active==='A'?0:3,b.active==='A'?3:6),incoming=s.cards.slice(target==='A'?0:3,target==='A'?3:6);if(incoming.every(i=>b.hp[i]===0))throw Error('Le groupe en attente est entièrement PERDU.');if(cost===2)out.forEach(i=>{if(b.hp[i]>0)b.hp[i]=Math.min(100,b.hp[i]+30);});b.gauge-=cost;b.active=target;return editBoard(s,b);}
function advice(s,node){if(!s.board)return ['Démarre le suivi après avoir formé les deux groupes.'];const b=s.board,g=b.active,ids=s.cards.slice(g==='A'?0:3,g==='A'?3:6),other=g==='A'?'B':'A',waiting=s.cards.slice(other==='A'?0:3,other==='A'?3:6),messages=[];
if(s.cards.every(i=>b.hp[i]===0))return ['Tous les personnages sont PERDUS : fin du combat.'];for(const t of node.heat.filter(t=>b.heat[g]>=t.level))messages.push('Groupe '+g+' · niveau '+t.level+' : '+t.effect);const weak=ids.some(i=>b.hp[i]>0&&b.hp[i]<=30),danger=ids.every(i=>b.hp[i]===0)||weak||node.heat.some(t=>b.heat[g]>=t.level);if(danger)messages.push(waiting.every(i=>b.hp[i]===0)?'Le groupe en attente est entièrement PERDU.':b.gauge>=1?'Envisage un échange vers '+other+' après vérification des attaques ennemies et de ses PV.':'Groupe actif fragile ; la jauge ne permet pas encore un échange.');else messages.push('Surveille les attaques et les PV de chaque personnage ; aucun tour sûr n’est garanti.');return messages;}
const API={key,empty,initial,validate,validateSession,validateBoard,context,group,assess,compose,replace,editBoard,exchange,advice};if(typeof module!=='undefined')module.exports=API;root.DokkanFrontierModel=API;
})(typeof window!=='undefined'?window:globalThis);
