/* Actual preparation and manual combat state; no simulated activation. */
(function(root){'use strict';
const record=x=>!!x&&typeof x==='object'&&!Array.isArray(x),num=(v,min,max)=>v===''||v==null?null:Number.isInteger(+v)&&+v>=min&&+v<=max?+v:null;
function profile(x={}){return {sa:num(x.sa,1,30),potential:num(x.potential,0,100),awakening:['unknown','base','ztur','zlr','superZtur','superZlr'].includes(x.awakening)?x.awakening:'unknown',links:record(x.links)?Object.fromEntries(Object.entries(x.links).slice(0,30).filter(([k,v])=>k.length<=100&&num(v,1,10)!==null).map(([k,v])=>[k,+v])):{}};}
function preparation(c,p={}){p=profile(p);const kit=c._kitVersion||'base',out=[];if(p.awakening==='unknown')out.push('Éveil réalisé à renseigner');else if(kit!==p.awakening)out.push('Kit utilisé : '+kit+' ; éveil déclaré : '+p.awakening);if(p.sa===null)out.push('Niveau ATT SP inconnu');else if(c.maxSALevel&&p.sa<c.maxSALevel)out.push('ATT SP '+p.sa+'/'+c.maxSALevel+' : à préparer');if(p.sa!==null&&c.maxSALevel&&p.sa>c.maxSALevel)out.push('ATT SP saisie au-dessus du maximum de ce kit : vérifie l’éveil sélectionné');if(p.potential===null)out.push('Potentiel inconnu');else if(p.potential<100)out.push('Potentiel déclaré : '+p.potential+' %');const links=(c.links||[]).map(k=>p.links[k]).filter(v=>v!=null);if(links.length<(c.links||[]).length)out.push('Certains niveaux de liens sont inconnus');return out;}
function counters(x={}){return {attacks:num(x.attacks,0,999)||0,hits:num(x.hits,0,999)||0,dodges:num(x.dodges,0,999)||0,appearances:num(x.appearances,0,99)||0};}
function thresholds(text,count,turn=1){text=String(text||'');const results=[];const re=/(?:après|effectué|subi|esquivé|effectue|subit|esquive)[^\n.!]{0,45}?(\d+)\s*(?:attaque(?:s)?|esquive(?:s)?)/gi;for(const m of text.matchAll(re)){const kind=/esquiv/i.test(m[0])?'dodges':/subi/i.test(m[0])?'hits':'attacks',need=+m[1];results.push({kind,need,current:count[kind]||0,reached:(count[kind]||0)>=need,text:m[0]});}for(const m of text.matchAll(/(?:à partir du|dès le)\s*(\d+)(?:e|ème|er)?\s*tour/gi))results.push({kind:'turn',need:+m[1],current:turn,reached:turn>=+m[1],text:m[0]});return results.slice(0,12);}
function signature(s){return JSON.stringify({cards:s.cards.map(c=>[c.id,c.kit,c.projected]),leader:s.leader,friend:s.friend,settings:s.settings});}
function changes(a,b){const ai=new Set(a.cards.map(c=>c.id)),bi=new Set(b.cards.map(c=>c.id));return {added:b.cards.filter(c=>!ai.has(c.id)),removed:a.cards.filter(c=>!bi.has(c.id)),kits:b.cards.filter(c=>a.cards.some(x=>x.id===c.id&&(x.kit!==c.kit||x.projected!==c.projected))),leader:a.leader!==b.leader,objective:a.objective!==b.objective||JSON.stringify(a.missions)!==JSON.stringify(b.missions)};}
function validate(x){
 if(!record(x)||!record(x.profiles||{})||!record(x.combat||{})||!Array.isArray(x.history||[])||(x.history||[]).length>100||!Array.isArray(x.goals||[])||(x.goals||[]).length>100||!Array.isArray(x.dataHistory||[])||(x.dataHistory||[]).length>30)throw Error('Suivi personnel invalide');
 for(const [id,p]of Object.entries(x.profiles||{}))if(!/^\d+$/.test(id)||!record(p)||JSON.stringify(profile(p))!==JSON.stringify(p))throw Error('Profil de carte invalide');
 const c=x.combat||{};if(c.team!==undefined&&typeof c.team!=='string'||c.turn!==undefined&&num(c.turn,1,99)!==c.turn||c.counts!==undefined&&!record(c.counts))throw Error('Compteurs invalides');
 for(const [id,v]of Object.entries(c.counts||{}))if(!/^\d+$/.test(id)||!record(v)||JSON.stringify(counters(v))!==JSON.stringify(v))throw Error('Compteurs invalides');
 for(const h of x.history||[])if(!record(h)||typeof h.id!=='string'||!Number.isFinite(Date.parse(h.date))||typeof h.signature!=='string'||!record(h.snapshot)||!record(h.snapshot.settings)||!Array.isArray(h.snapshot.cards)||h.snapshot.cards.length>6||h.snapshot.cards.some(c=>!record(c)||!/^\d+$/.test(c.id)||typeof c.name!=='string'||!['base','ztur','zlr','superZtur','superZlr'].includes(c.kit))||!Array.isArray(h.snapshot.missions)||h.snapshot.missions.some(m=>typeof m!=='string'))throw Error('Historique invalide');
 for(const g of x.goals||[])if(!record(g)||typeof g.id!=='string'||typeof g.title!=='string'||g.title.length>120||!Array.isArray(g.steps)||g.steps.length>30||g.steps.some(s=>!record(s)||typeof s.label!=='string'||s.label.length>300||typeof s.done!=='boolean'))throw Error('Objectif invalide');
 for(const h of x.dataHistory||[])if(!record(h)||typeof h.signature!=='string'||typeof h.date!=='string'||['added','changed','removed','events','missions','incomplete'].some(k=>!Number.isInteger(h[k])||h[k]<0))throw Error('Historique de collecte invalide');
 if(x.dataCards!==undefined&&(!record(x.dataCards)||Object.entries(x.dataCards).some(([k,v])=>!/^\d+$/.test(k)||typeof v!=='string'||v.length>100)))throw Error('Index de collecte invalide');
 return x;
}
const API={profile,preparation,counters,thresholds,signature,changes,validate};if(typeof module!=='undefined')module.exports=API;root.DokkanProgressModel=API;
})(typeof window!=='undefined'?window:globalThis);
