/* F2P methods are grouped by exact game name; training rates remain form-specific. */
(function(root){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeLink(url,label){return /^https:\/\/(?:www\.)?dbz-dokkanbattle\.com\//.test(url||'')?'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(label)+'</a>':'';}
function lookup(data,card){const id=String(card.candidateId||card.id||'');return data?.characters?.[data.cards?.[id]]||null;}
function render(data,card,family=[]){
 const row=lookup(data,card),title='<section class="detail-section sa-farming"><h3>Monter l’ATT SP avec des cartes F2P</h3>';
 if(!data)return title+'<p class="muted">Chargement des méthodes de farming…</p></section>';
 if(!row||row.status==='unknown')return title+'<p><b>À vérifier</b> · Aucune méthode suffisamment vérifiée pour cette fiche.</p><p class="muted">Ce statut ne signifie pas que le farming est impossible.</p></section>';
 if(row.status==='none-listed')return title+'<p><b>Aucune méthode F2P répertoriée</b></p><p class="muted">La source n’indique pas de carte gratuite compatible pour ce nom. Utilise des Kaïo si tu n’as pas de copie compatible ; ne sacrifie pas tes doublons utiles au potentiel.</p>'+safeLink(row.source,'Vérifier la fiche source')+'</section>';
 const methods=row.methods||[],ids=new Set(family.map(x=>String(x.id||x))),same=methods.some(m=>ids.has(m.donor)),hasFarm=methods.some(m=>m.acquisition==='event'),onlyExchange=methods.every(m=>m.acquisition==='exchange');
 const farmLocations=methods.flatMap(m=>m.origins||[]).flatMap(o=>o.locations||[]).filter(l=>l.event),closedFarm=hasFarm&&farmLocations.length&&farmLocations.every(l=>l.sourceStatus==='inactive')&&!methods.some(m=>m.acquisition==='exchange');
 const status=hasFarm?'Oui · carte à farmer':onlyExchange?'Oui · échange gratuit':'Oui · méthode F2P répertoriée';
 const details=methods.map(m=>{const samePath=ids.has(m.donor);return '<article class="sa-farm-method"><h4>'+esc(m.name)+' · '+esc(m.rarity)+' '+esc(m.type||'')+'</h4><p class="muted">ID '+esc(m.donor)+(samePath?' · Même chaîne d’éveil : hausse de SP garantie.':' · Autre carte : vérifie les chances de réussite dans l’entraînement.')+'</p>'+(m.evolve&&!samePath?'<p>La source propose une forme éveillée. Vérifie si sa forme de départ suffit dans le jeu avant de dépenser des médailles.</p>':'')+(m.origins.length?m.origins.map(o=>'<div class="sa-farm-origin"><b>'+esc(o.name)+' · carte obtenable '+esc(o.id)+'</b>'+o.locations.map(l=>l.acquisition==='exchange'?'<p>Échange Baba : '+esc(l.price||'Coût non renseigné')+' '+esc(l.name)+'</p>'+safeLink(l.source,'Voir le lieu d’échange'):'<p>'+esc(l.name)+(l.sourceStatus==='inactive'?' · Signalé indisponible lors de la collecte.':' · Disponibilité à confirmer en jeu.')+'</p>'+(l.event?'<button data-sa-event="'+esc(l.event)+'">Ouvrir l’événement →</button>':'')+safeLink(l.source,'Voir la source d’obtention')).join('')+'</div>').join(''):'<p class="muted">La carte est listée comme F2P ; son lieu d’obtention précis reste à vérifier dans sa fiche source.</p>')+safeLink(m.donorSource,'Voir la carte à obtenir')+'</article>';}).join('');
 return title+'<p><b>'+status+'</b></p><p>'+esc(methods[0]?.name||'')+' · '+esc(methods[0]?.rarity||'')+' '+esc(methods[0]?.type||'')+' peut servir à monter la SP.</p>'+(closedFarm?'<p class="muted">Les événements indiqués sont signalés indisponibles lors de la collecte. Vérifie leur retour ou les clés dans le jeu.</p>':'')+'<details><summary>Cartes à obtenir, événements et conditions</summary><p>Choisis la carte dans l’entraînement et vérifie le taux affiché avant de valider. Le taux dépend de la forme donnée ; les pourcentages d’une autre fiche ne sont pas appliqués à ta version.</p><p>'+ (same?'Une copie de la même chaîne est listée. Le jeu accepte aussi les formes de départ de cette chaîne pour augmenter la SP.':'Une carte différente peut servir jusqu’à SP 10. Au-delà, prévois une copie compatible de la même chaîne ou des Kaïo ; vérifie le gain affiché par le jeu.')+'</p><p class="muted">Plusieurs exemplaires de cartes différentes ne transfèrent pas automatiquement tous leurs niveaux de SP. Garde tes cartes principales et les doublons destinés au potentiel.</p>'+details+'<p class="muted">Méthodes contrôlées le '+esc(new Date(data.verifiedAt).toLocaleDateString('fr-FR',{timeZone:'Europe/Paris'}))+'. Référence : '+esc(row.sourceName||row.name)+' · ID '+esc(row.referenceId)+'. Aucun taux de drop ni gain au-delà de SP 10 n’est déduit de ces listes.</p>'+safeLink(row.source,'Source des méthodes F2P')+' · '+safeLink('https://www.dbz-dokkanbattle.com/announcement/106521','Règle actuelle des chaînes d’éveil')+'</details></section>';
}
const API={lookup,render};if(typeof module!=='undefined')module.exports=API;
if(typeof window==='undefined')return;
let data=null,failed=false;window.DokkanSAFarm={render(card){return failed?'<section class="detail-section sa-farming"><h3>Monter l’ATT SP avec des cartes F2P</h3><p>Les méthodes sont indisponibles. Tes données personnelles sont conservées.</p></section>':render(data,card,typeof familyFor==='function'?familyFor(card.candidateId||card.id):[])},get data(){return data;}};
fetch('sa-farm.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{data=d;if(document.querySelector('#sheet.on'))window.DokkanCatalogUI?.renderSheet();}).catch(()=>{failed=true;if(document.querySelector('#sheet.on'))window.DokkanCatalogUI?.renderSheet();});
document.addEventListener('click',async e=>{const button=e.target.closest?.('[data-sa-event]');if(!button)return;const id=button.dataset.saEvent;button.disabled=true;try{await ensureEvents();const event=teamEvents.events.find(x=>x.id===id);if(event){closeSheet();eventSettings.selected=id;eventSettings.stage='';eventSettings.missions=[];eventSettings.missionPage=0;eventSave();switchView('events');}else{const text=document.createElement('p');text.textContent='Cet événement n’est pas dans la collecte locale. Consulte sa source d’obtention.';button.after(text);}}catch(err){const text=document.createElement('p');text.textContent='Événement indisponible hors ligne. Consulte sa source quand tu es connecté.';button.after(text);}finally{button.disabled=false;}});
})(typeof window==='undefined'?globalThis:window);
