/* Team tools are built on demand to keep generation responsive. */
(function(){'use strict';
const M=window.DokkanTeamPlannerModel,E=window.DokkanTeamEngine,esc=teamEsc,key='dokkanos-team-planner-v1';
let compared='',notice='',replacement=null,opened=new Set(),saved={version:1,signature:'',order:[]};try{const raw=storageRead(key);if(raw)saved=M.validate(JSON.parse(raw));}catch(e){notice='Plan de départ illisible : indique à nouveau l’ordre réel.';}
const reportSignature=()=>JSON.stringify([selectedTeam,teamLeader,teamSettings.combat,teamSettings.event,teamSettings.eventStage,teamMission().requirements,teamKitContext().realProfiles]);
const labels={defense:'Indice défensif',offense:'Indice offensif',anchors:'Profils pour le slot 1',links:'Liens partagés',covered:'Cartes sous le leader',leader:'Total des bonus PV / ATT / DÉF du leader',boss:'Adaptation au boss',incomplete:'Fiches incomplètes',deficit:'Quotas manquants'};
const current=()=>({cards:teamCards(),leader:E.combatCard(resolveCard(teamLeader),teamKitContext()),friend:teamFriend(resolveCard(teamLeader)),context:teamContext()});
function evaluation(x){return E.evaluate(x.cards,x.leader,x.friend,teamMission(),teamKnown(),x.context);}
function comparison(){const a=current(),choices=[...(teamUndo?[{id:'previous',name:'Équipe précédente',...teamUndo}]:[]),...teamSaved()];if(!a.cards.length)return '<p>Prépare une équipe pour comparer ses choix.</p>';if(!choices.length)return '<p>Sauvegarde une autre composition ou génère une nouvelle équipe pour comparer avec la précédente.</p>';const b=choices.find(x=>x.id===compared)||choices[0];compared=b.id;const cards=b.cards.map(resolveCard).filter(Boolean),context={...a.context,useZA:b.settings?.useZA!==false},leader=E.combatCard(resolveCard(b.leader),context),friend=b.settings?.friend==='mirror'&&leader?{...leader,boxId:'FRIEND-'+leader.boxId,_friend:true}:b.settings?.friend?{...verifyCandidate(b.settings.friend),boxId:'FRIEND-'+b.settings.friend,_friend:true}:null,ea=evaluation(a),eb=evaluation({cards,leader,friend,context}),result=M.compare(ea,eb),valid=a.cards.length===6&&cards.length===6&&leader;
 return '<p>Même boss, mêmes missions et même priorité : ceux sélectionnés au-dessus. A = équipe actuelle ; B conserve son leader et son ami.</p><label>Composition B<select id="tpCompare">'+choices.map(x=>teamOption(x.id,x.name,b.id)).join('')+'</select></label><div class="compare-table"><table><thead><tr><th>Indicateur</th><th>A</th><th>B</th><th>B − A</th></tr></thead><tbody>'+result.deltas.map(x=>'<tr><th>'+labels[x.key]+'</th><td>'+x.a+'</td><td>'+x.b+'</td><td>'+(x.delta>0?'+':'')+x.delta+'</td></tr>').join('')+'</tbody></table></div><p><b>'+(valid?(result.preferred==='equal'?'Évaluations proches':'Préférence indicative : '+result.preferred):'Comparaison incomplète')+'</b> · '+esc(valid?result.reason:'Une composition ou son leader est indisponible.')+'</p>'+((result.uncertain||!a.context.boss?.available)?'<p class="ai-warning">Données partielles : vérifie les kits et les protections en jeu.</p>':'')+'<p class="muted">Les indices comparent les kits et synergies ; ils ne représentent pas des dégâts ni une probabilité de victoire.</p>';
}
function openingView(){const a=current(),cards=[...a.cards,...(a.friend?[a.friend]:[])];if(cards.length!==7)return '<p>Prépare six cartes et un leader ami pour établir les trois premiers tours.</p>';const signature=JSON.stringify([cards.map(c=>c.boxId),teamLeader,teamMission().requirements,teamSettings.eventStage]);const real=saved.signature===signature&&saved.order.length===7&&saved.order.every(k=>cards.some(c=>c.boxId===k)),order=real?saved.order:cards.map(c=>c.boxId);
 return '<p>Recopie les sept cartes dans leur ordre de départ réel. Sans saisie, la liste ci-dessous est seulement un exemple.</p><form id="tpOpening"><div class="pilot-form">'+order.map((value,i)=>'<label>Départ '+(i+1)+'<select name="slot'+i+'" data-tp-order="'+i+'">'+cards.map(c=>teamOption(c.boxId,teamRotationName(c),value)).join('')+'</select></label>').join('')+'</div><button>Calculer les trois premiers tours</button></form><p id="tpOpeningStatus" role="status">'+esc(!real&&saved.order.length?'Composition modifiée : indique un nouvel ordre de départ réel.':notice)+'</p>'+(real?turns(a,cards,order):'<p class="muted">Le tirage initial est aléatoire dans le jeu. Indique-le avant d’appliquer ce plan.</p>');
}
function turns(a,cards,order){const e=evaluation(a),plan=M.opening(E,cards,order,e.rotations,a.context);return plan.map(t=>'<article class="team-rotation"><h4>Tour '+t.turn+'</h4>'+t.cards.map((c,i)=>'<div class="rotation-position"><b>Slot '+(i+1)+' · '+esc(teamRotationName(c))+'</b><p>'+esc(t.placements[i].summary.join(' '))+'</p>'+t.placements[i].warnings.map(w=>'<small class="ai-warning">'+esc(w)+'</small>').join('')+'<small>Retour prévu : tour '+t.returns[i].turn+'</small></div>').join('')+'</article>').join('')+'<p class="muted">Plan sans verrouillage ennemi, transformation ni échange spécial. Les attaques réelles, le Ki, les PV et les conditions actives restent à vérifier avant chaque placement.</p>';}
function profileView(){return '<p>Les éveils Z déclarés sont prioritaires sur la projection. Le potentiel, l’ATT SP et les niveaux de liens donnent un petit bonus de préparation au classement, sans inventer de statistiques de combat.</p>'+teamCards().map(c=>{const p=window.DokkanProgress?.state.profiles[E.identity(c)],links=Object.values(p?.links||{});return '<article class="team-saved-row"><span><b>'+esc(c.name)+'</b><small>'+esc(p?'Éveil : '+p.awakening+' · potentiel : '+(p.potential??'?')+' % · ATT SP : '+(p.sa??'?')+' · liens connus : '+links.length+'/'+(c.links||[]).length:'Profil réel à renseigner')+'</small></span><button data-pilot="profiles" data-pilot-card="'+E.identity(c)+'">Renseigner ma carte</button></article>';}).join('');}
function fill(d){const type=d.dataset.tpPanel;d.querySelector('.tp-content').innerHTML=type==='compare'?comparison():type==='opening'?openingView():profileView();}
function enhance(){if(replacement?.signature&&replacement.signature!==reportSignature())replacement=null;const host=document.querySelector('#teams main');if(!host||host.dataset.teamMode&&host.dataset.teamMode!=='classic'||host.querySelector('#teamPlanner'))return;const target=host.querySelector('#teamAnalysis');if(!target)return;const section=document.createElement('section');section.id='teamPlanner';section.className='panel';section.innerHTML='<h3>Choisir et préparer mon équipe</h3>'+(['compare','opening','profiles'].map((k,i)=>'<details data-tp-panel="'+k+'" '+(opened.has(k)?'open':'')+'><summary>'+['Comparer mes compositions','Les trois premiers tours','Progression réelle de mes cartes'][i]+'</summary><div class="tp-content"></div></details>').join(''))+(replacement?'<div class="tp-replacement" role="status"><h4>Pourquoi ce remplacement ?</h4><p>'+esc(replacement.oldName)+' → '+esc(replacement.newName)+'</p><ul>'+replacement.reasons.map(r=>'<li>'+esc(r)+'</li>').join('')+'</ul><small>Alternative évaluée sous les contraintes actuelles ; elle peut présenter des compromis.</small></div>':'');target.after(section);section.querySelectorAll('details[open]').forEach(fill);section.querySelectorAll('[data-tp-panel]').forEach(d=>d.addEventListener('toggle',()=>{if(d.open){opened.add(d.dataset.tpPanel);fill(d);}else opened.delete(d.dataset.tpPanel);}));}
const original=renderTeam;renderTeam=function(){original();enhance();};
document.addEventListener('change',e=>{if(e.target.id==='tpCompare'){compared=e.target.value;fill(e.target.closest('details'));}if(e.target.dataset.tpOrder!==undefined){const selects=[...document.querySelectorAll('#tpOpening select')],changed=e.target,old=changed.dataset.previous||saved.order[Number(changed.dataset.tpOrder)];const other=selects.find(s=>s!==changed&&s.value===changed.value);if(other){const used=new Set(selects.map(s=>s.value)),missing=[...changed.options].map(o=>o.value).find(v=>!used.has(v));other.value=missing||old;}selects.forEach(s=>s.dataset.previous=s.value);}});
document.addEventListener('submit',e=>{if(e.target.id!=='tpOpening')return;e.preventDefault();try{const a=current(),cards=[...a.cards,a.friend],order=[...e.target.querySelectorAll('select')].map(s=>s.value);M.opening(E,cards,order,evaluation(a).rotations,a.context);const next={version:1,signature:JSON.stringify([cards.map(c=>c.boxId),teamLeader,teamMission().requirements,teamSettings.eventStage]),order};M.validate(next);if(!storageWrite(key,JSON.stringify(next)))throw Error('Plan non sauvegardé : stockage indisponible.');saved=next;notice='Plan calculé avec ton ordre réel.';fill(e.target.closest('details'));}catch(x){notice=x.message;document.getElementById('tpOpeningStatus').textContent=notice;}});
window.addEventListener('dokkanos-team-replacement',e=>{replacement=e.detail;});document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(b&&(b.id==='autoTeam'||['clear','bestLeader','jointMissions','undo'].includes(b.dataset.teamAction)||b.dataset.teamVariant!==undefined))replacement=null;},true);
window.DokkanTeamPlanner={enhance,getReplacement:()=>replacement};
})();
