/* Teams workspace: uses owned cards; preserves existing collection storage. */
const TE=window.DokkanTeamEngine;
let teamEvents={events:[],coverage:{complete:false}}, teamSettings={event:'',mission:'',friend:'mirror',category:'',count:6,types:0,combat:'balanced',disableDodge:false,search:'',locked:[]};
try{Object.assign(teamSettings,JSON.parse(storageRead('dokkanos-team-settings-v2')||'{}'))}catch(e){}
function normalizeTeamSettings(){
 teamSettings.locked=Array.isArray(teamSettings.locked)?[...new Set(teamSettings.locked.filter(x=>typeof x==='string'))].slice(0,6):[];
 for(const key of ['event','mission','friend','category','combat','search'])if(typeof teamSettings[key]!=='string')teamSettings[key]=key==='friend'?'mirror':'';
 teamSettings.count=[1,2,3,4,5,6].includes(+teamSettings.count)?+teamSettings.count:6;
 teamSettings.types=[0,2,3,4,5].includes(+teamSettings.types)?+teamSettings.types:0;
 teamSettings.disableDodge=teamSettings.disableDodge===true;
 if(!['balanced','survival','short'].includes(teamSettings.combat))teamSettings.combat='balanced';
}
normalizeTeamSettings();
const teamEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const teamSaveSettings=()=>storageWrite('dokkanos-team-settings-v2',JSON.stringify(teamSettings));
const teamKnown=()=>[...new Set(ownedTeamCards().flatMap(c=>c.categories||[]))];
function teamFriend(leader){if(teamSettings.friend==='mirror')return leader?{...leader,boxId:'FRIEND-'+leader.boxId,_friend:true}:null;const id=teamSettings.friend,c=CATALOG.cards?.find(c=>String(c.id)===id),m=localized(META.cards?.[id]);return c&&m?{...c,...m,candidateId:id,boxId:'FRIEND-'+id,image:localCardImage(id,m.image||c.image),_friend:true}:null;}
function teamMission(){const event=teamEvents.events.find(e=>e.id===teamSettings.event),source=event?.missions?.find(m=>m.id===teamSettings.mission);const requirements=[...(source?.requirements||[])];if(teamSettings.category)requirements.push({kind:'category',value:teamSettings.category,count:+teamSettings.count,includeFriend:false});if(+teamSettings.types)requirements.push({kind:'types',count:+teamSettings.types,includeFriend:false});return {...source,requirements};}
leaderCoverageFor=(leader,card)=>TE.coverage(leader,card,teamKnown());
function teamLabel(c){return (c.name||'Carte')+' · '+(c.type||'?')+' · '+(c.rarity||'?')+' · ID '+(c.candidateId||c.id||'?');}
function teamOption(value,label,current){return `<option value="${teamEsc(value)}" ${String(value)===String(current)?'selected':''}>${teamEsc(label)}</option>`;}
function teamCard(c,leader,friend){const cov=TE.coverage(leader,c,teamKnown()),p=TE.passive(c,[...selectedTeam.map(resolveCard).filter(Boolean),...(friend?[friend]:[])],teamSettings);return `<article class="team-unit"><button class="team-unit-detail" data-team-open="${teamEsc(c.boxId)}"><img src="${teamEsc(c.image)}" onerror="imageFallback(this,'${teamEsc(c.candidateId)}','')"><strong>${teamEsc(c.name)}</strong><small>${teamEsc(c.type)} · ${teamEsc(c.rarity)} · ${teamEsc(c.candidateId)}</small></button><p>${cov.covered?`Leader : PV ${cov.hp} / ATT ${cov.atk} / DÉF ${cov.def} %`:'Couverture Leader inconnue ou absente'}</p><small>${teamEsc(p.roles.join(' · ')||'Kit à analyser')}</small><div class="team-unit-actions"><button data-team-lock="${teamEsc(c.boxId)}" aria-pressed="${teamSettings.locked.includes(c.boxId)}">${teamSettings.locked.includes(c.boxId)?'🔒 Imposée':'Imposer'}</button><button data-team-remove="${teamEsc(c.boxId)}">Retirer</button></div></article>`;}
function teamStatus(check){return check.rows.map(x=>`<p class="${x.ok?'ai-ok':'ai-warning'}">${x.unknown?'À vérifier':x.ok?'✓':'⚠'} ${teamEsc(x.r.kind==='category'?x.r.value:x.r.kind==='types'?'Types distincts':x.r.kind==='excludeRarity'?'Sans '+x.r.value:x.r.value||x.r.kind)} ${x.unknown?'':x.count+'/'+x.need}${x.r.includeFriend?' (ami inclus)':' (ami exclu)'}</p>`).join('');}
function teamSaved(){try{const s=JSON.parse(storageRead('dokkanos-saved-teams-v2')||'[]');return Array.isArray(s)?s.filter(x=>record(x)&&typeof x.id==='string'&&x.cards?.length<=6&&typeof x.name==='string'&&Array.isArray(x.cards)&&x.cards.every(id=>typeof id==='string')&&record(x.settings)&&Array.isArray(x.settings.locked)&&x.settings.locked.every(id=>typeof id==='string')):[]}catch(e){return[]}}
renderTeam=function(){const ownedIds=new Set(ownedTeamCards().map(c=>c.boxId));selectedTeam=selectedTeam.filter(id=>ownedIds.has(id));storageWrite('dokkanos-team',JSON.stringify(selectedTeam));teamSettings.locked=teamSettings.locked.filter(id=>ownedIds.has(id));if(teamLeader&&!ownedIds.has(teamLeader)){teamLeader='';storageWrite('dokkanos-team-leader','');}const host=document.querySelector('#teams main');if(!host)return;const owned=ownedTeamCards(),known=teamKnown().sort((a,b)=>a.localeCompare(b,'fr')),leader=teamLeader?resolveCard(teamLeader):null,team=selectedTeam.map(resolveCard).filter(Boolean),friend=teamFriend(leader),mission=teamMission(),e=TE.evaluate(team,leader,friend,mission,known,teamSettings),event=teamEvents.events.find(x=>x.id===teamSettings.event),friends=Object.entries(META.cards||{}).filter(([,m])=>m.fr?.leader||m.leader).map(([id,m])=>({id,...localized(m)})).sort((a,b)=>String(a.name).localeCompare(String(b.name),'fr'));
 host.innerHTML=`<div class="team-heading"><div><span class="eyebrow">LABORATOIRE D’ÉQUIPES</span><h2>Une équipe pour ton objectif</h2><p class="muted">Tes cartes confirmées, les deux leaders et les conditions du combat.</p></div><span id="teamCount" class="badge neutral">${team.length}/6</span></div>
 <div class="team-workflow"><a href="#teamObjective">1 · Objectif</a><a href="#teamComposition">2 · Composition</a><a href="#teamAnalysis">3 · Stratégie</a><a href="#teamSaved">4 · Sauvegardes</a></div>
 <section id="teamObjective" class="panel"><h3>Événement et mission</h3><p class="muted">${teamEvents.coverage?.complete?'Catalogue importé':'Catalogue partiel : seuls les objectifs vérifiés ci-dessous sont intégrés.'} ${teamEsc(teamEvents.verifiedAt?'Vérifié le '+teamEvents.verifiedAt:'')}</p><div class="team-form"><label>Événement<select data-team-setting="event">${teamOption('','Objectif personnalisé',teamSettings.event)}${teamEvents.events.map(x=>teamOption(x.id,x.name,teamSettings.event)).join('')}</select></label><label>Mission<select data-team-setting="mission">${teamOption('','Composition libre',teamSettings.mission)}${(event?.missions||[]).map(x=>teamOption(x.id,x.title,teamSettings.mission)).join('')}</select></label></div>${mission.title?`<p>${teamEsc(mission.title)}</p>${mission.notes?'<p class="muted">'+teamEsc(mission.notes)+'</p>':''}${mission.end?'<p class="muted">Fin de mission : '+teamEsc(new Date(mission.end).toLocaleString('fr-FR'))+'</p>':''}${mission.manualCheck?'<p class="ai-warning">Des conditions doivent être confirmées en combat.</p>':''}`:''}${event?.source?`<a href="${teamEsc(event.source)}" target="_blank" rel="noopener">Consulter les missions et niveaux à la source</a>`:''}<details><summary>Contraintes personnalisées et contexte</summary><div class="team-form"><label>Catégorie obligatoire<select data-team-setting="category">${teamOption('','Aucune',teamSettings.category)}${known.map(x=>teamOption(x,x,teamSettings.category)).join('')}</select></label><label>Nombre de cartes (sans l’ami)<select data-team-setting="count">${[1,2,3,4,5,6].map(x=>teamOption(x,x,teamSettings.count)).join('')}</select></label><label>Types distincts requis<select data-team-setting="types">${[0,2,3,4,5].map(x=>teamOption(x,x||'Aucun',teamSettings.types)).join('')}</select></label><label>Priorité<select data-team-setting="combat">${[['balanced','Équilibrée'],['survival','Survie'],['short','Combat court']].map(([v,l])=>teamOption(v,l,teamSettings.combat)).join('')}</select></label><label class="team-checkbox"><input type="checkbox" data-team-setting="disableDodge" ${teamSettings.disableDodge?'checked':''}> Esquive désactivée par le boss</label></div></details>${mission.id?`<label class="team-checkbox"><input type="checkbox" data-team-completed="${teamEsc(mission.id)}" ${storageRead('dokkanos-mission-done-'+mission.id)==='yes'?'checked':''}> Mission effectuée (confirmation manuelle)</label>`:''}${teamStatus(e.check)}${e.check.rows.length&&e.check.ok?'<p class="ai-ok">✓ Contraintes de composition respectées.</p>':''}</section>
 <section id="teamComposition" class="panel"><h3>Leader, ami et six cartes</h3><div class="team-form"><label>Leader de ta Box<select id="leaderSelect">${teamOption('','Choisir un leader',teamLeader)}${owned.filter(c=>c.leader).sort((a,b)=>teamLabel(a).localeCompare(teamLabel(b),'fr')).map(c=>teamOption(c.boxId,teamLabel(c),teamLeader)).join('')}</select></label><label>Leader ami<select data-team-setting="friend">${teamOption('mirror','Même carte que mon leader',teamSettings.friend)}${friends.map(c=>teamOption(c.id,teamLabel({...c,candidateId:c.id}),teamSettings.friend)).join('')}</select></label></div>${leader?`<details><summary>Aptitude Leader de ${teamEsc(leader.name)}</summary><p class="team-skill">${teamEsc(leader.leader)}</p></details>`:''}${friend?`<details><summary>Ami : ${teamEsc(friend.name)} · ${teamEsc(friend.type)}</summary><p class="team-skill">${teamEsc(friend.leader)}</p><p class="muted">L’ami reste en dehors des six cartes et des quotas qui l’excluent.</p></details>`:''}<div class="team-toolbar"><button id="autoTeam" class="primary">Optimiser cette équipe</button><button data-team-action="bestLeader">Comparer les leaders</button><button id="clearTeam">Vider</button></div><p id="teamBuildStatus" role="status" aria-live="polite"></p><div id="teamSlots" class="team-roster">${team.map(c=>teamCard(c,leader,friend)).join('')}${Array.from({length:6-team.length},(_,i)=>`<div class="team-unit team-empty">Emplacement ${team.length+i+1}</div>`).join('')}</div><p class="muted">Impose les cartes à conserver avant l’optimisation. Une équipe incomplète indique qu’il manque des cartes confirmées ou des données de leader.</p></section>
 <section id="teamAnalysis" class="panel"><h3>Rotations et passifs</h3><p class="muted">Proposition heuristique à partir des fiches disponibles. Les niveaux de liens, équipements, éveils-Z réellement effectués et valeurs en combat ne sont pas connus.</p><div class="team-analysis-kpis"><span><b>${e.cover.filter(x=>x.covered).length}/${team.length}</b> sous ton leader</span><span><b>${e.friendCover.filter(x=>x.covered).length}/${team.length}</b> sous l’ami</span><span><b>${e.profiles.filter(x=>x.complete).length}/${team.length}</b> kits renseignés</span></div>${e.rotations.map((r,i)=>`<div class="team-rotation"><b>Rotation ${i+1}</b><p>${teamEsc(r.a.name)} → ${teamEsc(r.b.name)}</p><small>${teamEsc(r.links.join(' · ')||'Aucun lien partagé')}</small>${r.uncertain?'<p class="ai-warning">Position 1 à confirmer : protection de base non identifiée.</p>':''}</div>`).join('')}${team.length?`<p class="muted">Flottants : ${team.filter(c=>!e.rotations.some(r=>r.a.boxId===c.boxId||r.b.boxId===c.boxId)).map(c=>teamEsc(c.name)).join(', ')||'—'}</p>`:''}${team.map((c,i)=>`<details><summary>${teamEsc(c.name)} · ${teamEsc(e.profiles[i].roles.join(', ')||'Kit non évalué')}</summary><p>Leader : PV +${e.cover[i].hp} %, ATT +${e.cover[i].atk} %, DÉF +${e.cover[i].def} %${e.cover[i].unknown?' · lecture partielle':''}</p>${e.profiles[i].effects.map(x=>`<div class="team-effect ${x.state}"><b>${teamEsc(x.condition)} · ${x.state==='active'?'Détecté actif':x.state==='missing'?'Non rempli':'À confirmer'}</b><p class="team-skill">${teamEsc(x.text)}</p></div>`).join('')}${e.profiles[i].warnings.map(x=>`<p class="ai-warning">${teamEsc(x)}</p>`).join('')}</details>`).join('')}</section>
 <section class="panel"><h3>Candidats de ta Box</h3><label>Rechercher une carte<input type="search" id="teamSearch" placeholder="Nom, type ou ID" value="${teamEsc(teamSettings.search)}"></label><div id="teamCandidates"></div></section>
 <section id="teamSaved" class="panel"><h3>Mes compositions</h3><div class="team-toolbar"><label>Nom de l’équipe<input id="teamName" maxlength="80" placeholder="Ex. Saga de Boo — mission 4 cartes"></label><button data-team-action="save">Sauvegarder</button></div>${teamSaved().map(x=>`<div class="team-saved-row"><span>${teamEsc(x.name)}</span><button data-team-load="${teamEsc(x.id)}">Charger</button><button data-team-delete="${teamEsc(x.id)}">Supprimer</button></div>`).join('')||'<p class="muted">Tes compositions seront conservées sur cet appareil.</p>'}</section>`;
 renderTeamCandidates();
};
function renderTeamCandidates(){const host=document.querySelector('#teamCandidates');if(!host)return;const leader=teamLeader?resolveCard(teamLeader):null,team=selectedTeam.map(resolveCard).filter(Boolean),friend=teamFriend(leader);const rows=ownedTeamCards().filter(c=>!selectedTeam.includes(c.boxId)&&TE.norm(teamLabel(c)).includes(TE.norm(teamSettings.search))).map(c=>({c,cov:TE.coverage(leader,c,teamKnown()),p:TE.passive(c,[...team,c],teamSettings),links:Math.max(0,...team.map(t=>TE.links(c,t).length))})).sort((a,b)=>Number(b.cov.covered)-Number(a.cov.covered)||b.p.defense-a.p.defense||b.links-a.links).slice(0,40);host.innerHTML=rows.map(({c,cov,p,links})=>`<div class="candidate-row ${cov.covered?'covered':'uncovered'}"><img loading="lazy" src="${teamEsc(c.image)}" onerror="imageFallback(this,'${teamEsc(c.candidateId)}','')"><div><b>${teamEsc(c.name)}</b><small>${teamEsc(c.type)} · ${teamEsc(c.rarity)} · ${teamEsc(c.candidateId)}</small><p>${cov.covered?'Sous le leader':'Couverture inconnue ou absente'} · ${links} liens avec sa meilleure paire</p><small>${teamEsc(p.roles.join(' · '))}</small></div><button data-team-add="${teamEsc(c.boxId)}" ${team.length>=6?'disabled':''} aria-label="Ajouter ${teamEsc(c.name)}">+</button></div>`).join('')||'<p class="muted">Aucune carte confirmée correspondante. Tu peux confirmer tes cartes dans Inventaire et À vérifier.</p>';}
autoBuildTeam=function(){const leader=resolveCard(teamLeader);if(!leader)return alert('Choisis un leader de ta Box.');const locked=teamSettings.locked.map(resolveCard).filter(Boolean),result=TE.build(ownedTeamCards(),leader,{friend:teamFriend(leader),mission:teamMission(),known:teamKnown(),context:teamSettings,locked});if(result.error)return alert(result.error);selectedTeam=result.team.map(c=>c.boxId);storageWrite('dokkanos-team',JSON.stringify(selectedTeam));renderTeam();document.querySelector('#teamBuildStatus').textContent=result.team.length<6?'Équipe incomplète : pas assez de cartes couvertes disponibles.':result.check.deficit?'Aucune composition respectant toutes les contraintes trouvée. Vérifie ta Box et tes cartes imposées.':'Composition proposée. Vérifie les conditions de passif et de mission ci-dessous.';};
clearTeam=function(){selectedTeam=[];teamSettings.locked=[];teamSaveSettings();storageWrite('dokkanos-team','[]');renderTeam();};
removeFromTeam=function(id){if(id===teamLeader){teamLeader='';storageWrite('dokkanos-team-leader','');}selectedTeam=selectedTeam.filter(x=>x!==id);teamSettings.locked=teamSettings.locked.filter(x=>x!==id);teamSaveSettings();storageWrite('dokkanos-team',JSON.stringify(selectedTeam));renderTeam();};
document.addEventListener('input',e=>{if(e.target.id==='teamSearch'){teamSettings.search=e.target.value;renderTeamCandidates();}});
document.addEventListener('change',e=>{if(e.target.dataset.teamCompleted){storageWrite('dokkanos-mission-done-'+e.target.dataset.teamCompleted,e.target.checked?'yes':'no');return;}const key=e.target.dataset.teamSetting;if(!key)return;teamSettings[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;if(key==='event')teamSettings.mission='';teamSaveSettings();renderTeam();});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.teamOpen){openCard(d.teamOpen);return;}if(d.teamAdd){addCandidate(d.teamAdd);return;}if(d.teamRemove){removeFromTeam(d.teamRemove);return;}if(d.teamLock){teamSettings.locked=teamSettings.locked.includes(d.teamLock)?teamSettings.locked.filter(x=>x!==d.teamLock):[...teamSettings.locked,d.teamLock];teamSaveSettings();renderTeam();return;}if(d.teamLoad){const s=teamSaved().find(x=>x.id===d.teamLoad);if(s){const owned=new Set(ownedTeamCards().map(c=>c.boxId));selectedTeam=s.cards.filter(id=>owned.has(id));teamLeader=owned.has(s.leader)?s.leader:'';Object.assign(teamSettings,s.settings);normalizeTeamSettings();storageWrite('dokkanos-team',JSON.stringify(selectedTeam));storageWrite('dokkanos-team-leader',teamLeader);teamSaveSettings();renderTeam();}return;}if(d.teamDelete){storageWrite('dokkanos-saved-teams-v2',JSON.stringify(teamSaved().filter(x=>x.id!==d.teamDelete)));renderTeam();return;}if(d.teamAction==='save'){if(!selectedTeam.length)return alert('Ajoute au moins une carte.');const name=document.querySelector('#teamName').value.trim()||'Mon équipe';const saved=teamSaved();saved.push({id:String(Date.now()),name,cards:[...selectedTeam],leader:teamLeader,settings:{...teamSettings,locked:[...teamSettings.locked]}});storageWrite('dokkanos-saved-teams-v2',JSON.stringify(saved));renderTeam();}if(d.teamAction==='bestLeader'){b.disabled=true;b.textContent='Comparaison…';await new Promise(r=>setTimeout(r,0));const pool=ownedTeamCards(),known=teamKnown(),ranked=pool.filter(c=>c.leader).map(c=>({c,coverage:pool.filter(x=>TE.coverage(c,x,known).covered).length})).sort((a,b)=>b.coverage-a.coverage).slice(0,10);const results=ranked.map(({c})=>({leader:c,result:TE.build(pool,c,{friend:teamFriend(c),mission:teamMission(),known,context:teamSettings,locked:teamSettings.locked.map(resolveCard).filter(Boolean)})})).filter(x=>!x.result.error).sort((a,b)=>b.result.score-a.result.score);if(results[0]){teamLeader=results[0].leader.boxId;storageWrite('dokkanos-team-leader',teamLeader);autoBuildTeam();document.querySelector('#teamBuildStatus').textContent='Proposition après comparaison de '+results.length+' leaders présélectionnés. Les données incomplètes peuvent limiter le choix.';}else{renderTeam();alert('Aucun leader compatible avec les cartes imposées.');}}});
fetch('events.json').then(r=>{if(!r.ok)throw Error('Événements indisponibles');return r.json()}).then(data=>{if(!Array.isArray(data?.events)||data.events.some(e=>!e||typeof e.id!=='string'||!Array.isArray(e.missions)))throw Error('Catalogue invalide');teamEvents=data;if(document.querySelector('#teams')?.classList.contains('on'))renderTeam();}).catch(()=>{teamEvents.coverage={complete:false,error:true};});
