/* Progressive disclosure for teams; the team engine and delegated actions remain authoritative. */
(function(){'use strict';
const states=new Map();
function fold(panel,key,label,open=false){if(!panel||panel.querySelector(':scope > [data-team-fold]'))return;const d=document.createElement('details');d.className='team-ui-fold';d.dataset.teamFold=key;d.open=states.has(key)?states.get(key):open;const summary=document.createElement('summary');summary.textContent=label;d.append(summary);while(panel.firstChild)d.append(panel.firstChild);panel.append(d);d.addEventListener('toggle',()=>{if(d.isConnected)states.set(key,d.open)});return d;}
function enhance(){const host=document.querySelector('#teams main');if(!host||host.dataset.teamUi==='ready')return;host.dataset.teamUi='ready';const objective=host.querySelector('#teamObjective'),leader=host.querySelector('#teamLeaderPanel'),cards=teamCards();
 // The renderer replaces children in place; mark the new composition, not the persistent host.
 const title=host.querySelector('.team-heading h2');if(title)title.textContent=cards.length?'Mon équipe · '+cards.length+'/6 cartes':'Préparer mon équipe';
 const source=host.querySelector('.team-heading + .panel');if(source&&objective){source.classList.add('team-source');const p=source.querySelector('p');if(p)p.textContent=teamSettings.pool==='catalog'?'Écarte les cartes que tu ne possèdes pas, puis recompose.':'Seules tes cartes confirmées sont utilisées.';objective.querySelector('summary').after(source);}
 if(objective){objective.open=states.has('objective')?states.get('objective'):cards.length<6;objective.addEventListener('toggle',()=>{if(objective.isConnected)states.set('objective',objective.open)});const boss=objective.querySelector('.team-boss');fold(boss,'boss','Boss · conseils et informations');const joint=objective.querySelector('.team-joint');fold(joint,'missions','Combiner plusieurs missions'+(teamSettings.eventMissions.length?' · '+teamSettings.eventMissions.length+' sélectionnées':''),teamSettings.eventMissions.length>0);const forms=objective.querySelectorAll(':scope > .team-form');if(forms.length>1){const custom=forms[forms.length-1];fold(custom,'constraints','Contraintes personnalisées',!!teamSettings.category||!!teamSettings.types);}}
 if(leader){const search=document.createElement('div');search.className='team-leader-search';const nodes=[...leader.children].filter(n=>n.matches('.team-recent,label,.team-scope,#teamLeaderResults'));for(const n of nodes)search.append(n);leader.querySelector('.team-section-title').after(search);fold(search,'leader-search',teamLeader?'Changer de leader':'Choisir un leader manuellement',!teamLeader&&teamSettings.pool==='owned');}
 const partners=host.querySelector('#teamCandidates')?.closest('.panel');if(partners){partners.id='teamPartners';fold(partners,'partners',teamSettings.replace?'Choisir la carte de remplacement':'Ajouter ou remplacer une carte',!!teamSettings.replace);}
 const analysis=host.querySelector('#teamAnalysis');if(analysis){const heading=analysis.querySelector('h3');if(heading)heading.textContent='Plan de combat et rotations';for(const [i,rotation] of [...analysis.querySelectorAll('.team-rotation')].entries()){const names=[...rotation.querySelectorAll('.rotation-position-heading b')].map(n=>n.textContent);fold(rotation,'rotation-'+i,'Rotation '+(i+1)+' · '+names.join(' + '));}if(!cards.length)analysis.hidden=true;}
 fold(host.querySelector('.companion-team-tools'),'tools','Autres outils de combat');
 const nav=host.querySelector('.ux-team-steps');if(nav){nav.innerHTML='<button data-ux-scroll="teamObjective">Objectif</button><button data-ux-scroll="teamComposition">Mon équipe</button><button data-ux-scroll="teamAnalysis">Rotations</button><button data-ux-scroll="teamSaved">Sauvegardes</button>';}
}
// A render writes a fresh heading each time. Reset only then, avoiding observer loops.
window.DokkanTeamUI={enhance(){const host=document.querySelector('#teams main');if(host&&!host.querySelector('.team-ui-fold'))delete host.dataset.teamUi;enhance();},openPartners(){const d=document.querySelector('#teamPartners > details');if(d){d.open=true;states.set('partners',true);d.scrollIntoView({behavior:'smooth',block:'start'});}}};
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-ux-scroll]');if(!b||!document.querySelector('#teams.on'))return;const target=document.getElementById(b.dataset.uxScroll);if(target?.tagName==='DETAILS')target.open=true;});
})();
