/* Fast visual verification. Every selection is explicit; recognition never validates a card. */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={active:false,ids:[],choices:new Map(),checked:new Set(),deferred:new Set(),sort:'confidence',undo:null,autoNext:true};
const rawCard=id=>DB.cards.find(c=>c.boxId===captureCanonicalId(id));
function proposals(c){
 const ids=[c.candidateId,c.runnerId,...(c.observations||[]).flatMap(o=>[o.candidateId,o.runnerId])];
 return [...new Set(ids.filter(Boolean).map(String))].map(verifyCandidate).filter(x=>x&&isPlayableCard(x)).slice(0,4);
}
function ranked(){return verifyPending().filter(c=>!state.deferred.has(c.boxId)).sort((a,b)=>state.sort==='capture'?0:Number(!!a._overlapConflict)-Number(!!b._overlapConflict)||(Number(b.inliers)||0)-(Number(a.inliers)||0));}
function fill(){state.ids=ranked().slice(0,20).map(c=>c.boxId);state.choices.clear();state.checked.clear();for(const id of state.ids){const p=proposals(rawCard(id))[0];if(p)state.choices.set(id,String(p.id));}}
function count(){return state.ids.filter(id=>state.checked.has(id)&&!rawCard(id)?.validated&&state.choices.has(id)).length;}
function refresh(){render();stats();renderDuplicates();renderMissing();renderInventory();renderManualOwned();renderAnalysis();}
function canUndo(){return !!state.undo&&storageRead('dokkanos-edits')===state.undo.after;}
function controls(){const n=count(),b=document.getElementById('verifyBatchConfirm');if(b){b.disabled=!n;b.textContent='Valider les '+n+' cartes cochées';}const undo=document.getElementById('verifyBatchUndo');if(undo)undo.disabled=!canUndo();}
function candidateHTML(p,boxId,chosen){return '<button type="button" class="vb-proposal '+(chosen===String(p.id)?'on':'')+'" data-vb-choice="'+esc(p.id)+'" data-vb-box="'+esc(boxId)+'" aria-pressed="'+(chosen===String(p.id))+'"><img loading="lazy" src="'+esc(p.image)+'" alt="'+esc(p.name)+'"><span>'+esc(p.name)+'<small>'+esc([p.rarity,p.type,'ID '+p.id].filter(Boolean).join(' · '))+'</small></span></button>';}
function row(c){const id=c.boxId,p=verifyCandidate(state.choices.get(id)),suggestions=proposals(c);return '<article class="vb-row" data-vb-row="'+esc(id)+'"><div class="vb-row-title"><label><input type="checkbox" data-vb-check="'+esc(id)+'" '+(state.checked.has(id)?'checked':'')+' '+(!p?'disabled':'')+'> Correspondance correcte</label><small>'+esc(c.capture)+' · '+esc(c.position)+'</small></div><div class="vb-compare"><figure><img loading="lazy" src="'+esc(c.crop||c.image)+'" alt="Ma capture '+esc(id)+'"><figcaption>Ma capture</figcaption></figure><figure><img loading="lazy" src="'+esc(p?.image||'assets/icon-192.png')+'" alt="'+esc(p?.name||'Aucune proposition')+'"><figcaption>'+esc(p?.name||'Carte à rechercher')+'<small>'+esc(p?[p.rarity,p.type,'ID '+p.id].filter(Boolean).join(' · '):'')+'</small></figcaption></figure></div>'+(c._overlapConflict?'<p class="vb-warning">Les anciennes identifications diffèrent : compare les captures avant de cocher.</p>':'')+'<details class="vb-alternatives"><summary>Autres propositions / corriger</summary><div class="vb-proposals">'+suggestions.map(x=>candidateHTML(x,id,state.choices.get(id))).join('')+'</div><button type="button" data-vb-edit="'+esc(id)+'">Rechercher dans tout le catalogue</button></details>'+verifyCaptureDetails(c)+'</article>';}
function draw(){const root=document.getElementById('verifyList');if(!root)return;const pending=verifyPending();state.ids=state.ids.filter(id=>rawCard(id)&&!rawCard(id).validated);if(!state.ids.length&&ranked().length)fill();root.innerHTML='<section class="vb-panel"><div class="vb-heading"><div><h3>Vérification par lots de 20</h3><p>'+pending.length+' cartes restantes · '+state.ids.length+' dans ce lot</p></div><button type="button" data-vb-mode="single">Mode individuel</button></div><p>Compare les deux images et coche uniquement les correspondances correctes. Rien n’est coché automatiquement.</p><label>Trier <select id="vbSort"><option value="confidence" '+(state.sort==='confidence'?'selected':'')+'>Plus de repères en premier</option><option value="capture" '+(state.sort==='capture'?'selected':'')+'>Ordre des captures</option></select></label><p class="muted">Le tri utilise les repères de reconnaissance ; il ne garantit pas une identification exacte.</p><div class="vb-list">'+state.ids.map(id=>row(rawCard(id))).join('')+'</div>'+(!state.ids.length?'<p>'+(!pending.length?'Tout est validé 🎉':'Les cartes mises de côté restent à vérifier.')+'</p>':'')+'<div class="vb-actions"><button type="button" id="verifyBatchConfirm" class="primary">Valider les cartes cochées</button><button type="button" id="verifyBatchUndo">Annuler le dernier lot</button><button type="button" data-vb-next>Autre lot / laisser celles-ci pour plus tard</button>'+(state.deferred.size?'<button type="button" data-vb-reset>Reprendre les cartes mises de côté</button>':'')+'</div></section>';controls();}
const originalRender=renderVerify;
renderVerify=function(){if(state.active&&!verifyDraft.boxId){draw();return;}originalRender();const root=document.getElementById('verifyList');if(!root)return;if(!verifyDraft.boxId){const bar=document.createElement('div');bar.className='vb-start panel';bar.innerHTML='<h3>Vérifier plus vite</h3><p>Compare 20 cartes à la fois, coche les bonnes propositions et valide le lot.</p><button type="button" class="primary" data-vb-mode="batch">Commencer un lot de 20</button>'+(state.undo?'<button type="button" id="verifyBatchUndo" '+(canUndo()?'':'disabled')+'>Annuler le dernier lot</button>':'');root.prepend(bar);return;}
 const c=rawCard(verifyDraft.boxId),host=document.createElement('section');host.className='vb-quick';host.innerHTML='<h3>Propositions rapides</h3><div class="vb-proposals">'+proposals(c).map(x=>candidateHTML(x,c.boxId,verifyDraft.cardId)).join('')+'</div><label><input type="checkbox" id="vbAutoNext" '+(state.autoNext?'checked':'')+'> Passer automatiquement à la suivante après validation</label>';root.querySelector('.verify-finder-label')?.before(host);
};
const originalConfirm=verifyConfirm;
verifyConfirm=function(){const id=verifyDraft.boxId;originalConfirm();if(!rawCard(id)?.validated)return;if(state.active){state.ids=state.ids.filter(x=>x!==id);state.checked.delete(id);state.choices.delete(id);renderVerify();}else if(state.autoNext){const next=ranked()[0];if(next)verifySelectPosition(next.boxId);}};
function commit(){const ids=state.ids.filter(id=>state.checked.has(id)&&!rawCard(id)?.validated&&state.choices.has(id));if(!ids.length)return;const rows=ids.map(id=>({c:rawCard(id),p:verifyCandidate(state.choices.get(id))}));if(rows.some(x=>!x.c||!x.p||!isPlayableCard(x.p))){verifyMessage('Une proposition est indisponible. Corrige-la avant de valider.','error');return;}const before=storageRead('dokkanos-edits'),cards=rows.map(x=>JSON.parse(JSON.stringify(x.c))),oldIds=[...state.ids],oldChoices=[...state.choices],oldChecked=[...state.checked];for(const {c,p} of rows){assignIdentification(c,p.id);c._edited=true;c._overlapConflict=false;c.validated=true;c.confidence='Validée manuellement';}if(!saveEdits()){for(const c of cards){const at=DB.cards.findIndex(x=>x.boxId===c.boxId);DB.cards[at]=c;}verifyMessage('Sauvegarde impossible : le lot reste à vérifier.','error');return;}
 state.undo={before,after:storageRead('dokkanos-edits'),cards,ids:oldIds,choices:oldChoices,checked:oldChecked};state.ids=state.ids.filter(id=>!ids.includes(id));for(const id of ids)state.checked.delete(id);refresh();verifyMessage('✓ '+ids.length+' cartes validées. Tu peux annuler le dernier lot.');window.DokkanExperience?.notify(ids.length+' cartes validées.');}
function undo(){if(!canUndo()){verifyMessage('Une autre modification a été enregistrée. Ce lot ne peut plus être annulé.','error');return;}const u=state.undo;try{if(u.before===null)localStorage.removeItem('dokkanos-edits');else if(!storageWrite('dokkanos-edits',u.before))throw Error('save');}catch(e){verifyMessage('Annulation impossible : sauvegarde indisponible.','error');return;}for(const c of u.cards){const at=DB.cards.findIndex(x=>x.boxId===c.boxId);if(at>=0)DB.cards[at]=c;}state.ids=u.ids;state.choices=new Map(u.choices);state.checked=new Set(u.checked);state.undo=null;verifyDraft={boxId:'',cardId:'',query:''};refresh();verifyMessage('Dernier lot annulé. Les cartes sont à nouveau à vérifier.');}
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const d=b.dataset;if(d.vbMode){state.active=d.vbMode==='batch';verifyDraft={boxId:'',cardId:'',query:''};if(state.active&&!state.ids.length)fill();renderVerify();}
 if(d.vbChoice){const c=rawCard(d.vbBox),p=verifyCandidate(d.vbChoice);if(!c||!p)return;if(verifyDraft.boxId){verifyChooseCard(p.id);const text=document.getElementById('verifySelectionText');if(text)text.textContent='Carte sélectionnée : '+p.name+' · ID '+p.id;document.querySelectorAll('.vb-quick .vb-proposal').forEach(x=>{const on=x.dataset.vbChoice===String(p.id);x.classList.toggle('on',on);x.setAttribute('aria-pressed',String(on));});}else{state.choices.set(c.boxId,String(p.id));state.checked.delete(c.boxId);draw();}}
 if(d.vbEdit){verifySelectPosition(d.vbEdit);}if(b.id==='verifyBatchConfirm')commit();if(b.id==='verifyBatchUndo')undo();if(d.vbNext!==undefined){for(const id of state.ids)state.deferred.add(id);fill();draw();}if(d.vbReset!==undefined){state.deferred.clear();fill();draw();}});
document.addEventListener('change',e=>{if(e.target.dataset?.vbCheck){const id=e.target.dataset.vbCheck;if(e.target.checked&&state.choices.has(id))state.checked.add(id);else state.checked.delete(id);controls();}if(e.target.id==='vbSort'){state.sort=e.target.value;state.deferred.clear();fill();draw();}if(e.target.id==='vbAutoNext')state.autoNext=e.target.checked;});
window.DokkanVerifyBatch={state,proposals,commit,undo,canUndo};
})();
