/* Indexed search and small result pages keep typing and image decoding responsive. */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const collator=new Intl.Collator('fr');
const FILTER_KEY='dokkanos-verify-filters-v1',filterOptions={type:['AGI','TEC','INT','PUI','END'],class:['Super','Extrême'],rarity:['SSR','UR','LR']};
const filters={type:'',class:'',rarity:''},savedFilters=storedJSON(FILTER_KEY,{});
for(const key of Object.keys(filters))if(filterOptions[key].includes(savedFilters?.[key]))filters[key]=savedFilters[key];
const hasFilters=()=>Object.values(filters).some(Boolean);
const hasSearch=()=>!!verifyDraft.query.trim()||hasFilters();
function filterControls(host){if(document.getElementById('verifySearchFilters'))return;const panel=document.createElement('div');panel.id='verifySearchFilters';panel.className='verify-search-filters';panel.innerHTML=Object.entries({type:'Type',class:'Classe',rarity:'Rareté'}).map(([key,label])=>'<label for="verify'+key[0].toUpperCase()+key.slice(1)+'Filter">'+label+'<select id="verify'+key[0].toUpperCase()+key.slice(1)+'Filter" data-verify-search-filter="'+key+'"><option value="">'+(key==='class'?'Toutes les classes':key==='type'?'Tous les types':'Toutes les raretés')+'</option>'+filterOptions[key].map(v=>'<option value="'+esc(v)+'" '+(filters[key]===v?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label>').join('')+'<button type="button" id="verifyResetFilters">Effacer les filtres</button>';host.before(panel);}
function updateFilters(){storageWrite(FILTER_KEY,JSON.stringify(filters));verifySetQuery(verifyDraft.query);clearTimeout(timer);timer=null;renderVerifyResults();}

let index=null,timer=null,limit=12,lastRows=[],searchCache=new Map(),builds=0,scans=0;
const sameSource=()=>index&&index.catalog===CATALOG.cards&&index.meta===META.cards&&index.length===(CATALOG.cards||[]).length;
function start(){
 if(sameSource())return index;
 const current=index={catalog:CATALOG.cards,meta:META.cards,length:(CATALOG.cards||[]).length,ids:[...new Set((CATALOG.cards||[]).filter(c=>catalogSelectable(c)&&!c.isSellingOnly&&!c.nonPlayable).map(c=>String(c.id)))],at:0,rows:[],ready:false};searchCache.clear();builds++;
 schedule(()=>build(current));return current;
}
function schedule(fn){if(typeof requestIdleCallback==='function')requestIdleCallback(fn,{timeout:150});else setTimeout(fn,8);}
function add(current,id){const card=verifyCandidate(id);if(!card||!isPlayableCard(card))return;current.rows.push({card,hay:norm([card.id,card.name,card.title,card.rarity,card.type,card.class,...(card.categories||[])].join(' ')),name:norm(card.name||'')});}
function build(current){if(index!==current)return;const began=Date.now();let n=0;while(current.at<current.ids.length&&n++<60&&Date.now()-began<8)add(current,current.ids[current.at++]);if(current.at<current.ids.length){schedule(()=>build(current));return;}current.ready=true;if(hasSearch())renderVerifyResults();}
function readySync(){const current=start();while(current.at<current.ids.length)add(current,current.ids[current.at++]);current.ready=true;return current;}
verifyResults=function(){const raw=verifyDraft.query.trim(),q=norm(raw);if(!q&&!hasFilters())return [];const current=readySync(),key=JSON.stringify([raw,filters.type,filters.class,filters.rarity]); if(searchCache.has(key))return searchCache.get(key);const terms=q.split(/\s+/).filter(Boolean),out=[];scans++;for(const row of current.rows){if(filters.type&&row.card.type!==filters.type||filters.class&&row.card.class!==filters.class||filters.rarity&&row.card.rarity!==filters.rarity)continue;let score=q?0:1;for(const t of terms)if(row.hay.includes(t))score+=2;if(String(row.card.id)===raw)score+=200;if(q&&row.name.startsWith(q))score+=40;if(q&&row.hay.includes(q))score+=20;if(score>0)out.push({card:row.card,score});}out.sort((a,b)=>b.score-a.score||collator.compare(String(a.card.name||''),String(b.card.name||'')));const result=(q?out.slice(0,80):out).map(x=>x.card);searchCache.set(key,result);if(searchCache.size>24)searchCache.delete(searchCache.keys().next().value);return result;};
function show(rows,host){const slice=rows.slice(0,limit);host.innerHTML=slice.map(card=>{const stage=awakeningLabel(card,rows),id=esc(card.id);return '<label class="verify-result-row"><input type="radio" name="verify-card" value="'+id+'" '+(verifyDraft.cardId===String(card.id)?'checked':'')+'><img loading="lazy" decoding="async" width="64" height="80" src="'+esc(card.image||'')+'" alt="'+esc(card.name||'Carte '+card.id)+'" onerror="imageFallback(this,\''+id+'\',\'\')"><span><b>'+esc(card.name||'ID '+card.id)+(stage?' · '+stage:'')+'</b><small>'+esc([card.rarity||'',card.type||'','ID '+card.id].filter(Boolean).join(' · '))+'</small></span></label>';}).join('')||'<div class="empty compact">Aucune carte trouvée. Ajuste les filtres, le nom ou l’ID Dokkan.</div>';if(rows.length>limit)host.insertAdjacentHTML('beforeend','<button type="button" id="verifySearchMore" class="loadmore">Afficher '+Math.min(12,rows.length-limit)+' résultats de plus · '+Math.min(limit,rows.length)+' / '+rows.length+'</button>');host.setAttribute('aria-busy','false');}
renderVerifyResults=function(){const host=document.getElementById('verifyResults');if(!host)return;filterControls(host);if(!hasSearch()){host.innerHTML='<div class="verify-tip">Choisis un type, une classe ou une rareté pour afficher les cartes, ou saisis un nom / ID.</div>';host.setAttribute('aria-busy','false');lastRows=[];return;}const current=start();if(!current.ready){host.innerHTML='<div class="verify-tip" role="status">Préparation de la recherche…</div>';host.setAttribute('aria-busy','true');return;}lastRows=verifyResults();show(lastRows,host);};
verifySetQuery=function(value){clearTimeout(timer);verifyDraft.query=String(value||'');verifyDraft.cardId='';const confirm=document.getElementById('verifyConfirm');if(confirm)confirm.disabled=true;const selection=document.getElementById('verifySelectionText');if(selection)selection.textContent='Sélectionne une carte dans les résultats';limit=12;const host=document.getElementById('verifyResults');if(!hasSearch()){renderVerifyResults();return;}if(host){host.scrollTop=0;host.innerHTML='<div class="verify-tip" role="status">Recherche…</div>';host.setAttribute('aria-busy','true');}timer=setTimeout(()=>{timer=null;renderVerifyResults();},120);};
document.addEventListener('change',e=>{const key=e.target.dataset?.verifySearchFilter;if(key in filters){filters[key]=filterOptions[key].includes(e.target.value)?e.target.value:'';updateFilters();}});
document.addEventListener('click',e=>{if(e.target.closest?.('#verifyResetFilters')){for(const key of Object.keys(filters))filters[key]='';document.getElementById('verifySearchFilters')?.remove();updateFilters();return;}if(!e.target.closest?.('#verifySearchMore'))return;const host=document.getElementById('verifyResults');if(host){limit+=12;show(lastRows,host);}});
document.addEventListener('compositionstart',e=>{if(e.target.id==='verifyFinder')clearTimeout(timer);});
document.addEventListener('compositionend',e=>{if(e.target.id==='verifyFinder')verifySetQuery(e.target.value);});
window.addEventListener('dokkanos-data-ready',()=>{index=null;limit=12;start();});
window.DokkanVerifySearch={filters,ready:()=>start().ready,prepare:readySync,get metrics(){return {builds,scans,rows:index?.rows.length||0,cache:searchCache.size}},invalidate(){index=null;start();}};
})();
