/* One workshop across phone, card sheets and explicit combat records. */
(function(){'use strict';
const M=window.DokkanWorkbenchModel,E=window.DokkanTeamEngine,esc=teamEsc;
let prefs={version:1,goal:'balanced',compact:true,resumeMode:'classic',folds:{}},scheduled=false,restoring=false;
try{const raw=storageRead(M.key);if(raw)prefs=M.validate(JSON.parse(raw));}catch(e){console.warn('Préférences de l’atelier ignorées : sauvegarde invalide.');}
const clone=x=>JSON.parse(JSON.stringify(x)),node=html=>{const d=document.createElement('div');d.innerHTML=html;return d.firstElementChild;};
const save=()=>storageWrite(M.key,JSON.stringify(prefs));
const notice=s=>window.DokkanExperience?.notify(s);
const date=s=>s?new Date(s).toLocaleString('fr-FR'):'aucun export préparé';
function fold(panel,key,label,initial=false){
 if(!panel||panel.querySelector(':scope > [data-wb-fold]'))return;
 const d=document.createElement('details');d.dataset.wbFold=key;d.className='wb-fold';d.open=Object.hasOwn(prefs.folds,key)?prefs.folds[key]:initial;
 d.append(node('<summary>'+esc(label)+'</summary>'));while(panel.firstChild)d.append(panel.firstChild);panel.append(d);
 d.addEventListener('toggle',()=>{if(!d.isConnected||prefs.folds[key]===d.open)return;prefs.folds[key]=d.open;save();});
}
function currentEvaluation(){const cards=teamCards(),leader=E.combatCard(resolveCard(teamLeader),teamKitContext()),friend=teamFriend(leader),mission=teamMission(),context=teamContext();return {cards,leader,friend,mission,context,e:cachedTeamEvaluation(cards,leader,friend,mission,teamKnown(),context)};}
function diagnosticView(a){const d=M.diagnostic(E,a.cards,a.leader,a.friend,a.mission,teamKnown(),a.context,a.e);return '<section id="wbDiagnostic" class="wb-diagnostic"><div class="wb-heading"><h3>'+esc(d.verdict)+'</h3><span class="badge neutral">Diagnostic indicatif</span></div><div class="wb-diagnostic-grid"><div><h4>Points forts</h4><ul>'+d.strengths.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>'+(d.strengths.length?'':'<p>Prépare une composition pour voir ses points forts.</p>')+'</div><div><h4>Points à surveiller</h4><ul>'+d.risks.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>'+(d.risks.length?'':'<p>Aucune alerte structurelle détectée.</p>')+'</div></div><details><summary>Conditions importantes · '+d.conditions.length+'</summary><ul>'+d.conditions.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul><p>PV, Ki, attaques ennemies, accumulation et disponibilité des actives restent à vérifier au tour réel.</p></details><small>Les quotas, les kits et les protections connues sont évalués. Pas de dégâts précis ni de garantie de victoire.</small></section>';}
function rotationsView(a){
 if(!a.e.rotations.length)return '';
 const fixed=new Set(a.e.rotations.flatMap(r=>[r.a.boxId,r.b.boxId])),all=[...a.cards,...(a.friend?[a.friend]:[])];
 return '<section id="wbRotations"><h3>Mes rotations en un coup d’œil</h3><p class="muted">Deux tours consécutifs proposés, avec des flottants distincts. L’ordre de départ réel peut les décaler.</p>'+a.e.rotations.map((r,k)=>'<article class="wb-rotation"><h4>Rotation '+(k+1)+'</h4><div class="wb-slots">'+[r.a,r.b,r.third].filter(Boolean).map((c,i)=>{const row=[r.a,r.b,r.third].filter(Boolean),p=r.placements?.[i]||E.placementProfile(c,i+1,all,a.context,row),profile=E.passive(c,all,a.context),role=i===2?'Flottant':p.guaranteedProtection?'Protection avant attaque':E.supports(c,all).length>0?'Soutien':'Protection à vérifier';return '<div class="wb-slot '+(i===2?'wb-floater':'wb-fixed')+'"><span class="wb-slot-label">Position '+(i+1)+(i===2?' · flottant':' · duo fixe')+'</span><button data-team-open="'+esc(c.boxId)+'" aria-label="Voir '+esc(teamRotationName(c))+'">'+teamImage(c)+'<b>'+esc(teamRotationName(c))+'</b></button><small>'+esc(role)+'</small><small>Retour : normalement T+'+(i===2?3:2)+'</small></div>';}).join('')+'</div><p class="muted">'+r.links.length+' liens entre les deux membres du duo. '+(r.uncertain?'Premier slot : vérifie la protection avant l’attaque.':'Protection avant attaque détectée : vérifie ses conditions.')+'</p></article>').join('')+'<p class="wb-floaters"><b>Flottants qui circulent :</b> '+all.filter(c=>!fixed.has(c.boxId)).map(c=>esc(teamRotationName(c))).join(' · ')+'</p></section>';
}
function preferencesView(a){
 const configured=teamSettings.preferredDuo||[],goal=teamSettings.combat==='survival'?'security':teamSettings.combat==='short'?'speed':teamSettings.combat==='synergy'&&prefs.goal==='mission'?'mission':'balanced';
 return '<section id="wbPreferences"><h4>Mon objectif de génération</h4><div class="wb-goals">'+[['security','Sécurité','Protection et survie'],['speed','Rapidité','Dégâts pour un combat court'],['mission','Missions','Quotas sélectionnés et synergie']].map(([g,label,desc])=>'<button data-wb-goal="'+g+'" aria-pressed="'+(goal===g)+'" '+(teamBusy?'disabled':'')+'><b>'+label+'</b><small>'+desc+'</small></button>').join('')+'</div><p class="muted">Les contraintes des missions restent obligatoires dans les trois modes. Aucune réussite n’est déclarée par le générateur.</p><details><summary>Conserver mon duo préféré'+(configured.length?' · actif':'')+'</summary><form id="wbDuo"><div class="team-form">'+[0,1].map(i=>'<label>Carte '+(i+1)+'<select name="duo'+i+'">'+teamOption('','Choisir une carte',configured[i]||'')+a.cards.map(c=>teamOption(c.boxId,teamLabel(c),configured[i]||'')).join('')+'</select></label>').join('')+'</div><button '+(teamBusy?'disabled':'')+'>Conserver ces deux cartes</button>'+(configured.length?'<button type="button" data-wb-clear-duo '+(teamBusy?'disabled':'')+'>Retirer la préférence de duo</button>':'')+'<p class="muted">Les deux cartes sont verrouillées pour la recherche. Leur association en rotation est favorisée ; leurs protections et les contraintes du boss restent prioritaires à vérifier. Les autres verrous sont conservés.</p><p id="wbDuoStatus" role="status"></p></form></details></section>';
}
function historyView(){const entries=window.DokkanProgress?.state.history||[];return '<h3>Retrouver une ancienne composition</h3><p class="muted">Les versions automatiques sont locales. Restaurer une composition ne remplace ni ta Box, ni les missions, ni les profils réels. Exporte une sauvegarde complète pour protéger l’ensemble de tes données.</p>'+entries.slice(-8).reverse().map(h=>'<article class="wb-history-row"><div><b>'+esc(h.snapshot.objective||'Équipe libre')+'</b><small>'+esc(date(h.date))+' · '+h.snapshot.cards.length+' cartes</small><div class="wb-history-cards">'+h.snapshot.cards.map(c=>'<span>'+esc(c.name||verifyCandidate(c.id)?.name||c.id)+'</span>').join('')+'</div></div><button data-wb-preview-version="'+esc(h.id)+'">Voir / restaurer</button></article>').join('')+(entries.length?'':'<p>Aucune version automatique pour le moment. Les changements de ton équipe seront conservés après sa préparation.</p>')+'<div id="wbRestorePreview" role="status"></div>';}
function backupView(){const comp=storedJSON('dokkanos-companion-v1',{});return '<h3>Protéger ma Box vérifiée</h3><p>Dernier export préparé : <b>'+esc(date(comp.lastExport))+'</b>.</p><p class="muted">Vérifie que le fichier est bien enregistré dans Fichiers sur ton iPhone. Les versions locales seules ne protègent pas d’un effacement des données du navigateur.</p><button class="primary" data-c-export>Exporter toutes mes données</button><button data-c-tool="backup">Importer ou gérer une sauvegarde</button>';}
function teams(){
 const host=document.querySelector('#teams main');if(!host)return;const mode=host.dataset.teamMode||'classic';if(prefs.resumeMode!==mode&&document.body.dataset.view==='teams'){prefs.resumeMode=mode;save();}if(mode!=='classic'||host.querySelector('#wbCombatTop'))return;
 const a=currentEvaluation(),event=teamEvents.events.find(e=>e.id===teamSettings.event),stage=a.mission.stage,top=node('<section id="wbCombatTop" class="panel wb-combat-top"><div class="wb-heading"><div><span class="eyebrow">MON ATELIER DE COMBAT</span><h2>'+esc(stage?.name||event?.name||'Mon équipe libre')+'</h2></div><button data-wb-compact aria-pressed="'+prefs.compact+'">'+(prefs.compact?'Vue détaillée':'Vue compacte')+'</button></div><p>'+a.cards.length+'/6 cartes · '+esc(teamSettings.pool==='owned'?'Ma Box confirmée':'Catalogue · possession à vérifier')+' · '+(a.mission.missions?.length||Number(!!teamSettings.mission))+' mission(s) choisie(s)</p><div class="wb-actions"><button data-wb-objective>Changer l’objectif</button><button data-wb-result '+(a.cards.length!==6||teamBusy?'disabled':'')+'>Noter ce combat</button><button data-ux-scroll="teamAnalysis">Diagnostic et rotations</button></div><small>« Noter ce combat » conserve un instantané de cette composition avant de saisir ton résultat.</small></section>');host.querySelector('.team-heading')?.before(top);
 host.classList.toggle('wb-compact',prefs.compact);
 const composition=host.querySelector('#teamComposition');composition?.querySelector('.team-generation-options')?.before(node(preferencesView(a)));
 const analysis=host.querySelector('#teamAnalysis');if(analysis&&a.cards.length){analysis.querySelector('.team-section-title')?.after(node(diagnosticView(a)));analysis.querySelector('#wbDiagnostic')?.after(node(rotationsView(a)));}
 if(prefs.compact){fold(host.querySelector('#teamLeaderPanel'),'leader','Leader et catégorie · '+(a.leader?.name||'à choisir'),!a.leader);fold(host.querySelector('#teamSaved'),'saved','Mes équipes, résultats et sauvegardes');}
 const saved=host.querySelector('#teamSaved > details')||host.querySelector('#teamSaved');if(saved){const history=node('<details class="wb-history"><summary>Anciennes compositions et restauration</summary>'+historyView()+'</details>');saved.append(history);saved.append(node('<details class="wb-backup"><summary>Dernière sauvegarde et export</summary>'+backupView()+'</details>'));}
 if(teamSettings.replace)window.DokkanTeamUI?.openPartners();
}
function home(){
 const host=document.querySelector('#home main');if(!host)return;
 const f=window.DokkanFrontier?.getState(),b=window.DokkanBattlefield?.getState(),fs=f?.sessions?.[f.active],bs=b?.sessions?.[b.active],saved=teamSaved(),last=window.DokkanBattles?.rows().at(-1),frontier=window.DokkanFrontier?.getSummary?.(),battlefield=window.DokkanBattlefield?.getSummary?.(),comp=storedJSON('dokkanos-companion-v1',{});
 const signature=JSON.stringify([prefs.resumeMode,selectedTeam,teamSettings.event,teamSettings.eventStage,saved.map(s=>s.id),f,b,last?.id,comp.lastExport]);
 const old=host.querySelector('#wbHome');if(old?.dataset.signature===signature)return;
 const section=node('<section id="wbHome" class="panel ux-resume wb-home"><span class="eyebrow">REPRENDRE MON AVENTURE</span><h2>Mon prochain combat</h2><button class="primary" data-wb-resume="'+prefs.resumeMode+'">Reprendre '+({classic:'mon équipe',frontier:'Frontier',battlefield:'Battlefield'}[prefs.resumeMode])+'</button><div class="wb-mode-cards"><button data-wb-resume="classic"><b>Équipe classique</b><small>'+selectedTeam.length+'/6 cartes · '+esc(teamEvents.events.find(e=>e.id===teamSettings.event)?.name||'Objectif libre')+'</small></button><button data-wb-resume="frontier"><b>Frontier</b><small>'+esc(frontier?.label||'Choisir une case')+' · '+(frontier?.completed||0)+' case(s) gagnée(s)'+(fs?.board?' · tour '+fs.board.turn:'')+'</small></button><button data-wb-resume="battlefield"><b>Battlefield</b><small>'+esc(battlefield?.name||'Session en cours')+' · '+new Set((bs?.attempts||[]).filter(a=>a.result==='victory').map(a=>a.boss)).size+' combat(s) gagné(s) · '+Object.keys(bs?.reservePlan||{}).length+' secours</small></button></div>'+(last?'<p><b>Dernier combat noté :</b> '+esc(last.objective.eventName||'Équipe libre')+' · '+(last.result==='victory'?'victoire':'échec')+' · '+esc(date(last.date))+'</p><button data-battle-attempt-load="'+esc(last.id)+'">Reprendre l’équipe de ce combat</button>':'<p class="muted">Après ton combat, note le résultat pour retrouver les équipes qui fonctionnent.</p>')+'<details><summary>Mes compositions récentes · '+saved.length+'</summary>'+saved.slice(-3).reverse().map(s=>'<button class="wb-saved-shortcut" data-battle-review="'+esc(s.id)+'"><b>'+esc(s.name)+'</b><small>'+esc(s.objective?.eventName||'Équipe libre')+' · version '+(s.version||1)+'</small></button>').join('')+(saved.length?'':'<p>Sauvegarde une équipe pour la retrouver ici.</p>')+'</details><p class="wb-backup-note">Dernier export préparé : '+esc(date(comp.lastExport))+' <button data-c-tool="backup">Sauvegarder</button></p></section>');section.dataset.signature=signature;
 const target=old||host.querySelector('.ux-resume');if(target)target.replaceWith(section);else host.prepend(section);
}
function sheet(){
 const root=document.getElementById('sheet'),id=root?.dataset.cardId;if(!root?.classList.contains('on')||!id||root.querySelector('#wbCardProfile'))return;
 const c=verifyCandidate(id);if(!c)return;const p=window.DokkanProgress?.state.profiles[id],links=p?.links||{},actual=E.combatCard(c,{useZA:false,realProfiles:window.DokkanProgress?.state.profiles||{}}),all=teamCards().length?teamCards():[actual],profile=E.passive(actual,all,teamContext());
 const labels={unknown:'À renseigner',base:'Sans éveil Z',ztur:'Éveil Z TUR',zlr:'Éveil Z LR',superZtur:'Super éveil Z TUR',superZlr:'Super éveil Z LR'},known=Object.values(links).filter(Number.isFinite),potential=p?.potential??(rainbow100.has(id)?100:null),owned=ownedTeamCards().some(x=>E.identity(x)===id);
 const section=node('<section id="wbCardProfile" class="wb-card-profile"><h3>Ma carte en un coup d’œil</h3><div class="wb-card-kpis"><span><b>'+esc(owned?'Possédée':'À confirmer')+'</b>Box</span><span><b>'+esc(labels[p?.awakening]||'À renseigner')+'</b>Éveil réalisé</span><span><b>'+(potential===null?'?':potential+' %')+'</b>Potentiel réel</span><span><b>'+(p?.sa??'?')+'</b>Niveau ATT SP</span></div><p><b>Liens renseignés :</b> '+known.length+'/'+(c.links||[]).length+(known.length?' · moyenne des liens connus '+(known.reduce((a,b)=>a+b,0)/known.length).toFixed(1)+'/10':' · niveaux inconnus')+'</p><details><summary>Rôle et conditions de cette version</summary><p>'+esc(profile.roles.join(' · ')||'Rôle non confirmé')+'</p><p class="muted">Rôles détectés dans le kit '+esc(actual._kitLabel||'sélectionné')+'. Un rôle défensif ne garantit pas une protection avant l’attaque.</p>'+[1,2,3].map(i=>{const place=E.placementProfile(actual,i,all,teamContext());return '<p><b>Position '+i+'</b> · '+esc(place.summary.join(' '))+'</p>'+place.warnings.map(w=>'<small>'+esc(w)+'</small>').join('');}).join('')+'</details><button data-pilot="profiles" data-pilot-card="'+esc(id)+'">Renseigner cette carte en jeu</button></section>');root.querySelector('.hero')?.after(section);
 const progress=root.querySelector('[data-card-tab="progress"][aria-selected="true"]');if(progress){const content=root.querySelector('#cardSheetContent');if(content){content.prepend(node('<p class="muted">Les valeurs réelles et le rôle sont regroupés dans la fiche ci-dessus. Une valeur inconnue n’est pas supposée maximale.</p>'));const button=content.querySelector('[data-pilot="profiles"]');if(button)button.dataset.pilotCard=id;}}
}
function missionBatch(){
 const grid=document.querySelector('#eventDetail .event-missions'),batch=document.getElementById('wbMissionBatch');if(!grid)return;if(batch){if(batch.parentElement!==grid.parentElement)grid.before(batch);return;}const event=teamEvents.events.find(e=>e.id===eventSettings.selected),allowed=M.stageMissions(event,eventSettings.stage),ids=eventSettings.missions.filter(id=>allowed.some(m=>m.id===id));
 grid.before(node('<section id="wbMissionBatch" class="wb-mission-batch"><h4>Valider plusieurs missions ensemble</h4><p>Sélectionne les missions avec les cases de leur titre, puis confirme celles réellement réussies en jeu. La sélection sert aussi à préparer une équipe.</p><div class="wb-actions"><button data-wb-select-missions>Choisir toutes les missions restantes de ce niveau</button><button data-wb-clear-missions>Vider la sélection</button></div><p><b>'+ids.length+' mission(s) sélectionnée(s)</b> · la sélection est conservée entre les pages.</p><form id="wbBatchForm"><label class="team-checkbox"><input type="checkbox" name="confirmed" required> Le jeu a bien validé toutes les missions sélectionnées</label><label class="team-checkbox"><input type="checkbox" name="claimed"> Leurs récompenses ont aussi été récupérées</label><button class="primary" '+(!ids.length?'disabled':'')+'>Valider ces '+ids.length+' missions</button><p id="wbBatchStatus" role="status"></p></form>'+(eventBatchUndo?.event===event?.id?'<button data-wb-undo-missions>Annuler la dernière validation groupée</button>':'')+'</section>'));
}
function tools(){const content=document.querySelector('#toolContent');if(!content||!document.getElementById('backupFile')||content.querySelector('#wbBackupHistory'))return;content.append(node('<section id="wbBackupHistory">'+historyView()+'</section>'));}
function enhance(){const view=document.body.dataset.view;if(view==='teams')teams();if(view==='home')home();if(view==='events')missionBatch();if(view==='tools')tools();sheet();}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance();});}
const originalRender=renderTeam;renderTeam=function(){originalRender();teams();};
const originalEvents=renderEvents;renderEvents=function(){originalEvents();window.DokkanExperience?.enhance();missionBatch();};
function goal(value){if(teamBusy)return;if(!Object.hasOwn(M.goals,value))return;cancelTeamJob();prefs.goal=value;teamSettings.combat=value==='security'?'survival':value==='speed'?'short':'synergy';teamVariants=[];save();teamSaveSettings();teamStatusText='Priorité '+M.goals[value]+' choisie. Relance la génération pour comparer une nouvelle proposition ; aucune carte n’a été modifiée.';renderTeam();}
function showResult(){if(teamBusy||selectedTeam.length!==6)return;window.DokkanProgress?.checkpoint?.();const current=teamSaved().find(s=>s.id===teamSettings.savedSource),same=current&&JSON.stringify([current.cards,current.leader,current.objective])===JSON.stringify([selectedTeam,teamLeader,window.DokkanBattles.objective(teamSettings)]);if(!same){const next={id:Date.now()+'-'+Math.random().toString(36).slice(2,8),name:'Équipe · '+(teamMission().stage?.name||teamEvents.events.find(e=>e.id===teamSettings.event)?.name||'combat libre'),cards:[...selectedTeam],leader:teamLeader,settings:clone(teamSettings)};window.DokkanBattles.enrich(next,current);if(!storageWrite('dokkanos-saved-teams-v2',JSON.stringify([...teamSaved(),next]))){notice('Composition non sauvegardée : aucun résultat ajouté.');return;}teamSettings.savedSource=next.id;teamSaveSettings();}renderTeam();const panel=document.getElementById('teamSaved');if(panel.querySelector(':scope > details'))panel.querySelector(':scope > details').open=true;const form=[...panel.querySelectorAll('[data-battle-form]')].find(f=>f.dataset.battleForm===teamSettings.savedSource);if(form){form.closest('details').open=true;form.scrollIntoView({block:'start',behavior:'smooth'});}}
document.addEventListener('click',e=>{const button=e.target.closest?.('button');if(!button)return;const d=button.dataset;
 if(d.uxScroll){const target=document.getElementById(d.uxScroll),fold=target?.querySelector(':scope > [data-wb-fold]');if(fold)fold.open=true;}if(d.teamAction==='results'){const fold=document.querySelector('#teamSaved > [data-wb-fold]');if(fold)fold.open=true;}if(d.wbGoal)goal(d.wbGoal);
 if(d.wbCompact!==undefined){prefs.compact=!prefs.compact;save();renderTeam();}
 if(d.wbObjective!==undefined){const panel=document.getElementById('teamObjective');if(panel){panel.open=true;panel.scrollIntoView({block:'start',behavior:'smooth'});}}
 if(d.wbResult!==undefined)showResult();
 if(d.wbResume){prefs.resumeMode=d.wbResume;save();if(d.wbResume==='frontier')window.DokkanFrontier.open();else if(d.wbResume==='battlefield')window.DokkanBattlefield.open();else{switchView('teams');document.querySelector('[data-bf-mode="classic"]')?.click();}}
 if(d.wbClearDuo!==undefined&&!teamBusy){const duo=teamSettings.preferredDuo||[];teamSettings.locked=teamSettings.locked.filter(id=>!duo.includes(id)||!prefs.duoLocks?.includes(id));teamSettings.preferredDuo=[];delete prefs.duoLocks;save();teamSaveSettings();renderTeam();}
 if(d.wbPreviewVersion){const h=window.DokkanProgress?.state.history.find(h=>h.id===d.wbPreviewVersion),preview=document.getElementById('wbRestorePreview');if(h&&preview){preview.innerHTML='<section class="wb-restore-preview"><h4>Restaurer la composition du '+esc(date(h.date))+' ?</h4><p>'+h.snapshot.cards.map(c=>esc(c.name||c.id)).join(' · ')+'</p><p>Seules les cartes disponibles dans la source de cette version seront reprises. Tes kits actuels sont utilisés. Ta Box, tes missions et tes profils sont conservés.</p><button data-wb-restore-version="'+esc(h.id)+'">Restaurer cette composition</button><button data-wb-cancel-restore>Annuler</button></section>';preview.scrollIntoView({block:'nearest',behavior:'smooth'});}}
 if(d.wbCancelRestore!==undefined){const preview=document.getElementById('wbRestorePreview');if(preview)preview.textContent='';}
 if(d.wbRestoreVersion&&!restoring){window.DokkanProgress?.checkpoint?.();restoring=true;try{const h=window.DokkanProgress?.state.history.find(x=>x.id===d.wbRestoreVersion);if(h){const helper=node('<button data-progress-restore="'+esc(h.id)+'"></button>');document.body.append(helper);helper.click();helper.remove();notice('Ancienne composition reprise. Ta Box vérifiée est conservée.');}}finally{restoring=false;}}
 if(d.wbSelectMissions!==undefined){const event=teamEvents.events.find(e=>e.id===eventSettings.selected),state=eventAllProgress();eventSettings.missions=M.stageMissions(event,eventSettings.stage).filter(m=>!state[m.id]?.done).map(m=>m.id);eventSave();renderEvents();}
 if(d.wbClearMissions!==undefined){eventSettings.missions=[];eventSave();renderEvents();}
 if(d.wbUndoMissions!==undefined){try{eventUndoBatch();renderEvents();notice('Validation groupée annulée ; les autres missions sont conservées.');}catch(error){notice(error.message);}}
});
document.addEventListener('submit',e=>{
 if(e.target.id==='wbDuo'){e.preventDefault();if(teamBusy)return;const form=e.target,duo=[...form.querySelectorAll('select')].map(n=>n.value);if(duo.length!==2||duo.some(id=>!selectedTeam.includes(id))||duo[0]===duo[1]){form.querySelector('#wbDuoStatus').textContent='Choisis deux cartes distinctes de ton équipe.';return;}const previous=teamSettings.preferredDuo||[],added=prefs.duoLocks||[];teamSettings.locked=teamSettings.locked.filter(id=>!previous.includes(id)||!added.includes(id));prefs.duoLocks=duo.filter(id=>!teamSettings.locked.includes(id));teamSettings.preferredDuo=duo;teamSettings.locked=[...new Set([...teamSettings.locked,...duo])];cancelTeamJob();teamVariants=[];save();teamSaveSettings();renderTeam();notice('Duo conservé pour la recherche. Les autres verrous sont inchangés.');}
 if(e.target.id==='wbBatchForm'){e.preventDefault();const form=e.target;if(!form.querySelector('[name=confirmed]').checked){form.querySelector('#wbBatchStatus').textContent='Confirme d’abord que le jeu a validé ces missions.';return;}try{const count=eventConfirmMissions(eventSettings.selected,eventSettings.missions,{stage:eventSettings.stage,claimed:form.querySelector('[name=claimed]').checked});renderEvents();notice(count+' missions validées ensemble.');}catch(error){form.querySelector('#wbBatchStatus').textContent=error.message;}}
});
window.addEventListener('dokkanos-view-change',enhance);window.addEventListener('dokkanos-sheet-render',sheet);window.addEventListener('dokkanos-data-ready',schedule);window.addEventListener('dokkanos-events-loaded',schedule);
window.addEventListener('dokkanos-state-change',schedule);
const observer=new MutationObserver(records=>{if(records.some(r=>!r.target.closest?.('#wbHome,#wbCardProfile,#wbCombatTop,#wbDiagnostic,#wbPreferences,#wbMissionBatch,#wbBackupHistory,#wbRestorePreview')))schedule();});document.querySelectorAll('#home,#teams,#events,#tools,#sheet').forEach(root=>observer.observe(root,{childList:true,subtree:true}));
window.DokkanWorkbench={enhance,preferences:()=>clone(prefs),diagnostic:()=>{const a=currentEvaluation();return M.diagnostic(E,a.cards,a.leader,a.friend,a.mission,teamKnown(),a.context,a.e);}};enhance();
})();
