/* Readable preparation, explicit feedback and scoped mission batches. */
(function(root){'use strict';
const key='dokkanos-workbench-v1',record=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const goals={balanced:'Équilibrée',security:'Sécurité',speed:'Rapidité',mission:'Réussir les missions'};
const causes={before:'Mort avant ma spéciale',damage:'Dégâts insuffisants',ki:'Manque de Ki',locks:'Positions verrouillées',build:'Montée en puissance trop lente',conditions:'Conditions du passif non remplies'};
function validate(x){if(!record(x)||x.version!==1||!Object.hasOwn(goals,x.goal)||typeof x.compact!=='boolean'||!['classic','frontier','battlefield'].includes(x.resumeMode)||!record(x.folds)||x.duoLocks!==undefined&&(!Array.isArray(x.duoLocks)||x.duoLocks.length>2||x.duoLocks.some(id=>typeof id!=='string'||id.length>120))||Object.keys(x.folds).length>20||Object.entries(x.folds).some(([k,v])=>!/^[-a-z]{1,40}$/.test(k)||typeof v!=='boolean'))throw Error('Préférences de l’atelier invalides.');return x;}
function stageMissions(event,stageId=''){const stage=(event?.stages||[]).find(s=>String(s.id)===String(stageId));if(stageId&&!stage)return [];return (event?.missions||[]).filter(m=>!stage||(!m.stageId&&!m.stageNumber)||String(m.stageId)===String(stage.id)||m.stageNumber===stage.number);}
function batch(event,stageId,ids,progress={},claimed=false){const allowed=new Map(stageMissions(event,stageId).map(m=>[m.id,m]));if(!Array.isArray(ids)||!ids.length||ids.length>1000||ids.some(id=>typeof id!=='string'||!allowed.has(id)))throw Error('Sélectionne des missions appartenant à cet événement et à ce niveau.');const next=JSON.parse(JSON.stringify(progress));for(const id of new Set(ids)){const previous=next[id]||{};next[id]={done:true,claimed:claimed||previous.done===true&&previous.claimed===true};}return next;}
function diagnostic(E,cards,leader,friend,mission,known,context,evaluation){const e=evaluation||E.evaluate(cards,leader,friend,mission,known,context),strengths=[],risks=[],conditions=[];const covered=e.cover.filter(c=>c.covered).length,anchors=(e.profiles||[]).filter(p=>p.slot1>=32).length;
 if(cards.length!==6)risks.push('Composition incomplète : '+cards.length+'/6 cartes.');
 if(covered<cards.length)risks.push((cards.length-covered)+' carte(s) hors leader ou couverture inconnue.');else if(cards.length)strengths.push('Toutes les cartes bénéficient du leader sélectionné.');
 if(e.check.deficit)risks.push('Des quotas de mission ne sont pas remplis.');else if((mission.requirements||[]).length)strengths.push('Les quotas de composition sélectionnés sont remplis ; les actions en jeu restent à réaliser.');
 if(e.check.unknown)conditions.push('Des contraintes de mission ne peuvent pas être vérifiées automatiquement : consulte leur description dans le jeu.');
 if(anchors>=2)strengths.push('Au moins deux profils défensifs pour la première position sont détectés.');else if(cards.length===6)risks.push('Moins de deux profils solides pour la première position : surveille les rotations de départ.');
 if(e.synergy.linkTotal)strengths.push(e.synergy.linkTotal+' liens partagés dans la composition ; ils ne sont pas tous actifs simultanément.');
 const partial=e.profiles.filter(p=>!p.complete).length;if(partial)risks.push(partial+' fiche(s) incomplète(s) : évaluation moins certaine.');
 for(const r of e.rotations){const row=[r.a,r.b,r.third].filter(Boolean);row.forEach((c,i)=>{const p=r.placements?.[i]||E.placementProfile(c,i+1,[...cards,...(friend?[friend]:[])],context,row);if(i===0&&!p.guaranteedProtection)risks.push(c.name+' : protection avant sa propre attaque à confirmer.');conditions.push(...p.warnings.map(w=>c.name+' : '+w));});}
 if(context.boss?.locks)conditions.push('Le boss peut verrouiller les positions : le placement proposé peut devenir impossible.');
 if(context.disableDodge)conditions.push('Esquive désactivée : ne compte pas sur elle pour protéger la rotation.');
 if(!context.boss?.available)conditions.push('Profil du boss partiel ou absent : vérifie les restrictions dans le jeu.');
 return {evaluation:e,strengths:[...new Set(strengths)],risks:[...new Set(risks)],conditions:[...new Set(conditions)],verdict:e.check.deficit||covered<cards.length||cards.length!==6?'À ajuster avant le combat':e.check.unknown?'Conditions de mission à vérifier':'Composition prête à tester',uncertain:partial>0||e.check.unknown};
}
function advice(selected=[]){const texts={before:'Teste une protection active avant l’attaque en première position ; ne confonds pas DÉF après spéciale et protection de départ.',damage:'Vérifie l’ATT SP, les bonus réellement reçus du leader et l’avantage de type. Essaie la priorité Rapidité si le combat est court.',ki:'Examine les liens de Ki et les soutiens actifs sur la rotation réelle, puis les sphères disponibles. Un lien partagé ailleurs dans l’équipe ne suffit pas.',locks:'Prévois une carte capable d’encaisser dans la position imposée ; le plan de rotations ne peut pas annuler un verrouillage ennemi.',build:'Pour un départ dangereux, privilégie les protections immédiates. Les bonus après plusieurs attaques ou apparitions ne sont pas disponibles au tour 1.',conditions:'Relis les conditions de PV, de partenaires, de tour et de transformation. Renseigne aussi les éveils réellement réalisés.'};return [...new Set(selected)].filter(k=>Object.hasOwn(texts,k)).map(k=>({cause:k,title:causes[k],detail:texts[k],goal:k==='damage'?'speed':['before','build'].includes(k)?'security':null}));}
const API={key,goals,causes,validate,stageMissions,batch,diagnostic,advice};if(typeof module!=='undefined')module.exports=API;root.DokkanWorkbenchModel=API;
})(typeof window!=='undefined'?window:globalThis);
