const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
fs.mkdirSync('audit-artifacts',{recursive:true});const report={checks:[],errors:[]};
async function go(page,id){const b=page.locator('nav [data-v="'+id+'"]');if(!await b.isVisible())await page.locator('#moreNav').click();await b.click();await page.locator('#'+id+'.on').waitFor();}
async function tool(page,id){await page.evaluate(id=>window.DokkanCopilot.open(id),id);await page.locator('#pilotWork').waitFor();await page.waitForTimeout(250);}
(async()=>{const browser=await chromium.launch({headless:true});try{for(const width of [390,1280]){
const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true,serviceWorkers:'allow'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++});await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});if(navigations<2)await page.waitForEvent('framenavigated',{predicate:f=>f===page.mainFrame(),timeout:60000});await page.waitForFunction(()=>navigator.serviceWorker.controller&&document.querySelector('#home .companion-welcome'),null,{timeout:60000});
await go(page,'box');assert.equal(await page.locator('#grid .unit').count(),80);await page.locator('#boxMore').click();assert.equal(await page.locator('#grid .unit').count(),160);
await go(page,'teams');await page.locator('#teamLeaderSearch').fill('1034201');await page.locator('#teamLeaderResults [data-team-leader="1034201"]').click();if(await page.locator('[data-team-own-leader="1034201"]').count())await page.locator('[data-team-own-leader="1034201"]').click();await page.locator('#autoTeam').click();await page.waitForFunction(()=>document.querySelector('#teamCount').textContent==='6/6'&&!document.querySelector('#autoTeam').disabled,null,{timeout:60000});await page.locator('#teams [data-pilot="guide"]').click();await page.locator('#copilot.on').waitFor();assert((await page.locator('#pilotWork').innerText()).includes('Premières apparitions'));assert.equal(await page.locator('#pilotWork .team-rotation').count(),2);
for(const id of ['guide','passives','equipment','farm','review','missing','share','performance']){await tool(page,id);const sizes=await page.evaluate(()=>[innerWidth,document.documentElement.scrollWidth]);assert(sizes[1]<=sizes[0]+2,id+' overflow');await page.screenshot({path:'audit-artifacts/copilot-'+id+'-'+width+'.png'});}
await tool(page,'passives');await page.locator('#pilotCard').selectOption('1034201');assert((await page.locator('#pilotWork').innerText()).includes('Vérifie le ki'));
await tool(page,'equipment');await page.locator('#pilotEquipment [name="additional"]').fill('25');await page.locator('#pilotEquipment [name="critical"]').fill('10');await page.locator('#pilotEquipment button').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('dokkanos-copilot-v1')).equipment['1034201'].additional),'25');
await tool(page,'farm');await page.evaluate(()=>window.DokkanCopilot.open('farm','1003211'));await page.locator('#farmVersion').selectOption('ztur');assert((await page.locator('#pilotWork').innerText()).includes('Besoin : 15'));await page.locator('[data-farm-have]').first().fill('5');await page.locator('[data-farm-have]').first().dispatchEvent('change');assert((await page.locator('#pilotWork').innerText()).includes('10 à obtenir'));await page.locator('#farmResource [name="name"]').fill('Ressource personnelle');await page.locator('#farmResource [name="need"]').fill('20');await page.locator('#farmResource [name="have"]').fill('6');await page.locator('#farmResource button').click();assert((await page.locator('#pilotWork').innerText()).includes('14 à obtenir'));
await tool(page,'review');await page.locator('#pilotReview [name="turn"]').fill('9');await page.locator('#pilotReview [name="notes"]').fill('<script>texte uniquement</script>');await page.locator('#pilotReview button').click();assert.equal(await page.locator('.pilot-review-list script').count(),0);assert((await page.locator('.pilot-review-list').innerText()).includes('<script>texte uniquement</script>'));
await tool(page,'missing');await page.locator('[data-pilot-action="missing"]').click();await page.waitForFunction(()=>document.querySelector('#pilotStatus').textContent.includes('Comparaison terminée'),null,{timeout:120000});assert((await page.locator('#pilotWork').innerText()).includes('Alternatives déjà possédées'));await page.screenshot({path:'audit-artifacts/copilot-missing-result-'+width+'.png'});
await tool(page,'multi');await page.evaluate(async()=>{await ensureEvents();teamEvents.events.push({id:'audit-copilot',name:'Mission de contrôle',kind:'Défi',permanent:true,stages:[{id:'1',number:1,name:'Niveau 1',requirements:[]},{id:'2',number:2,name:'Niveau 2',requirements:[]}],missions:[{id:'audit-a',title:'Au moins un INT',stageNumber:1,requirements:[{kind:'type',value:'INT',count:1}],rewards:[]},{id:'audit-b',title:'Au moins un Saga de Boo',stageNumber:1,requirements:[{kind:'category',value:'Saga de Boo',count:1}],manualCheck:true,rewards:[]},{id:'audit-other-stage',title:'Ne pas mélanger les niveaux',stageNumber:2,requirements:[],rewards:[]}]});window.DokkanCopilot.render();});await page.locator('#multiEvent').selectOption('audit-copilot');assert.equal(await page.locator('[data-pilot-mission="audit-other-stage"]').count(),0);await page.locator('[data-pilot-action="pickMissions"]').click();await page.locator('[data-pilot-action="multi"]').click();await page.waitForFunction(()=>document.querySelector('#pilotStatus').textContent.includes('Recherche terminée'),null,{timeout:180000});assert.equal(await page.locator('[data-pilot-load-multi]').count(),1);assert.equal(await page.evaluate(()=>eventProgress['audit-a']?.done||false),false);await page.screenshot({path:'audit-artifacts/copilot-multi-'+width+'.png'});
await tool(page,'share');const [file]=await Promise.all([page.waitForEvent('download'),page.locator('[data-pilot-action="shareFile"]').click()]);await file.saveAs('/tmp/pilot-fiche-'+width+'.txt');assert(fs.readFileSync('/tmp/pilot-fiche-'+width+'.txt','utf8').includes('Rotation 1'));const [codeFile]=await Promise.all([page.waitForEvent('download'),page.locator('[data-pilot-action="shareCode"]').click()]);await codeFile.saveAs('/tmp/pilot-code-'+width+'.json');const code=fs.readFileSync('/tmp/pilot-code-'+width+'.json','utf8'),before=await page.evaluate(()=>localStorage.getItem('dokkanos-inventory'));await page.locator('#pilotImportTeam textarea').fill('{"format":"wrong"}');await page.locator('#pilotImportTeam button').click();assert.equal(await page.locator('[data-pilot-action="importTeam"]').count(),0);await page.locator('#pilotImportTeam textarea').fill(code);await page.locator('#pilotImportTeam button').click();assert.equal(await page.locator('[data-pilot-action="importTeam"]').count(),1);await page.locator('[data-pilot-action="importTeam"]').click();assert.equal(await page.evaluate(()=>localStorage.getItem('dokkanos-inventory')),before);assert.equal(await page.locator('#teamCount').innerText(),'6/6');
await tool(page,'capture');const cat=JSON.parse(fs.readFileSync('catalog.json')),imageCard=cat.cards.find(c=>c.id==='1000010');await page.locator('#pilotCaptureFile').setInputFiles(imageCard.image);await page.locator('#pilotCaptureGrid button').click();await page.locator('[data-pilot-capture-choice]').first().waitFor({timeout:60000});assert.equal(await page.evaluate(()=>localStorage.getItem('dokkanos-inventory')),before);assert(await page.locator('[data-pilot-capture-id="1000010"]').count()>0,'exact reference image not among candidates');await page.locator('[data-pilot-capture-id="1000010"]').first().click();await page.locator('[data-pilot-capture-confirm]').first().click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('dokkanos-inventory'))['1000010']),'owned');await page.screenshot({path:'audit-artifacts/copilot-capture-'+width+'.png'});
await tool(page,'performance');await page.locator('#pilotPerformance').selectOption('full');await go(page,'box');assert(await page.locator('#grid .unit').count()>160);await tool(page,'performance');await page.locator('#pilotPerformance').selectOption('fast');await go(page,'box');assert.equal(await page.locator('#grid .unit').count(),80);await tool(page,'performance');await page.locator('[data-pilot-action="storage"]').click();assert((await page.locator('#pilotStorage').innerText()).includes('Mo'));
await page.reload();await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});await tool(page,'equipment');await page.locator('#pilotCard').selectOption('1034201');assert.equal(await page.locator('#pilotEquipment [name="additional"]').inputValue(),'25');await tool(page,'farm');await page.evaluate(()=>window.DokkanCopilot.open('farm','1003211'));assert((await page.locator('#pilotWork').innerText()).includes('Ressource personnelle'));
await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});await tool(page,'guide');assert.equal(await page.locator('#pilotWork .team-rotation').count(),2);await tool(page,'review');assert(await page.locator('.pilot-review-list .plan-card').count()>0);assert.deepEqual(errors,[]);report.checks.push({width,guide:true,passives:true,equipment:true,multiSameStage:true,farming:true,reviewEscaping:true,missingCards:true,visualRecognition:true,explicitCaptureConfirmation:true,shareImport:true,performance:true,persistence:true,offline:true});await context.close();
}}catch(e){report.errors.push(e.stack||String(e));process.exitCode=1;}finally{await browser.close();fs.writeFileSync('audit-artifacts/copilot-report.json',JSON.stringify(report,null,2));console.log('COPILOT_AUDIT '+JSON.stringify(report));}})();
