const fs=require('fs'),assert=require('node:assert/strict'),{chromium,webkit,devices}=require('playwright');fs.mkdirSync('audit-artifacts',{recursive:true});
(async()=>{for(const scenario of [{name:'desktop',engine:chromium,settings:{viewport:{width:1280,height:900}}},{name:'iphone-12',engine:webkit,settings:devices['iPhone 12']}]){const browser=await scenario.engine.launch();try{
 const context=await browser.newContext(scenario.settings),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>performance.getEntriesByType('navigation')[0]?.type==='reload'&&navigator.serviceWorker.controller&&document.querySelector('#grid .unit')&&window.DokkanWorkbench,null,{timeout:90000});
 await p.evaluate(async()=>{await ensureEvents();await teamBossReady;teamSettings.pool='owned';teamSettings.useZA=false;chooseTeamLeader(TE.identity(teamOwnedCards().find(c=>c.leader)));switchView('teams');await autoBuildTeam(true);});await p.waitForFunction(()=>!teamBusy&&selectedTeam.length===6,null,{timeout:150000});
 const before=await p.evaluate(()=>[localStorage.getItem('dokkanos-inventory'),localStorage.getItem('dokkanos-team'),localStorage.getItem('dokkanos-team-leader')]);
 assert.equal(await p.locator('.wb-slot .visual-card').count(),6);assert.equal(await p.locator('.wb-slot .visual-card-type').count(),6);assert.equal(await p.locator('.wb-slot .visual-card-rarity').count(),6);assert.equal(await p.locator('.visual-rotation-details').count(),2);assert.equal(await p.locator('.visual-rotation-details[open]').count(),0);
 assert(await p.locator('.wb-slot .visual-card img').first().evaluate(n=>getComputedStyle(n).objectFit==='contain'));await p.locator('.visual-rotation-details summary').first().click();assert(await p.locator('.visual-rotation-details[open]').first().isVisible());
 await p.locator('#wbRotations').screenshot({path:'audit-artifacts/visual-rotations-'+scenario.name+'.png',animations:'disabled'});await p.locator('#teamComposition').screenshot({path:'audit-artifacts/visual-composition-'+scenario.name+'.png',animations:'disabled'});
 await p.evaluate(()=>DokkanExperience.notify('Équipe sauvegardée. Tes cartes et les missions sont conservées.',true));const toast=await p.locator('#uxToast').boundingBox(),nav=await p.locator('.app-nav').boundingBox();assert(toast.height<=160);if(scenario.name==='iphone-12'){assert(toast.y+toast.height<nav.y);const metrics=await p.locator('.app-header').evaluate(n=>({height:n.getBoundingClientRect().height,paddingTop:parseFloat(getComputedStyle(n).paddingTop),children:[...n.querySelectorAll('.brand,.brand-home,.header-context,#uxBack,#openGlobalSearch')].map(x=>({class:x.className,id:x.id,height:x.getBoundingClientRect().height,width:x.getBoundingClientRect().width,padding:getComputedStyle(x).padding})),styles:[...document.styleSheets].map(s=>s.href)}));console.log(JSON.stringify({profile:scenario.name,header:metrics}));assert(metrics.height-(metrics.paddingTop-6)<=70,'Compact iPhone header excluding safe area');assert(await p.locator('#uxBack').isVisible());assert(await p.locator('#uxBack').evaluate(n=>n.getBoundingClientRect().height>=44));}
 assert.equal(await p.locator('#uxToast').getAttribute('aria-atomic'),'true');assert.equal(await p.locator('#uxToast').getAttribute('data-tone'),'success');await p.locator('[data-ux-toast-close]').click();assert(await p.locator('#uxToast').isHidden());
 await p.evaluate(()=>switchView('home'));await p.locator('#wbHome').screenshot({path:'audit-artifacts/visual-home-'+scenario.name+'.png',animations:'disabled'});assert.equal(await p.locator('#home').evaluate(n=>getComputedStyle(n).opacity),'1');
 for(const view of ['home','teams','events','catalog']){await p.evaluate(view=>switchView(view),view);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),view+' horizontal overflow');}
 for(const mode of ['frontier','battlefield']){await p.evaluate(mode=>mode==='frontier'?DokkanFrontier.open():DokkanBattlefield.open(),mode);await p.locator('#teams main > .panel').first().screenshot({path:'audit-artifacts/visual-'+mode+'-'+scenario.name+'.png',animations:'disabled'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),mode+' overflow');}
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>switchView('home'));assert.equal(await p.locator('.view.on').evaluate(n=>getComputedStyle(n).animationName),'none');assert.deepEqual(await p.evaluate(()=>[localStorage.getItem('dokkanos-inventory'),localStorage.getItem('dokkanos-team'),localStorage.getItem('dokkanos-team-leader')]),before);assert.deepEqual(errors,[]);console.log(JSON.stringify({profile:scenario.name,framedCards:true,actualBadges:true,compactHeader:true,compactToast:true,foldedRotations:true,linkChips:true,noBlankTransition:true,reducedMotion:true,noOverflow:true,boxAndTeamUnchanged:true}));await context.close();
 }finally{await browser.close();}}})().catch(e=>{console.error(e);process.exitCode=1});
