const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
fs.mkdirSync('audit-artifacts',{recursive:true});
async function go(page,id){const b=page.locator('nav [data-v="'+id+'"]');if(!await b.isVisible())await page.locator('#moreNav').click();await b.click();await page.locator('#'+id+'.on').waitFor();}
async function tab(page,id){await page.locator('[data-c-tool="'+id+'"]').first().click();await page.locator('#toolTab-'+id+'[aria-selected="true"]').waitFor();}
const report={checks:[],errors:[]};
(async()=>{const browser=await chromium.launch({headless:true});try{for(const width of [390,1280]){
 const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true,serviceWorkers:'allow'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++});await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});if(navigations<2)await page.waitForEvent('framenavigated',{predicate:f=>f===page.mainFrame(),timeout:60000});await page.waitForFunction(()=>navigator.serviceWorker.controller&&document.querySelector('#home .companion-welcome'),null,{timeout:60000});
 await page.locator('#openGlobalSearch').click();await page.locator('#globalSearchInput').fill('Saga de Boo');await page.locator('#globalResults [data-c-category]').first().waitFor();assert(await page.locator('#globalResults [data-c-card]').count()>0);await page.locator('#globalResults [data-c-category]').first().click();await page.locator('#catalog.on').waitFor();assert.equal(await page.locator('#missingQuery').inputValue(),'Saga de Boo');
 await go(page,'teams');await page.locator('#teamLeaderSearch').fill('1034201');await page.locator('#teamLeaderResults [data-team-leader="1034201"]').click();await page.locator('[data-team-own-leader="1034201"]').click();await page.locator('#autoTeam').click();await page.waitForFunction(()=>document.querySelector('#teamCount').textContent==='6/6'&&!document.querySelector('#autoTeam').disabled,null,{timeout:60000});await page.locator('#teamName').fill('Équipe test compagnon');await page.locator('[data-team-action="save"]').click();await page.locator('[data-c-pin-team]').last().click();await go(page,'home');assert((await page.locator('#home').innerText()).includes('Équipe test compagnon'));await page.screenshot({path:'audit-artifacts/companion-home-'+width+'.png'});
 await go(page,'teams');await page.locator('[data-team-replace]').first().click();await page.locator('.replacement-changes').first().waitFor();assert((await page.locator('.replacement-changes').first().innerText()).length>20);await page.locator('[data-team-action="cancelReplace"]').click();
 await go(page,'tools');await tab(page,'diagnostic');assert((await page.locator('#toolContent').innerText()).includes('6/6'));await page.screenshot({path:'audit-artifacts/companion-diagnostic-'+width+'.png'});await tab(page,'compare');await page.locator('[data-c-compare="compareB"]').selectOption({label:'Équipe test compagnon'});assert.equal(await page.locator('.compare-table tbody tr').count(),8);await page.screenshot({path:'audit-artifacts/companion-compare-'+width+'.png'});
 await tab(page,'journal');await page.locator('#journalName').fill('Combat de test');await page.locator('#journalNotes').fill('Rotation efficace <script>ne doit pas exécuter</script>');await page.locator('#journalForm button[type="submit"]').click();assert((await page.locator('.journal-list').innerText()).includes('<script>ne doit pas exécuter</script>'));assert.equal(await page.locator('.journal-list .mini-roster img').count(),6);await page.screenshot({path:'audit-artifacts/companion-journal-'+width+'.png'});
 await tab(page,'plan');const check=page.locator('[data-c-task]').first(),id=await check.getAttribute('data-c-task'),field=await check.getAttribute('data-c-field');await check.check();assert(await page.evaluate(({id,field})=>JSON.parse(localStorage.getItem('dokkanos-companion-v1')).tasks[id][field],{id,field}));await page.locator('[data-c-reset-plan]').click();assert.equal(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('dokkanos-companion-v1')).tasks).length),0);await page.screenshot({path:'audit-artifacts/companion-plan-'+width+'.png'});
 await go(page,'box');await page.locator('#search').fill('goku');await page.locator('.box-filter-panel summary').click();await page.locator('#rarityFilter').selectOption('LR');await page.reload();await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});assert.equal(await page.locator('#search').inputValue(),'goku');assert.equal(await page.locator('#rarityFilter').inputValue(),'LR');
 await go(page,'tools');await tab(page,'freshness');assert((await page.locator('#toolContent').innerText()).includes('4494'));await page.screenshot({path:'audit-artifacts/companion-freshness-'+width+'.png'});await tab(page,'backup');
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-c-export]').click()]);const backupPath='/tmp/companion-backup-'+width+'.json';await download.saveAs(backupPath);const payload=JSON.parse(fs.readFileSync(backupPath));assert(payload.entries['dokkanos-journal-v1']);assert(payload.entries['dokkanos-box-filters-v1']);
 const before=await page.evaluate(()=>localStorage.getItem('dokkanos-inventory'));await page.locator('#backupFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"wrong"}')});await page.waitForFunction(()=>document.querySelector('#companionStatus').textContent.includes('compatible'));assert.equal(await page.evaluate(()=>localStorage.getItem('dokkanos-inventory')),before);
 await page.evaluate(()=>localStorage.setItem('dokkanos-inventory','{"1003211":"owned"}'));await page.locator('#backupFile').setInputFiles(backupPath);await page.locator('[data-c-restore]').waitFor();await page.screenshot({path:'audit-artifacts/companion-backup-'+width+'.png'});await Promise.all([page.waitForEvent('download'),page.waitForEvent('framenavigated',{predicate:f=>f===page.mainFrame()}),page.locator('[data-c-restore]').click()]);await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});assert.equal(await page.evaluate(()=>localStorage.getItem('dokkanos-inventory')),payload.entries['dokkanos-inventory']);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('dokkanos-journal-v1')).length),1);
 await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#home .companion-welcome')&&document.querySelector('#grid .unit'),null,{timeout:60000});await go(page,'tools');await tab(page,'journal');assert.equal(await page.locator('.journal-list .plan-card').count(),1);await page.locator('#openGlobalSearch').click();await page.locator('#globalSearchInput').fill('Équipe test compagnon');await page.locator('#globalResults [data-c-load-team]').waitFor();await page.locator('#closeGlobalSearch').click();
 for(const route of ['home','tools']){await go(page,route);const sizes=await page.evaluate(()=>[innerWidth,document.documentElement.scrollWidth]);assert(sizes[1]<=sizes[0]+2);}assert.deepEqual(errors,[]);report.checks.push({width,globalSearch:true,pinnedTeam:true,replacementDeltas:true,diagnostic:true,comparison:true,journalEscaping:true,planTracking:true,filterMemory:true,freshness:true,backupExport:true,invalidImportRejected:true,restoreRoundTrip:true,offline:true});await context.close();
 }}catch(e){report.errors.push(e.stack||String(e));process.exitCode=1;}finally{await browser.close();fs.writeFileSync('audit-artifacts/companion-report.json',JSON.stringify(report,null,2));console.log('COMPANION_AUDIT '+JSON.stringify(report));}})();
