const fs=require('fs'),assert=require('node:assert/strict'),{chromium,webkit,devices}=require('playwright');fs.mkdirSync('audit-artifacts',{recursive:true});
(async()=>{for(const config of [{name:'desktop',engine:chromium,options:{viewport:{width:1280,height:900}}},{name:'iphone-webkit',engine:webkit,options:devices['iPhone 13']}]){const browser=await config.engine.launch();try{const ctx=await browser.newContext(config.options),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>navigator.serviceWorker.controller&&window.DokkanBattlefield&&typeof teamOwnedCards==='function'&&teamOwnedCards().length>0,null,{timeout:90000});await p.evaluate(async()=>{await window.DokkanBattlefield.ready;await teamBossReady;window.DokkanBattlefield.open();});
 const before=await p.evaluate(()=>({inventory:localStorage.getItem('dokkanos-inventory'),edits:localStorage.getItem('dokkanos-edits'),team:JSON.stringify(selectedTeam),leader:teamLeader}));
 await p.evaluate(()=>{window.bfFrames=[];let last=performance.now();window.bfTracking=true;function frame(t){if(!window.bfTracking)return;window.bfFrames.push(t-last);last=t;requestAnimationFrame(frame);}requestAnimationFrame(frame);});
 const start=Date.now();await p.locator('[data-bf-action="generate"]').click();await p.waitForFunction(()=>!document.querySelector('[data-bf-action="cancel"]')&&Object.keys(window.DokkanBattlefield.getState().sessions['global-109']?.plan||{}).length>0,null,{timeout:90000});const elapsed=Date.now()-start;
 const frames=await p.evaluate(()=>{window.bfTracking=false;return window.bfFrames;});assert(frames.length>0);const sorted=[...frames].sort((a,b)=>a-b),p95=sorted[Math.floor(sorted.length*.95)];assert(p95<250,'Frame p95 exceeds 250 ms: '+p95);
 const plan=await p.evaluate(()=>window.DokkanBattlefield.getState().sessions['global-109'].plan),ids=Object.values(plan).flat();assert.equal(new Set(ids).size,ids.length);
 const selected=Object.keys(plan)[0];await p.selectOption('#bfBoss',selected);assert.equal(await p.locator('.bf-card [data-bf-replace]').count(),7);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 const original=plan[selected];await p.locator('[data-bf-replace="2"]').click();await p.waitForFunction(()=>!document.querySelector('[data-bf-action="cancel"]'),null,{timeout:90000});const after=await p.evaluate(b=>window.DokkanBattlefield.getState().sessions['global-109'].plan[b],selected);if(after.some((i,n)=>i!==original[n]))assert.equal(after.filter((i,n)=>i!==original[n]).length,1);
 await p.screenshot({path:`audit-artifacts/battlefield-${config.name}.png`,fullPage:true});
 p.on('dialog',d=>d.accept());await p.locator('[data-bf-action="victory"]').click();assert.equal(await p.evaluate(()=>window.DokkanBattlefield.getState().sessions['global-109'].attempts.length),1);
 await p.locator('[data-bf-mode="classic"]').click();assert(await p.locator('#autoTeam').count());await p.locator('[data-bf-mode="battlefield"]').click();
 const afterBox=await p.evaluate(()=>({inventory:localStorage.getItem('dokkanos-inventory'),edits:localStorage.getItem('dokkanos-edits'),team:JSON.stringify(selectedTeam),leader:teamLeader}));assert.deepEqual(afterBox,before);
 // Wait for PWA installation, then prove the worker/data remain available offline.
 await p.waitForFunction(()=>navigator.serviceWorker.controller,null,{timeout:90000});await ctx.setOffline(true);await p.reload();await p.waitForFunction(()=>window.DokkanBattlefield&&teamOwnedCards().length>0,null,{timeout:90000});await p.evaluate(async()=>{await window.DokkanBattlefield.ready;window.DokkanBattlefield.open();});assert.equal(await p.evaluate(()=>window.DokkanBattlefield.getState().sessions['global-109'].attempts.length),1);await p.locator('[data-bf-action="generate"]').click();await p.waitForFunction(()=>!document.querySelector('[data-bf-action="cancel"]'),null,{timeout:90000});assert(!await p.locator('#bfStatus').textContent().then(s=>/échoué|indisponibles/.test(s)));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({profile:config.name,teams:Object.keys(plan).length,uniqueCards:ids.length,generationMs:elapsed,frames:frames.length,frameP95Ms:Math.round(p95),offline:true,boxPreserved:true}));await ctx.close();
 }finally{await browser.close();}}})().catch(e=>{console.error(e);process.exitCode=1});
