const fs=require('fs'),assert=require('node:assert/strict'),{chromium,webkit,devices}=require('playwright');
fs.mkdirSync('audit-artifacts',{recursive:true});
(async()=>{for(const scenario of [{name:'desktop',engine:chromium,settings:{viewport:{width:1280,height:900}}},{name:'iphone-12',engine:webkit,settings:devices['iPhone 12']}]){
 const browser=await scenario.engine.launch();try{
 const context=await browser.newContext({...scenario.settings,acceptDownloads:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8765');await p.waitForFunction(()=>performance.getEntriesByType('navigation')[0]?.type==='reload'&&navigator.serviceWorker.controller&&document.querySelector('#grid .unit')&&window.DokkanWorkbench,null,{timeout:90000});
 await p.evaluate(async()=>{await ensureEvents();await teamBossReady;teamSettings.pool='owned';teamSettings.useZA=false;chooseTeamLeader(TE.identity(teamOwnedCards().find(c=>c.leader)));switchView('teams');});
 await p.locator('[data-team-action="bestLeader"]').click();await p.waitForFunction(()=>!teamBusy,null,{timeout:150000});assert.equal(await p.evaluate(()=>selectedTeam.length),6,await p.locator('#teamBuildStatus').textContent());
 const box=await p.evaluate(()=>[localStorage.getItem('dokkanos-inventory'),localStorage.getItem('dokkanos-edits')]);
 assert.equal(await p.locator('.wb-rotation').count(),2);assert.equal(await p.locator('.wb-slot').count(),6);
 assert(await p.evaluate(()=>{const r=DokkanWorkbench.diagnostic().evaluation.rotations;return r.length===2&&r[0].third.boxId!==r[1].third.boxId;}));
 const cards=await p.evaluate(()=>[...selectedTeam]);await p.locator('[data-wb-goal="security"]').click();assert.deepEqual(await p.evaluate(()=>[...selectedTeam]),cards);
 await p.locator('#wbDuo').locator('..').locator('summary').click();await p.locator('#wbDuo [name=duo0]').selectOption(cards[1]);await p.locator('#wbDuo [name=duo1]').selectOption(cards[2]);await p.locator('#wbDuo button').first().click();
 await p.locator('#autoTeam').click();await p.waitForFunction(()=>!teamBusy&&selectedTeam.length===6,null,{timeout:150000});assert(await p.evaluate(ids=>ids.every(id=>selectedTeam.includes(id)&&teamSettings.locked.includes(id)),cards.slice(1,3)));
 await p.evaluate(()=>document.querySelector('#wbDuo').closest('details').open=true);await p.locator('[data-wb-clear-duo]').click();
 await p.locator('#wbRotations').scrollIntoViewIfNeeded();await p.screenshot({path:`audit-artifacts/workbench-rotations-${scenario.name}.png`});
 await p.evaluate(()=>switchView('home'));assert.equal(await p.locator('.wb-mode-cards button').count(),3);await p.screenshot({path:`audit-artifacts/workbench-home-${scenario.name}.png`});await p.locator('.wb-mode-cards [data-wb-resume="frontier"]').click();await p.waitForFunction(()=>document.querySelector('#teams main').dataset.teamMode==='frontier');await p.evaluate(()=>switchView('home'));assert.equal(await p.evaluate(()=>DokkanWorkbench.preferences().resumeMode),'frontier');await p.locator('.wb-mode-cards [data-wb-resume="classic"]').click();
 const id=await p.evaluate(()=>TE.identity(teamCards()[1]));await p.evaluate(id=>openCard('CATALOG-'+id),id);await p.locator('#wbCardProfile [data-pilot-card]').click();await p.locator('#progressProfile [name=potential]').fill('79');await p.locator('#progressProfile [name=sa]').fill('10');await p.locator('#progressProfile [name=awakening]').selectOption('base');await p.locator('#progressProfile button').click();assert.equal(await p.evaluate(id=>JSON.parse(localStorage.getItem('dokkanos-progression-v1')).profiles[id].potential,id),79);await p.evaluate(id=>openCard('CATALOG-'+id),id);assert((await p.locator('#wbCardProfile').innerText()).includes('79 %'));assert((await p.locator('#wbCardProfile').innerText()).includes('Sans éveil Z'));assert.equal(await p.locator('#wbCardProfile [data-pilot-card]').getAttribute('data-pilot-card'),id);await p.screenshot({path:`audit-artifacts/workbench-card-${scenario.name}.png`});await p.evaluate(()=>closeSheet());
 await p.evaluate(()=>{teamEvents.events.push({id:'wb-event',name:'Combat test',stages:[{id:'s1',number:1,name:'Niveau 1'},{id:'s2',number:2,name:'Niveau 2'}],missions:[{id:'wb-m1',title:'Mission 1',stageId:'s1',requirements:[]},{id:'wb-m2',title:'Mission 2',stageId:'s1',requirements:[]},{id:'wb-m3',title:'Mission 3',stageId:'s2',requirements:[]}]});eventSettings.selected='wb-event';eventSettings.stage='s1';eventSettings.missions=['wb-m1','wb-m2'];switchView('events');});
 // Batch remains in the mission tab after the existing event layout enhancement.
 await p.evaluate(()=>{const d=document.querySelector('#wbMissionBatch');for(let a=d?.parentElement;a;a=a.parentElement)if(a.tagName==='DETAILS')a.open=true;document.querySelector('[data-ux-event-tab="missions"]')?.click();});
 await p.locator('#wbBatchForm [name=confirmed]').check();await p.locator('#wbBatchForm [name=claimed]').check();await p.locator('#wbBatchForm button').click();assert(await p.evaluate(()=>eventAllProgress()['wb-m1'].claimed&&eventAllProgress()['wb-m2'].done&&!eventAllProgress()['wb-m3'].done));await p.locator('#wbMissionBatch').scrollIntoViewIfNeeded();await p.screenshot({path:`audit-artifacts/workbench-missions-${scenario.name}.png`});await p.locator('[data-wb-undo-missions]').click();assert.equal(await p.evaluate(()=>eventAllProgress()['wb-m1'].done),false);
 await p.evaluate(()=>{teamSettings.event='wb-event';teamSettings.eventStage='s1';teamSettings.mission='wb-m1';teamSettings.eventMissions=['wb-m1'];switchView('teams');});await p.locator('[data-wb-result]').click();
 const form=p.locator('[data-battle-form]').last();assert.equal(await form.locator('[name=validated]').count(),2);await form.locator('[name=result]').selectOption('victory');await form.locator('[data-battle-pick-all]').click();await form.locator('[name=causes][value=ki]').check();await form.locator('button[type=submit]').click();assert.equal(await p.evaluate(()=>DokkanBattles.rows().at(-1).validated.length),2);assert.equal(await p.evaluate(()=>DokkanBattles.rows().at(-1).objective.missions.length),1);assert.equal(await p.evaluate(()=>eventAllProgress()['wb-m3'].done),false);
 await p.evaluate(()=>{document.querySelector('#teamSaved > details').open=true;document.querySelector('.battle-feedback-advice')?.closest('details').setAttribute('open','');});assert(await p.locator('.battle-feedback-advice').isVisible());await p.locator('.battle-feedback-advice').scrollIntoViewIfNeeded();await p.screenshot({path:`audit-artifacts/workbench-feedback-${scenario.name}.png`});
 await p.evaluate(()=>{DokkanProgress.checkpoint();renderTeam();document.querySelector('#teamSaved > details').open=true;document.querySelector('.wb-history').open=true;});await p.locator('[data-wb-preview-version]').first().click();assert(await p.locator('[data-wb-restore-version]').isVisible());await p.locator('[data-wb-restore-version]').click();assert.deepEqual(await p.evaluate(()=>[localStorage.getItem('dokkanos-inventory'),localStorage.getItem('dokkanos-edits')]),box);assert.equal(await p.evaluate(id=>DokkanProgress.state.profiles[id].potential,id),79);
 await p.evaluate(()=>{document.querySelector('#teamSaved > details').open=true;document.querySelector('.wb-backup').open=true;});const [download]=await Promise.all([p.waitForEvent('download'),p.locator('.wb-backup [data-c-export]').click()]);assert(download.suggestedFilename().endsWith('.json'));assert(await p.evaluate(()=>JSON.parse(localStorage.getItem('dokkanos-companion-v1')).lastExport));
 for(const view of ['home','teams','events']){await p.evaluate(view=>switchView(view),view);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),view+' horizontal overflow');}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({profile:scenario.name,visualRotations:true,duoSurvivesGeneration:true,batchScoped:true,rewardsSeparate:true,batchUndo:true,extraMissions:true,explicitAdvice:true,boxUnchanged:true,actualProfilePreserved:true,backupExport:true,noOverflow:true}));await context.close();
 }finally{await browser.close();}
}console.log('Workshop desktop/iPhone WebKit: all eight improvements and grouped mission confirmation: OK');})().catch(e=>{console.error(e);process.exitCode=1});
