const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
fs.mkdirSync('audit-artifacts',{recursive:true});const report={checks:[],errors:[]};
async function go(page,id){await page.evaluate(id=>switchView(id),id);await page.locator('#'+id+'.on').waitFor();}
async function tool(page,id,card){await page.evaluate(([id,card])=>window.DokkanCopilot.open(id,card),[id,card]);await page.locator('#pilotWork').waitFor();}
(async()=>{const browser=await chromium.launch({headless:true});try{for(const width of [390,1280]){
 const context=await browser.newContext({viewport:{width,height:900},acceptDownloads:true,serviceWorkers:'allow'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let navs=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navs++});await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>document.querySelector('#grid .unit'),null,{timeout:60000});if(navs<2)await page.waitForEvent('framenavigated',{predicate:f=>f===page.mainFrame(),timeout:60000});await page.waitForFunction(()=>navigator.serviceWorker.controller&&window.DokkanProgress,null,{timeout:60000});await go(page,'teams');await page.locator('#teamLeaderSearch').fill('1034201');await page.locator('#teamLeaderResults [data-team-leader="1034201"]').click();if(await page.locator('[data-team-own-leader="1034201"]').count())await page.locator('[data-team-own-leader="1034201"]').click();await page.locator('#autoTeam').click();await page.waitForFunction(()=>document.querySelector('#teamCount').textContent==='6/6'&&!document.querySelector('#autoTeam').disabled,null,{timeout:60000});
 for(const id of ['profiles','counters','combat','duo','bosses','history','goals','updates','farmSources','sync']){await tool(page,id);await page.waitForTimeout(150);assert(await page.locator('#pilotWork h2').count()>0,id);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),id+' overflow');await page.screenshot({path:'audit-artifacts/progression-'+id+'-'+width+'.png'});}
 await tool(page,'profiles','1034201');await page.locator('#progressProfile [name="sa"]').fill('20');await page.locator('#progressProfile [name="potential"]').fill('79');await page.locator('#progressProfile [name="awakening"]').selectOption('base');await page.locator('#progressProfile details summary').click();await page.locator('#progressProfile [name="link0"]').fill('10');await page.locator('#progressProfile button').click();assert.equal(await page.evaluate(()=>window.DokkanProgress.state.profiles['1034201'].potential),79);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('dokkanos-kit-versions-v4'))['1034201']),'base');
 await tool(page,'combat');await page.locator('[data-progress-count="attacks"][data-progress-card="1034201"][data-progress-delta="1"]').click();await page.locator('[data-progress-turn="1"]').click();assert.equal(await page.evaluate(()=>window.DokkanProgress.state.combat.counts['1034201'].attacks),1);assert.equal(await page.evaluate(()=>window.DokkanProgress.state.combat.turn),2);await page.locator('[data-progress-reset]').click();assert.equal(await page.evaluate(()=>window.DokkanProgress.state.combat.turn),1);
 await tool(page,'duo');const duo=await page.evaluate(()=>teamCards().slice(0,2).map(DokkanTeamEngine.identity));await page.locator('#progressDuo [name="card0"]').selectOption(duo[0]);await page.locator('#progressDuo [name="card1"]').selectOption(duo[0]);await page.locator('#progressDuo button').click();assert((await page.locator('#pilotStatus').innerText()).includes('distinctes'));await page.locator('#progressDuo [name="card1"]').selectOption(duo[1]);await page.locator('#progressDuo button').click();await page.locator('[data-progress-load-duo]').waitFor({timeout:120000});assert(!(await page.locator('[data-progress-load-duo]').isDisabled()));await page.locator('[data-progress-load-duo]').click();assert(await page.evaluate(ids=>ids.every(k=>teamCards().some(c=>DokkanTeamEngine.identity(c)===k)),duo));
 await page.waitForTimeout(500);await page.evaluate(()=>{selectedTeam=[...selectedTeam].reverse();saveTeamState();});await page.waitForTimeout(500);await tool(page,'history');assert.equal(await page.locator('[data-progress-restore]').count(),2);assert(await page.evaluate(()=>DokkanProgress.state.history.length>=2));const version=await page.evaluate(()=>DokkanProgress.state.history.find(h=>h.snapshot.cards.length===6).id);await page.locator('#progressHistoryA').selectOption(version);await page.locator('[data-progress-restore]').first().click();assert.equal(await page.locator('#teamCount').innerText(),'6/6');
 await tool(page,'bosses');await page.evaluate(async()=>{await ensureEvents();});await page.locator('#progressBossEvent').selectOption('quest-1769');await page.locator('#progressBossStage').selectOption('17690045');assert((await page.locator('#pilotWork').innerText()).includes('Phase 1'));assert((await page.locator('#pilotWork').innerText()).includes('130,000,000'));await page.locator('[data-progress-boss-team]').click();assert.equal(await page.evaluate(()=>teamSettings.eventStage),'17690045');assert.equal(await page.locator('#teams.on').count(),1);
 await tool(page,'goals');await page.locator('#progressGoal [name="title"]').fill('<img src=x onerror=alert(1)>');await page.locator('#progressGoal [name="steps"]').fill('Éveiller\nMonter ATT SP');await page.locator('#progressGoal button').click();assert.equal(await page.locator('#pilotWork img[src="x"]').count(),0);await page.locator('[data-progress-goal]').first().check();assert.equal(await page.evaluate(()=>DokkanProgress.state.goals[0].steps[0].done),true);await page.locator('[data-progress-goal-card]').click();assert.equal(await page.evaluate(()=>DokkanProgress.state.goals.length),2);
 await tool(page,'farmSources','1003211');await page.waitForFunction(()=>document.querySelector('#pilotWork')?.textContent.includes('Niveaux')||document.querySelector('[data-progress-farm-level]'));assert(await page.locator('[data-progress-farm-level]').count()>0);await page.locator('[data-progress-farm-level]').first().click();assert.equal(await page.locator('#events.on').count(),1);
 await tool(page,'updates');await page.locator('[data-progress-refresh]').click();await page.waitForFunction(()=>document.querySelector('#pilotStatus')?.textContent.includes('Vérification terminée'));assert(await page.evaluate(()=>DokkanProgress.state.dataHistory.length>0));
 const backup=await page.evaluate(()=>DokkanCompanionModel.backup(localStorage));assert(backup.entries['dokkanos-progression-v1']);assert(!backup.entries['dokkanos-sync-config']);await page.reload();await page.waitForFunction(()=>window.DokkanProgress&&document.querySelector('#grid .unit'),null,{timeout:60000});assert.equal(await page.evaluate(()=>DokkanProgress.state.profiles['1034201'].potential),79);await tool(page,'goals');assert(await page.locator('[data-progress-goal]').count()>0);
 // Simulated service: exercise client/API protocol; no production Supabase service is provisioned.
 let cloud=null,rev=0;await page.route('https://audit.supabase.co/**',async route=>{const req=route.request(),url=req.url(),body=req.postDataJSON();let payload;if(url.includes('/otp'))payload={};else if(url.includes('/verify')||url.includes('/token'))payload={access_token:'fake-test-token',refresh_token:'fake-test-refresh',expires_in:3600,user:{id:'00000000-0000-0000-0000-000000000001',email:'audit@example.org'}};else if(url.includes('/rpc/dokkanos_save')){if(body.expected_revision!==rev)payload={ok:false};else{cloud=body.payload_data;rev++;payload={ok:true,revision:rev};}}else if(url.includes('/dokkanos_snapshots'))payload=cloud?[{payload:cloud,revision:rev,updated_at:new Date().toISOString()}]:[];else payload={};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(payload)});});
 await tool(page,'sync');assert((await page.locator('#pilotWork').innerText()).includes('Synchronisation inactive'));await page.locator('#syncConfig [name="url"]').fill('https://audit.supabase.co');await page.locator('#syncConfig [name="key"]').fill('sb_secret_rejected');await page.locator('#syncConfig button').click();assert((await page.locator('#pilotWork').innerText()).includes('Clé secrète interdite'));await page.locator('#syncConfig [name="url"]').fill('https://audit.supabase.co');await page.locator('#syncConfig [name="key"]').fill('sb_publishable_test');await page.locator('#syncConfig button').click();await page.locator('#syncLogin [name="email"]').fill('audit@example.org');await page.locator('#syncLogin button').click();await page.locator('#syncVerify [name="token"]').fill('123456');await page.locator('#syncVerify button').click();await page.locator('[data-sync="push"]').waitFor();await page.locator('[data-sync="push"]').click();await page.waitForFunction(()=>document.querySelector('#progressSync')?.textContent.includes('sauvegardée en ligne'));assert.equal(rev,1);assert(!JSON.stringify(cloud).includes('fake-test-token'));assert(!cloud.entries['dokkanos-sync-config']);
 await page.locator('#syncAuto').check();await tool(page,'combat');await page.locator('[data-progress-turn="1"]').click();await page.waitForFunction(()=>document.querySelector('#pilotWork'),null,{timeout:1000});for(let n=0;n<20&&rev<2;n++)await page.waitForTimeout(500);assert(rev>=2,'automatic upload');
 rev++;await page.locator('[data-progress-turn="1"]').click();await page.waitForTimeout(3800);await tool(page,'sync');assert((await page.locator('#progressSync').innerText()).includes('deux appareils'));assert.equal(await page.locator('[data-sync="pull"]').count(),1);const before=rev;await page.locator('[data-sync="push"]').click();await page.waitForFunction(()=>document.querySelector('#progressSync')?.textContent.includes('sauvegardée en ligne'));assert.equal(rev,before+1);await page.locator('#syncAuto').uncheck();
 // First-connection remote preview and transactional restore with rescue.
 await page.locator('[data-sync="check"]').click();await page.locator('[data-sync="pull"]').waitFor();await Promise.all([page.waitForEvent('download'),page.waitForEvent('framenavigated',{predicate:f=>f===page.mainFrame()}),page.locator('[data-sync="pull"]').click()]);await page.waitForFunction(()=>window.DokkanProgress&&document.querySelector('#grid .unit'),null,{timeout:60000});assert(await page.evaluate(()=>!!localStorage.getItem('dokkanos-sync-rescue')));await tool(page,'sync');assert.equal(await page.locator('[data-sync="rescue"]').count(),1);await page.locator('[data-sync="logout"]').click();await page.waitForFunction(()=>sessionStorage.getItem('dokkanos-sync-session')===null);assert.equal(await page.evaluate(()=>sessionStorage.getItem('dokkanos-sync-session')),null);
 await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.DokkanProgress&&document.querySelector('#grid .unit'),null,{timeout:60000});for(const id of ['profiles','combat','goals','bosses','farmSources']){await tool(page,id);assert(await page.locator('#pilotWork h2').count()>0);}assert.deepEqual(errors,[]);report.checks.push({width,profiles:true,counters:true,compact:true,duo:true,history:true,goals:true,bossPhases:true,farmingSources:true,updates:true,backup:true,persistence:true,syncMockAuth:true,syncConflict:true,syncAuto:true,syncRestoreRescue:true,offline:true});await context.close();
 }}catch(e){report.errors.push(e.stack||String(e));process.exitCode=1;}finally{await browser.close();fs.writeFileSync('audit-artifacts/progression-report.json',JSON.stringify(report,null,2));console.log('PROGRESSION_AUDIT '+JSON.stringify(report));}})();
