const fs=require('fs'),vm=require('vm'),assert=require('assert'),{parseHTML}=require('linkedom');
const {document,window}=parseHTML(fs.readFileSync('index.html','utf8'));const saved=new Map();window.HTMLElement.prototype.scrollIntoView=function(){};const context={console,window,document,navigator:{onLine:true},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,String(v))},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path,'utf8'))}),alert:m=>{console.log('ALERT',m)},setTimeout,clearTimeout,Date,location:{reload(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('team-engine.js','utf8'),context);vm.runInContext(fs.readFileSync('app.js','utf8').split('boot().catch(')[0],context);vm.runInContext(fs.readFileSync('teams.js','utf8'),context);
(async()=>{await vm.runInContext('boot()',context);for(const btn of document.querySelectorAll('nav button')){btn.querySelector('span').click();assert(document.querySelector('#'+btn.dataset.v).classList.contains('on'));btn.querySelector('b').click();assert(document.querySelector('#'+btn.dataset.v).classList.contains('on'));}
for(const chip of document.querySelectorAll('.invchip')){chip.click();assert.equal(vm.runInContext('inventoryFilter',context),chip.dataset.invf);}
vm.runInContext(`query='goku';filter='check';rarityFilter='LR';render()`,context);document.querySelector('#resetFilters').click();assert.equal(vm.runInContext('query+rarityFilter',context),'');assert.equal(vm.runInContext('filter',context),'all');
assert.equal(vm.runInContext('verifyCandidate("999999999")',context),null);
vm.runInContext(`META.cards['9990000']={name:'Ancienne',passive:'ANCIEN PASSIF',leader:'ANCIEN LEADER',eza:true};CATALOG.cards.push({id:'9990001',name:'Nouvelle',rarity:'UR',type:'INT'});let auditCard={boxId:'TEST',candidateId:'9990000',crop:'capture.png',...META.cards['9990000']};assignIdentification(auditCard,'9990001');`,context);assert.equal(vm.runInContext('auditCard.passive',context),undefined);assert.equal(vm.runInContext('auditCard.leader',context),undefined);assert.equal(vm.runInContext('auditCard.eza',context),undefined);assert.equal(vm.runInContext('auditCard.crop',context),'capture.png');
assert.equal(vm.runInContext(`awakeningLabel({id:'9990001',name:'Identique'},[{id:'9990000',name:'Identique'}])`,context),'');
vm.runInContext('switchView("teams")',context);assert(document.querySelector('#teamObjective'));assert(document.querySelector('#teamComposition'));assert.equal(document.querySelectorAll('[data-team-setting="event"] option').length,9);console.log('confirmed cards',vm.runInContext('ownedTeamCards().length',context));vm.runInContext(`inventory['9990001']='owned';query='aucun-resultat';render()`,context);assert.equal(document.querySelectorAll('#manualOwned .unit').length,0);vm.runInContext(`query='nouvelle';render()`,context);assert.equal(document.querySelectorAll('#manualOwned .unit').length,1);vm.runInContext(`query='';delete inventory['9990001'];render()`,context);
const leader=vm.runInContext('ownedTeamCards().find(c=>c.leader&&TE.coverage(c,c,teamKnown()).covered)',context);assert(leader);vm.runInContext(`teamLeader=${JSON.stringify(leader.boxId)};teamSettings.event='campaign-2026-p3';teamSettings.mission='boo-4';renderTeam()`,context);const start=Date.now();vm.runInContext('autoBuildTeam()',context);console.log('build',Date.now()-start,'ms',document.querySelector('#teamCount').textContent);assert(document.querySelector('#teamBuildStatus').textContent);const input=document.querySelector('#teamName');input.value='Test & <composition>';document.querySelector('[data-team-action="save"]').click();assert.equal(document.querySelectorAll('.team-saved-row').length,1);assert(document.querySelector('.team-saved-row').textContent.includes('Test & <composition>'));document.querySelector('[data-team-load]').click();assert.equal(document.querySelectorAll('.team-saved-row').length,1);vm.runInContext('clearTeam()',context);assert.equal(document.querySelector('#teamCount').textContent,'0/6');document.querySelector('[data-team-load]').click();assert.notEqual(document.querySelector('#teamCount').textContent,'0/6');console.log('Seven tabs, inventory chips, complete reset, unknown ID, metadata replacement and verified awakenings: OK');console.log('Team UI boot, events, mission, leader, optimization, escaped name, save/load and clear: OK');
for(const [key,value] of [['dokkanos-edits','{}'],['dokkanos-inventory','null'],['dokkanos-team','{}'],['dokkanos-favorites','{}'],['dokkanos-rainbow100','{}'],['dokkanos-potential-manual','[]'],['dokkanos-saved-teams-v2','[null,{}, {"name":"Invalid","cards":[]}]']])saved.set(key,value);
vm.runInContext('restoreEdits();render();stats();renderInventory();renderMissing();renderManualOwned();renderDuplicates();renderAnalysis();renderTeam()',context);assert.equal(vm.runInContext('teamSaved().length',context),0);
context.localStorage.getItem=()=>{throw Error('Storage disabled')};context.localStorage.setItem=()=>{throw Error('Storage disabled')};await vm.runInContext('boot()',context);assert.equal(vm.runInContext('saveEdits()',context),false);vm.runInContext('renderTeam();toggleRainbow100("1000010")',context);console.log('Malformed saved values and blocked storage: OK');})();
