const assert=require('node:assert/strict'),E=require('../team-engine'),meta=require('../card-meta.json').cards;
const unit=(id,passive,sa='')=>({id,boxId:id,name:id,passive,superAttack:{description:sa},categories:['A'],links:['Lien'],type:'INT',class:'Super',rarity:'UR'});
const basic='*Effets de base*\n- ATT et DÉF +150 %';
assert.deepEqual(E.positionSlots('En attaquant en 2e ou 3e position'),[2,3]);
const first=unit('first',basic+'\n*En 1re position*\n- Garde activée contre toutes les attaques');
assert(E.placementProfile(first,1).guaranteedProtection);assert(!E.placementProfile(first,2).guaranteedProtection);
const attackGuard=unit('attackGuard',basic+'\n*En attaquant en 1re position*\n- Garde activée contre toutes les attaques\n- DÉF +200 %');
assert(!E.placementProfile(attackGuard,1).guaranteedProtection);assert(E.placementProfile(attackGuard,1).postDefense>0);
const receive=unit('receive',basic+'\n*Au moment d’encaisser une attaque*\n- DÉF +200 %\n- Taux de réduction des dégâts +40 %');
const received=unit('received',basic+'\n*Après avoir encaissé 3 attaques*\n- Garde activée contre toutes les attaques');
assert(E.placementProfile(receive,1).guaranteedProtection);assert(!E.placementProfile(received,1).guaranteedProtection);assert(E.placementProfile(received,1).rows.some(r=>r.timing==='build'));
const dodger=unit('dodger',basic+'\n*Avant que ce perso n’attaque*\n- Fortes chances d’esquiver l’attaque ennemie');
assert(E.placementProfile(dodger,1).rows.some(r=>r.dodge));assert(!E.placementProfile(dodger,1).guaranteedProtection);assert(!E.placementProfile(dodger,1,[],{disableDodge:true}).rows.some(r=>r.dodge));
assert(E.placementProfile(dodger,1,[],{boss:{disableDodge:true}}).warnings.some(w=>w.includes('annulée')));
const randomGuard=unit('randomGuard',basic+'\n*Effets de base*\n- Grandes chances de garde activée contre toutes les attaques');assert(!E.placementProfile(randomGuard,1).guaranteedProtection);
const ally=unit('ally',basic),inline=unit('inline',basic+'\n*S’il y a parmi les alliés attaquants du tour un autre perso de catégorie "A"*\n- En 1re position, DÉF +100 % et garde activée contre toutes les attaques\n- En 2e ou 3e position, ATT +200 %');
assert(!E.placementProfile(inline,1,[inline],{},[inline]).guaranteedProtection);
assert(E.placementProfile(inline,1,[inline,ally],{},[inline,ally]).guaranteedProtection);
assert(!E.placementProfile(inline,2,[inline,ally],{},[inline,ally]).guaranteedProtection);
const entry=unit('entry',basic+'\n*À son apparition, s’il y a un autre perso de catégorie "A" dans l’équipe*\n- Taux de réduction des dégâts +90 % [1 fois] [permanent]');
assert(!E.placementProfile(entry,1,[entry,ally],{},[entry,ally]).guaranteedProtection);
const decay=unit('decay',basic+'\n*À son apparition*\n- Taux de réduction des dégâts +90 %\n- À chaque tour passé, taux de réduction des dégâts -15 % (max. 90 %)');assert(!E.placementProfile(decay,1).rows.some(r=>r.text.includes('-15 %')));assert(E.placementProfile(decay,1).warnings.some(w=>w.includes('décroissante')));
const ultra=unit('ultra',basic);ultra.ultraSuperAttack={description:'Augmente fortement la DÉF pendant 1 tour ; inflige des dégâts colossaux'};assert(E.placementProfile(ultra,2).summary.some(s=>s.includes('Ultra-SP')));
const enemyDown=unit('enemyDown',basic,'Augmente l’ATT ; inflige des dégâts immenses et réduit la DÉF');assert(!E.placementProfile(enemyDown,2).summary.some(s=>s.includes('Après la SP')));
const third=unit('third',basic+'\n*En attaquant en 3e position*\n- ATT +500 %\n- ATT SP supplémentaire garantie');assert(E.placementProfile(third,3).score>E.placementProfile(third,2).score);
const thirdSupport=unit('thirdSupport',basic+'\n*En 3e position*\n- Ki +3 et ATT et DÉF +50 % pour tous les alliés');const support3=E.placementProfile(thirdSupport,3,[thirdSupport,ally],{},[thirdSupport,ally]);assert(support3.rows.some(r=>r.support>0&&r.defense===0));assert(support3.score>E.placementProfile(thirdSupport,2,[thirdSupport,ally],{},[thirdSupport,ally]).score);
const second=unit('second',basic+'\n*En attaquant en 2e position*\n- ATT et DÉF +300 %','Augmente fortement la DÉF pendant 1 tour ; inflige des dégâts immenses');
const tank2=unit('tank2',first.passive),second2=unit('second2',second.passive),filler=unit('filler',basic);
const team=[first,second,tank2,second2,third,filler],rot=E.rotations(team);assert.equal(rot.length,2);assert(rot.every(r=>[first.id,tank2.id].includes(r.a.id)));assert(rot.every(r=>[second.id,second2.id].includes(r.b.id)));assert(rot.some(r=>r.third.id===third.id));assert.equal(new Set(rot.flatMap(r=>[r.a.id,r.b.id])).size,4);
// Exact current sourced kits: position bonus nested under rotation-category condition.
const sourced=id=>({...meta[id],...meta[id].fr,id,boxId:id});const goku=sourced('1034481'),boo=unit('boo',basic);boo.categories=['Saga de Boo'];
assert(E.placementProfile(goku,1,[goku,boo],{},[goku,boo]).guaranteedProtection);
assert(!E.placementProfile(goku,2,[goku,boo],{},[goku,boo]).guaranteedProtection);
assert(!E.placementProfile(goku,1,[goku,boo],{},[goku]).guaranteedProtection);
const arinsu=sourced('1034431');assert(E.placementProfile(arinsu,1,[],{disableDodge:true}).rows.some(r=>r.timing==='hit'&&r.defense));assert(!E.placementProfile(arinsu,1,[],{disableDodge:true}).rows.some(r=>r.dodge));
console.log('Placement 1/2/3, before own attack vs attack, hit vs after hits, random guards, dodge cancellation, rotation category, conditional entry, ultra-SP and actual sourced kits: OK');
