const assert=require('node:assert/strict'),fs=require('fs'),E=require('../team-engine.js'),M=require('../frontier-model.js'),C=require('../companion-model.js'),data=JSON.parse(fs.readFileSync('frontier-data.json'));
const cards=Array.from({length:32},(_,i)=>({id:String(9000000+i),name:'Carte '+i,type:['AGI','TEC','INT','PUI','END'][i%5],categories:i<12?['A','Cyborg','Kamehameha']:['B'],links:['Lien'],leader:'Ki +3, PV, ATT et DÉF +'+(i<4?200:150)+' % pour tous les types',passive:'*Effets de base*\n- Garde activée contre toutes les attaques\n- ATT et DÉF +'+(100+i*2)+' %',superAttack:'Augmente la DÉF',dataStatus:{kit:'verified'}}));
(async()=>{
assert.equal(data.nodes.length,72);assert.equal(data.chapters.length,5);assert.equal(new Set(data.nodes.map(n=>n.id)).size,72);assert.equal(data.nodes.find(n=>n.id==='global-7').phases[0].enemies.length,3);assert(M.context(data.nodes.find(n=>n.id==='global-6')).disableDodge);
for(const n of data.nodes){assert(n.phases.every(p=>p.enemies.length&&p.enemies.every(e=>['AGI','TEC','INT','PUI','END'].includes(e.type))));assert(n.missions.some(m=>m.id===n.mission.id));assert(n.source.startsWith('https://'));assert(n.heat.every(h=>Number.isInteger(h.level)&&h.level>0));}
const entry=data.nodes.find(n=>n.chapterId==='namek');assert(!M.assess(E,cards.slice(0,6),entry,['A']).valid);const required={...data.nodes[0],mission:{kind:'leader',manual:true,requiredLeader:cards[1].id}};assert(!M.quota(E,cards.slice(0,6),required,true));const led=[cards[1],cards[0],...cards.slice(2,6)];assert(M.quota(E,led,required,true));const rainbow={...required,mission:{kind:'rainbow'}};assert(!M.quota(E,led,rainbow,true));assert(M.quota(E,led.map((c,i)=>({...c,_realPotential:i===0?100:null})),rainbow,true));
const node=data.nodes[0];let s=M.empty();const result=await M.compose(E,cards,node,['A','B'],s);assert.equal(result.cards.length,6);assert.equal(new Set(result.cards).size,6);const team=result.cards.map(i=>cards.find(c=>c.id===i)),e=M.assess(E,team,node,['A','B']);assert(e.valid&&Number.isFinite(e.score));assert.equal(e.groups[0].cover.length,3);assert.equal(e.groups[1].cover.length,3);assert(e.groups[0].cover.every(c=>c.hp<=200),'One leader per group, never sum two leader skills');
const incompatible=team.map((c,i)=>({...c,categories:i<3?['A']:['B'],leader:'Ki +3, PV, ATT et DÉF +170 % pour la catégorie "'+(i<3?'A':'B')+'"'}));assert(M.assess(E,incompatible,node,['A','B']).valid,'Cross-group leader coverage is not required');
s.cards=result.cards;s.locked=[0,2,3];const locked=await M.compose(E,cards,node,['A','B'],s);for(const i of s.locked)assert.equal(locked.cards[i],s.cards[i]);const replace=await M.replace(E,cards,team,node,['A','B'],s,1);assert(replace&&Number.isFinite(replace.score));assert.equal(replace.cards.filter((i,j)=>i!==s.cards[j]).length,1);await assert.rejects(M.replace(E,cards,team,node,['A','B'],s,0));
for(const label of ['3','7']){const n=data.nodes.find(n=>n.label===label),q=M.empty();q.mission=true;const found=await M.compose(E,cards,n,['A','B','Cyborg','Kamehameha'],q);assert(found);const ct=found.cards.map(i=>cards.find(c=>c.id===i));assert(ct.filter(c=>E.inCategory(c,n.mission.category)).length>=n.mission.count);assert(M.assess(E,ct,n,['A','B','Cyborg','Kamehameha'],true).valid);}
const aliases=cards.map(c=>({...c,categories:c.categories.includes('Cyborg')?['Cyborge','Destruction planétaire']:c.categories})),aliasNode={...node,mission:{kind:'category',category:'Destructeurs de planètes',count:6}};const aliasSession=M.empty();aliasSession.mission=true;const aliasTeam=await M.compose(E,aliases,aliasNode,['Cyborge','Destruction planétaire'],aliasSession);assert(aliasTeam&&M.assess(E,aliasTeam.cards.map(i=>aliases.find(c=>c.id===i)),aliasNode,['Cyborge','Destruction planétaire'],true).valid);
const impossible={...node,category:'absente'};assert.equal(await M.compose(E,cards,impossible,['A'],M.empty()),null);await assert.rejects(M.compose(E,cards,node,['A'],M.empty(),()=>{},()=>true),/annulée/);
s.board=M.initial(s.cards);s.board.gauge=3;s.board.hp[s.cards[0]]=0;s.board.hp[s.cards[1]]=20;s=M.editBoard(s,s.board);assert(s.board.lost.includes(s.cards[0]));const switched=M.exchange(s,2);assert.equal(switched.board.active,'B');assert.equal(switched.board.gauge,1);assert.equal(switched.board.hp[s.cards[0]],0,'Exchange cannot revive LOST');assert.equal(switched.board.hp[s.cards[1]],50);assert.deepEqual(switched.board.heat,s.board.heat,'Do not invent heat changes');assert.deepEqual(s.board.active,'A');assert.throws(()=>M.exchange(switched,3),/Jauge/);let corrected=M.editBoard(switched,{...switched.board,hp:{...switched.board.hp,[s.cards[0]]:100}});assert(corrected.board.lost.includes(s.cards[0]));assert(M.advice({...s,board:{...s.board,heat:{A:4,B:0}}},node).some(x=>x.includes('Effets des attaques')));
assert.throws(()=>M.validateSession({...s,cards:[...s.cards.slice(0,5),s.cards[0]]}));assert.throws(()=>M.validateSession({...s,board:{...s.board,gauge:-1}}));assert.throws(()=>M.validateSession({...s,missionDone:true,completed:false}));
const state={version:1,active:node.id,sessions:{[node.id]:s}},saved=new Map([[M.key,JSON.stringify(state)]]),storage={length:1,key:i=>[...saved.keys()][i],getItem:k=>saved.get(k)},backup=C.backup(storage);assert.deepEqual(C.parseBackup(JSON.stringify(backup)).entries,backup.entries);backup.entries[M.key]='{"version":1,"active":"global-1","sessions":{"global-1":{}}}';assert.throws(()=>C.parseBackup(JSON.stringify(backup)));
console.log('Frontier: separate leaders, balanced unique groups, quotas, locked slots, single-card replacement, manual HP/heat, exchanges, LOST history, cancellation and portable backup: OK');
})().catch(e=>{console.error(e);process.exitCode=1});
