const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('../team-engine');
const leader={id:'L',boxId:'L',name:'Leader',type:'INT',class:'Super',categories:['A'],leader:'Ki +3, PV, ATT et DÉF +170 % pour la catégorie "A"; PV, ATT et DÉF +30 % supplémentaires pour la catégorie "B"'};
const a={id:'a',boxId:'a',name:'A',categories:['A'],type:'AGI',class:'Super'},b={id:'b',boxId:'b',name:'B',categories:['B'],type:'TEC',class:'Extrême'},ab={...a,categories:['A','B']};
assert.equal(E.coverage(leader,a).atk,170);assert.equal(E.coverage(leader,ab).atk,200);assert.equal(E.coverage(leader,b).covered,false);
const typed={leader:'Ki +3, PV, ATT et DÉF +120 % pour le type S. INT'};
assert.equal(E.coverage(typed,{type:'INT',class:'Extrême'}).covered,false);assert.equal(E.coverage(typed,{type:'INT',class:'Super'}).covered,true);
assert.equal(E.coverage({leader:''},a).unknown,true);
assert.equal(E.links({name:'Goku',links:['Ki']},{name:'Goku',links:['Ki']}).length,0);
const support={id:'s',passive:'*Effets de base*\n- ATT et DÉF +150 %\n*Si au moins 2 alliés de catégorie "A" sont présents*\n- Taux de réduction des dégâts +50 %'};
assert.equal(E.passive(support,[support,a,b]).effects[1].state,'missing');assert.equal(E.passive(support,[support,a,{...a,id:'a2'}]).effects[1].state,'active');assert.equal(E.passive(support,[support,a,b]).reduction,0);assert.equal(E.passive(support,[support,a,{...a,id:'a2'}]).reduction,50);
const dodge={passive:'*Effets de base*\n- Grandes chances d’esquive'};assert(!E.passive(dodge,[],{disableDodge:true}).roles.includes('Esquive'));
const mission={requirements:[{kind:'category',value:'A',count:2,includeFriend:false}]};assert.equal(E.constraints([a,b],mission,a).rows[0].count,1);
const pool=Array.from({length:9},(_,i)=>({id:String(i),candidateId:String(i),boxId:String(i),name:'Card '+i,rarity:'UR',type:['AGI','TEC','INT','PUI','END'][i%5],categories:['A'],links:['Link '+i%2],passive:'*Effets de base*\n- Garde activée contre toutes les attaques\n- ATT et DÉF +150 %'}));
const result=E.build([leader,...pool,b],leader,{friend:leader,mission:{requirements:[{kind:'types',count:5}]}});
assert.equal(result.team.length,6);assert.equal(new Set(result.team.map(E.identity)).size,6);assert(result.check.ok);assert(!result.team.some(x=>x.id==='b'));
const locked=pool[8],lockResult=E.build([leader,...pool],leader,{locked:[locked]});assert(lockResult.team.some(x=>x.id===locked.id));
assert.equal(E.build([leader,a],leader).team.length,2);assert(E.build([leader,a],leader,{locked:[b]}).error);
const rots=E.rotations(pool.slice(0,6));assert.equal(rots.length,2);assert.equal(new Set(rots.flatMap(r=>[r.a.id,r.b.id])).size,4);
const events=JSON.parse(fs.readFileSync('events.json'));const ids=new Set();for(const e of events.events){assert(e.id&&e.name&&e.source.startsWith('https://'));for(const m of e.missions){assert(!ids.has(m.id));ids.add(m.id);assert(Array.isArray(m.requirements));}}assert.equal(events.coverage.complete,false);
console.log('Team engine: leader base/bonus, type/class intersection, missing data, ally passives, dodge restriction, quotas excluding friend, five types, ownership, locks, rotations and event schema: OK');
