const assert=require('node:assert/strict'),W=require('../workbench-model'),B=require('../team-battle-model'),C=require('../companion-model');
const prefs={version:1,goal:'security',compact:true,resumeMode:'frontier',folds:{saved:false},duoLocks:['a','b']};
assert.deepEqual(W.validate(prefs),prefs);for(const bad of [{...prefs,goal:'win-guaranteed'},{...prefs,compact:1},{...prefs,duoLocks:[1]},{...prefs,folds:{saved:'yes'}}])assert.throws(()=>W.validate(bad));
const event={id:'event',stages:[{id:'s1',number:1},{id:'s2',number:2}],missions:[{id:'m1',title:'A',stageId:'s1'},{id:'m2',title:'B',stageNumber:1},{id:'m3',title:'C',stageId:'s2'},{id:'any',title:'Tous niveaux'}]};
assert.deepEqual(W.stageMissions(event,'s1').map(m=>m.id),['m1','m2','any']);assert.equal(W.stageMissions(event,'bad').length,0);
const before={m1:{done:false,claimed:false},m3:{done:true,claimed:true}},next=W.batch(event,'s1',['m1','m2','m1'],before);
assert.deepEqual(before.m1,{done:false,claimed:false});assert.deepEqual(next.m1,{done:true,claimed:false});assert.deepEqual(next.m3,before.m3);assert(W.batch(event,'s1',['m1'],next,true).m1.claimed);
assert.throws(()=>W.batch(event,'s1',['m3'],before));assert.throws(()=>W.batch(event,'s1',[],before));assert.throws(()=>W.batch(undefined,'',['m1']));
assert.equal(W.advice(['before','ki','before','made-up']).length,2);assert.equal(W.advice(['damage'])[0].goal,'speed');
const team={id:'t',name:'Composition',cards:['a','b'],leader:'a',settings:{event:'event'},objective:{event:'event',stage:'s1',missions:[{id:'m1',title:'A'}]}};
const rows=B.add([],team,{count:1,result:'victory',validated:['m1','m2','m3'],missions:[{id:'m1',title:'A'},{id:'m2',title:'B'}],causes:['ki','ki']});
assert.deepEqual(rows[0].validated,['m1','m2']);assert.deepEqual(rows[0].completedMissions,[{id:'m2',title:'B'}]);assert.deepEqual(rows[0].causes,['ki']);assert.equal(B.summary(rows,team).status,'works');assert.deepEqual(team.objective.missions,[{id:'m1',title:'A'}]);
assert.throws(()=>B.validate([{...rows[0],result:'defeat'}]));assert.throws(()=>B.add([],team,{count:1,result:'defeat',causes:['not-known']}));
const backup={format:'DokkanOS',version:1,createdAt:new Date().toISOString(),entries:{[W.key]:JSON.stringify(prefs),[B.key]:JSON.stringify(rows)}};assert.deepEqual(C.parseBackup(JSON.stringify(backup)),backup);
console.log('Workshop: strict preferences, scoped multi-mission validation, independent reward confirmation, immutable state, explicit cause advice, additional stage missions and portable backup: OK');
