const fs=require('fs'),vm=require('vm'),assert=require('assert'),{parseHTML}=require('linkedom');
const {document,window}=parseHTML(fs.readFileSync('index.html','utf8'));const saved=new Map();window.HTMLElement.prototype.scrollIntoView=function(){};const context={console,window,document,navigator:{onLine:true},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,String(v))},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path,'utf8'))}),alert:m=>{console.log('ALERT',m)},setTimeout,clearTimeout,Date,location:{reload(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('team-engine.js','utf8'),context);vm.runInContext(fs.readFileSync('app.js','utf8').split('boot().catch(')[0],context);vm.runInContext(fs.readFileSync('teams.js','utf8'),context);
(async()=>{await vm.runInContext('boot()',context);for(const btn of document.querySelectorAll('nav button')){btn.querySelector('span').click();assert(document.querySelector('#'+btn.dataset.v).classList.contains('on'));btn.querySelector('b').click();assert(document.querySelector('#'+btn.dataset.v).classList.contains('on'));}
for(const chip of document.querySelectorAll('.invchip')){chip.click();assert.equal(vm.runInContext('inventoryFilter',context),chip.dataset.invf);}
vm.runInContext(`query='goku';filter='check';rarityFilter='LR';render()`,context);document.querySelector('#resetFilters').click();assert.equal(vm.runInContext('query+rarityFilter',context),'');assert.equal(vm.runInContext('filter',context),'all');
const img=document.createElement('img');img.src='capture-original.png';context.auditImage=img;vm.runInContext(`CATALOG.cards.push({id:'9999900',image:'https://example.org/exact.png'});imageFallback(auditImage,'9999900','capture-original.png')`,context);assert.equal(img.getAttribute('src'),'https://example.org/exact.png');vm.runInContext(`imageFallback(auditImage,'9999900','capture-original.png')`,context);assert.equal(img.getAttribute('src'),'assets/cards/9999900.webp');
assert.equal(vm.runInContext('verifyCandidate("999999999")',context),null);
vm.runInContext(`META.cards['9990000']={name:'Ancienne',passive:'ANCIEN PASSIF',leader:'ANCIEN LEADER',eza:true};CATALOG.cards.push({id:'9990001',name:'Nouvelle',rarity:'UR',type:'INT'});let auditCard={boxId:'TEST',candidateId:'9990000',crop:'capture.png',...META.cards['9990000']};assignIdentification(auditCard,'9990001');`,context);assert.equal(vm.runInContext('auditCard.passive',context),undefined);assert.equal(vm.runInContext('auditCard.leader',context),undefined);assert.equal(vm.runInContext('auditCard.eza',context),undefined);assert.equal(vm.runInContext('auditCard.crop',context),'capture.png');
assert.equal(vm.runInContext(`awakeningLabel({id:'9990001',name:'Identique'},[{id:'9990000',name:'Identique'}])`,context),'');
vm.runInContext('switchView("teams")',context);assert(document.querySelector('#teamObjective'));assert(document.querySelector('#teamComposition'));assert.equal(document.querySelectorAll('[data-team-setting="event"] option').length,9);console.log('confirmed cards',vm.runInContext('ownedTeamCards().length',context));vm.runInContext(`inventory['9990001']='owned';query='aucun-resultat';render()`,context);assert.equal(document.querySelectorAll('#manualOwned .unit').length,0);vm.runInContext(`query='nouvelle';render()`,context);assert.equal(document.querySelectorAll('#manualOwned .unit').length,1);vm.runInContext(`query='';delete inventory['9990001'];render()`,context);
const leader=vm.runInContext('ownedTeamCards().find(c=>c.leader&&TE.coverage(c,c,teamKnown()).covered)',context);assert(leader);vm.runInContext(`teamLeader=${JSON.stringify(leader.boxId)};teamSettings.event='campaign-2026-p3';teamSettings.mission='boo-4';renderTeam()`,context);const start=Date.now();await vm.runInContext('autoBuildTeam()',context);console.log('build',Date.now()-start,'ms',document.querySelector('#teamCount').textContent);assert(document.querySelector('#teamBuildStatus').textContent);const input=document.querySelector('#teamName');input.value='Test & <composition>';document.querySelector('[data-team-action="save"]').click();assert.equal(document.querySelectorAll('.team-saved-row').length,1);assert(document.querySelector('.team-saved-row').textContent.includes('Test & <composition>'));document.querySelector('[data-team-load]').click();assert.equal(document.querySelectorAll('.team-saved-row').length,1);vm.runInContext('clearTeam()',context);assert.equal(document.querySelector('#teamCount').textContent,'0/6');document.querySelector('[data-team-load]').click();assert.notEqual(document.querySelector('#teamCount').textContent,'0/6');console.log('Seven tabs, inventory chips, complete reset, unknown ID, metadata replacement and verified awakenings: OK');console.log('Team UI boot, events, mission, leader, optimization, escaped name, save/load and clear: OK');
// Leader-first workflow: a catalogue entry must never silently become owned.
assert(vm.runInContext('verifyCandidate("1034201").leader.includes("220")',context));
assert(!vm.runInContext('ownedTeamCards().some(c=>String(c.candidateId)==="1034201")',context));
const search=document.querySelector('#teamLeaderSearch');search.value='goku ssj3 int';search.dispatchEvent(new window.Event('input',{bubbles:true}));assert(document.querySelector('[data-team-leader="1034201"]'));
document.querySelector('[data-team-leader="1034201"]').click();assert(document.querySelector('[data-team-own-leader="1034201"]'));assert(document.querySelector('#autoTeam').hasAttribute('disabled'));
assert(!vm.runInContext('ownedTeamCards().some(c=>String(c.candidateId)==="1034201")',context));
document.querySelector('[data-team-own-leader="1034201"]').click();assert.equal(vm.runInContext('teamLeader',context),'MANUAL-1034201');assert(vm.runInContext('selectedTeam.includes(teamLeader)',context));
document.querySelector('[data-team-action="booPreset"]').click();assert.equal(vm.runInContext('teamSettings.event',context),'epic-battles-boo-4');assert(vm.runInContext('teamSettings.mission.length>0',context));
await vm.runInContext('autoBuildTeam()',context);assert.equal(document.querySelector('#teamCount').textContent,'6/6');assert(vm.runInContext('TE.constraints(teamCards(),teamMission(),teamFriend(resolveCard(teamLeader))).ok',context));
assert.equal(document.querySelectorAll('[data-team-pair]').length,30);document.querySelector('[data-team-pair]').click();assert(document.querySelector('#teamPairInfo').textContent.includes(' : '));
const original=vm.runInContext('JSON.stringify(selectedTeam)',context);document.querySelector('[data-team-replace]').click();const replacement=document.querySelector('[data-team-apply-replace]');assert(replacement);replacement.click();assert.notEqual(vm.runInContext('JSON.stringify(selectedTeam)',context),original);document.querySelector('[data-team-action="undo"]').click();assert.equal(vm.runInContext('JSON.stringify(selectedTeam)',context),original);
const excluded=document.querySelector('[data-team-exclude]');const excludedId=excluded.dataset.teamExclude;excluded.click();assert(vm.runInContext('teamSettings.excluded.includes('+JSON.stringify(excludedId)+')',context));document.querySelector('[data-team-action="restoreExcluded"]').click();assert.equal(vm.runInContext('teamSettings.excluded.length',context),0);
document.querySelector('[data-team-action="export"]').click();await new Promise(r=>setTimeout(r,0));assert(document.querySelector('#teamExport textarea').textContent.includes('Son Goku Super Saiyan 3'));
// An unsupported or blocked Worker still uses the same search without crashing.
context.Worker=function(){throw Error('Worker blocked')};context.smallRequest=vm.runInContext('buildTeamRequest(teamCards(),resolveCard(teamLeader))',context);const fallback=await vm.runInContext('executeTeamRequest(smallRequest)',context);assert.equal(fallback.team.length,6);
// A late worker message must not restore a cancelled composition.
let fakeWorker;context.Worker=function(){fakeWorker=this;this.postMessage=()=>{};this.terminate=()=>{this.terminated=true}};
const pending=vm.runInContext('autoBuildTeam()',context);document.querySelector('[data-team-action="cancel"]').click();assert(fakeWorker.terminated);fakeWorker.onmessage({data:{result:fallback}});await pending;assert.equal(vm.runInContext('teamBusy',context),false);assert.equal(vm.runInContext('JSON.stringify(selectedTeam)',context),original);assert(document.querySelector('#teamBuildStatus').textContent.includes('annulée'));
delete context.Worker;
console.log('New LR catalogue/search, explicit ownership, Boo preset, six covered cards, pair matrix, replacement/undo, exclusions, copy fallback, blocked worker and cancelled search: OK');
for(const [key,value] of [['dokkanos-edits','{}'],['dokkanos-inventory','null'],['dokkanos-team','{}'],['dokkanos-favorites','{}'],['dokkanos-rainbow100','{}'],['dokkanos-potential-manual','[]'],['dokkanos-saved-teams-v2','[null,{}, {"name":"Invalid","cards":[]}]']])saved.set(key,value);
vm.runInContext('restoreEdits();render();stats();renderInventory();renderMissing();renderManualOwned();renderDuplicates();renderAnalysis();renderTeam()',context);assert.equal(vm.runInContext('teamSaved().length',context),0);
context.localStorage.getItem=()=>{throw Error('Storage disabled')};context.localStorage.setItem=()=>{throw Error('Storage disabled')};await vm.runInContext('boot()',context);assert.equal(vm.runInContext('saveEdits()',context),false);vm.runInContext('renderTeam();toggleRainbow100("1000010")',context);console.log('Malformed saved values and blocked storage: OK');})();
