const assert=require('assert'),fs=require('fs'),M=require('../progress-model'),B=require('../companion-model');
assert.deepEqual(M.profile({sa:'20',potential:'79',awakening:'ztur',links:{A:'10',B:'',C:'11'}}),{sa:20,potential:79,awakening:'ztur',links:{A:10}});
assert.equal(M.profile({sa:0,potential:101}).sa,null);assert.equal(M.profile({sa:0,potential:101}).potential,null);
assert(M.preparation({_kitVersion:'ztur',maxSALevel:15,links:['A']},{sa:10,awakening:'base'}).some(x=>x.includes('éveil déclaré')));
assert.deepEqual(M.thresholds('Après avoir effectué 5 attaques\nAprès avoir subi 3 attaques\nAprès avoir esquivé 2 attaques\nÀ partir du 4e tour',{attacks:5,hits:2,dodges:2},4).map(x=>x.reached),[true,false,true,true]);
const a={cards:[{id:'1',name:'A',kit:'base'}],leader:'1',settings:{},missions:[],objective:'Libre'},b={...a,cards:[{id:'2',name:'B',kit:'base'}],leader:'2'};assert.equal(M.changes(a,b).added[0].id,'2');assert.notEqual(M.signature(a),M.signature(b));assert.equal(M.signature(a),M.signature({...a,settings:{search:'Autre recherche',locked:['x']}}));
const state={profiles:{'1':M.profile({})},combat:{},history:[],goals:[{id:'g',title:'Plan',steps:[{label:'Éveiller',done:false}]}],dataHistory:[]};assert.doesNotThrow(()=>M.validate(state));assert.throws(()=>M.validate({...state,profiles:{'bad':{}}}));assert.throws(()=>M.validate({...state,goals:[{id:'g',title:'x',steps:[{label:'x',done:'yes'}]}]}));
assert(B.allowed('dokkanos-progression-v1'));for(const key of ['dokkanos-sync-config','dokkanos-sync-session','dokkanos-sync-rescue'])assert(!B.allowed(key));
assert.doesNotThrow(()=>B.parseBackup(JSON.stringify({format:'DokkanOS',version:1,createdAt:new Date().toISOString(),entries:{'dokkanos-progression-v1':JSON.stringify(state)}})));
assert.throws(()=>B.parseBackup(JSON.stringify({format:'DokkanOS',version:1,createdAt:new Date().toISOString(),entries:{'dokkanos-progression-v1':'{"profiles":{"__proto__":{}},"history":[]}'}})));
const data=JSON.parse(fs.readFileSync('progress-data.json')),events=JSON.parse(fs.readFileSync('events.json'));assert(Object.keys(data.medals).length>400);for(const card of Object.values(data.medals))for(const variant of Object.values(card))for(const rows of Object.values(variant))for(const key of data.matches[rows]){const row=data.levels[key];const e=events.events.find(e=>e.id===row.event),s=e.stages.find(s=>s.id===row.stage);assert(s.rewards.some(r=>r.identified&&r.name===row.rewardName&&r.amount===row.amount));}
const sql=fs.readFileSync('backend/supabase.sql','utf8');assert(sql.includes('enable row level security'));assert(sql.includes('revision=expected_revision'));assert(sql.includes('security invoker'));assert(sql.includes('auth.uid()) = user_id'));
console.log('Progression: real preparation, unknown values, manual thresholds, history, strict backup, sourced medal links and sync isolation: OK');
