const assert=require('assert'),M=require('../companion-model.js'),T=require('../team-engine.js');
class Store{constructor(data={}){this.data={...data};this.fail=null;}get length(){return Object.keys(this.data).length}key(i){return Object.keys(this.data)[i]}getItem(k){return this.data[k]??null}setItem(k,v){if(k===this.fail)throw Error('quota');this.data[k]=String(v)}removeItem(k){delete this.data[k]}}
const old={'dokkanos-inventory':'{"1":"owned"}','dokkanos-team':'["MANUAL-1"]','foreign-key':'secret'},s=new Store(old),backup=M.backup(s,'2026-10-01T20:00:00Z');assert(!('foreign-key'in backup.entries));assert.equal(M.summary(backup).owned,1);assert.deepEqual(M.parseBackup(JSON.stringify(backup)),backup);
for(const entries of [{'foreign-key':'bad'},{'dokkanos-inventory':'{"1":"yes"}'},{'dokkanos-events-progress-v1':'{"m":{"done":false,"claimed":true}}'},{'dokkanos-journal-v1':'[{"id":"x","cards":[null]}]'}])assert.throws(()=>M.parseBackup(JSON.stringify({...backup,entries})));
const replacement={...backup,entries:{'dokkanos-inventory':'{"2":"owned"}'}};const undo=M.restore(s,replacement);assert.equal(s.getItem('dokkanos-team'),null);assert.equal(s.getItem('foreign-key'),'secret');M.restore(s,undo);assert.equal(s.getItem('dokkanos-team'),'["MANUAL-1"]');
const failure=new Store(old);failure.fail='dokkanos-favorites';assert.throws(()=>M.restore(failure,{...backup,entries:{'dokkanos-inventory':'{"3":"owned"}','dokkanos-favorites':'[]'}}));assert.equal(failure.getItem('dokkanos-inventory'),old['dokkanos-inventory']);
const card={id:'1',candidateId:'1',boxId:'MANUAL-1',name:'Test',rarity:'UR',type:'INT',categories:['Saga de Boo'],links:['Combat acharné'],leader:'Ki +3, PV, ATT et DÉF +170 % pour tous les types',passive:'*Effets de base* DÉF +150 %'},cards=Array.from({length:6},(_,i)=>({...card,id:String(i+1),candidateId:String(i+1),boxId:'MANUAL-'+(i+1),name:'Carte '+i}));
const d=M.diagnose(cards,cards[0],cards[0],{requirements:[{kind:'category',value:'Saga de Boo',count:6}]},['Saga de Boo'],{confirmedIds:cards.map(T.identity)},T);assert.equal(d.checks[0].ok,true);assert(!d.issues.length);assert(M.diagnose(cards,cards[0],cards[0],{},[],{confirmedIds:[]},T).issues.some(x=>x.includes('confirmée')));assert(M.diagnose([cards[0],cards[0]],cards[0],null,{},[],{},T).issues.some(x=>x.includes('plusieurs')));
const manual=M.diagnose(cards,cards[0],cards[0],{requirements:[{kind:'unknown',count:1}]},[],{},T);assert.equal(manual.verdict,'Composition à vérifier');
const base={...card,id:'10',candidateId:'10',name:'Avant',rarity:'SSR'},final={...card,id:'11',candidateId:'11',name:'Après',rarity:'LR'};const plan=M.improvementPlan([base],[[final,base]],{},new Set(['10']),()=>[]);assert(plan[0].tasks.some(x=>x.key==='awaken'));assert(plan[0].used);assert(!M.improvementPlan([final],[[final,base]],{'11':{sa:true}},new Set(),()=>[]).length);assert(!M.improvementPlan([base,final],[[final,base]],{},new Set(),()=>[])[0].tasks.some(x=>x.key==='awaken'));
const a=T.evaluate(cards,cards[0],cards[0],{},[],{quick:true}),b=T.evaluate(cards.map((c,i)=>i===5?{...c,links:[]}:c),cards[0],cards[0],{},[],{quick:true});assert(M.deltas(a,b).some(x=>x.key==='links'&&x.delta<0));
console.log('Companion: portable backup isolation, corruption rejection, restore replacement/rollback, ownership and manual diagnostics, family improvement plan, explicit comparison deltas: OK');
