const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),E=require('../team-engine');
const profile={source:'test',phases:[{name:'Phase 1',bosses:[{name:'Danger',stats:{ATK:'1,600,000','Max att / tour':'10'},effects:['Annule la capacité d’esquive en lançant des attaques infaillibles','Empêche l’étourdissement','Annule le blocage des attaques spéciales','Annule la réduction de l’ATT et de la DÉF','Verrouille le déplacement de personnage','Rend les sph. de ki aléatoires'],supers:[{damage:'Dégâts spé : 7,000,000',description:'Étourdit pendant 1 tour'}]},{name:'Autre route',stats:{},effects:[],supers:[]}]}]};
const b=E.bossAnalysis(profile);assert(b.disableDodge&&b.immuneStun&&b.immuneSeal&&b.immuneAtk&&b.immuneDef&&b.locks&&b.kiDisrupt&&b.stuns);assert.equal(b.maxSuper,7000000);assert.equal(b.maxHits,10);
const separate=E.bossAnalysis(profile,[],b.entries[1].key);assert(separate.selected);assert(!separate.disableDodge&&!separate.immuneStun);assert.equal(separate.bosses.length,1);assert(!E.bossAnalysis({ ...profile,source:'different'},[],b.entries[1].key).selected);
assert(!E.bossAnalysis(null).available);assert(E.bossAnalysis(null,['Annule la capacité d’esquive']).disableDodge);
const unit=(id,passive)=>({id,boxId:id,name:id,rarity:'UR',class:'Super',type:'INT',categories:['A'],links:['Lien'],passive:'*Effets de base*\n'+passive});
const tank=unit('tank','ATT et DÉF +150 %\nGarde activée contre toutes les attaques'),dodge=unit('dodge','ATT et DÉF +150 %\nEsquive les attaques ennemies'),control=unit('control','ATT et DÉF +150 %');control.superAttack={description:'Réduit l’ATT et la DÉF et étourdit l’ennemi'};
assert(!E.passive(unit('random','Grande chance de garde contre toutes les attaques')).guard);
const bossContext=E.battleContext({boss:b});assert(bossContext.disableDodge);assert(!E.passive(dodge,[],bossContext).roles.includes('Esquive'));
const fit=E.bossFit(control,E.passive(control),{boss:b});assert(fit.warnings.some(x=>x.includes('baisse d’ATT'))&&fit.warnings.some(x=>x.includes('étourdissement')));
const immunity=unit('immune','Annule la réduction de l’ATT');assert(!E.bossFit(immunity,E.passive(immunity),{boss:b}).warnings.some(x=>x.includes('baisse d’ATT')));
const leader={...tank,id:'leader',boxId:'leader',name:'leader',teamRules:{leader:[{kind:'base',known:true,categories:['A'],types:[],classes:[],hp:200,atk:200,def:200}]}},others=Array.from({length:4},(_,i)=>unit('strong'+i,'ATT et DÉF +200 %\nGarde activée contre toutes les attaques'));
const pool=[leader,...others,dodge,tank],original=JSON.stringify(pool),result=E.build(pool,leader,{context:{boss:b}});assert.equal(result.team.length,6);assert(result.team.some(c=>c.id==='tank'));assert(!result.team.some(c=>c.id==='dodge'));assert.equal(JSON.stringify(pool),original);
const forced=E.build(pool,leader,{mission:{requirements:[{kind:'card',value:'dodge',count:1}]},context:{boss:b}});assert(forced.check.ok&&forced.team.some(c=>c.id==='dodge'));
// Worker and direct generation must use exactly the same boss context and result.
let reply;const worker={importScripts(){worker.self.DokkanTeamEngine=E},self:{postMessage:r=>reply=r}};vm.runInNewContext(fs.readFileSync('team-worker.js','utf8'),worker);worker.self.onmessage({data:{pool,leader,options:{context:{boss:b}}}});assert.deepEqual(reply.result.team.map(c=>c.id),result.team.map(c=>c.id));
const hazard=E.bossAnalysis({source:'hazard',phases:[{bosses:[{name:'Boss',effects:[`S'il y a un perso de catégorie \"A\", ATT et DÉF +66 %`]}]}]});assert.equal(hazard.categoryHazards[0].category,'A');assert(E.bossFit(tank,E.passive(tank),{boss:hazard}).warnings.some(t=>t.includes('bonus ennemi')));
const live=JSON.parse(fs.readFileSync('boss-profiles.json')).profiles;for(const p of Object.values(live)){const a=E.bossAnalysis(p);assert(a.bosses.length);assert(Number.isFinite(a.pressure));}
console.log('Boss mechanics, source isolation, missing profiles, conditional guard, passive counters, mission priority, real dataset and worker parity: OK');
