const fs=require('fs'),vm=require('vm'),assert=require('assert');
const M=require('../event-model.js');
const event={id:'e',name:'Défi test',kind:'Défi',permanent:true,stages:[{id:'a',notes:['EFFET BOSS'],requirements:[]}],missions:[{id:'m',title:'Condition',description:'Deux cartes de la catégorie Rareté introuvable dans le titre',requirements:[],rewards:[]}]};
assert.equal(M.filter([event],{query:'rareté introuvable',status:'all',favorites:[]},{}).length,1);
assert.equal(M.combine(event,'a',['m']).notes,event.missions[0].description);
assert.deepEqual(M.combine(event,'a',['m']).stage.notes,['EFFET BOSS']);
const source=fs.readFileSync('app.js','utf8'),start=source.indexOf('async function boot(){'),end=source.indexOf('\nfunction mergeRecentCards',start);
const context={DB:null,META:null,CATALOG:null,OVERLAP:null,record:x=>x&&typeof x==='object'&&!Array.isArray(x),mergeRecentCards:()=>{},render:()=>{},stats:()=>{},renderDuplicates:()=>{},renderMissing:()=>{},renderInventory:()=>{},renderManualOwned:()=>{},renderTeam:()=>{},renderAnalysis:()=>{},applyMetadata:()=>{},restoreEdits:()=>{},initAdvancedFilters:()=>{}};
let inflight=0,max=0,calls=[];
context.fetch=async path=>{calls.push(path);inflight++;max=Math.max(max,inflight);await new Promise(r=>setTimeout(r,10));inflight--;return{ok:true,json:async()=>path==='collection.json'||path==='data.json'?{cards:[]}:null};};
vm.createContext(context);vm.runInContext(source.slice(start,end),context);
(async()=>{await vm.runInContext('boot()',context);assert(max>=5,'independent data must load concurrently');assert.deepEqual(JSON.parse(JSON.stringify(context.META)),{cards:{}});assert.deepEqual(JSON.parse(JSON.stringify(context.CATALOG)),{cards:[]});
context.fetch=async path=>{calls.push(path);if(path==='collection.json')throw Error('unavailable');return{ok:true,json:async()=>path==='data.json'?{cards:[{boxId:'fallback'}]}:null};};
await vm.runInContext('boot()',context);assert.equal(context.DB.cards[0].boxId,'fallback');assert(calls.includes('data.json'));console.log('Full audit regressions: description search, readable combat notes, concurrent boot, malformed optional data and collection fallback: OK');})().catch(e=>{console.error(e);process.exitCode=1});
