const assert=require('node:assert/strict'),E=require('../team-engine'),M=require('../team-planner-model'),C=require('../catalog-model'),B=require('../companion-model'),P=require('../progress-model');
const basic='*Effets de base*\n- ATT et DÉF +150 %',cards=Array.from({length:7},(_,i)=>({id:String(i+1),boxId:String(i+1),name:'Carte '+i,categories:['A'],links:['Lien'],type:'INT',class:'Super',maxSALevel:10,leader:'Ki +3, PV, ATT et DÉF +170 % pour tous les types',passive:basic}));
const plan=M.opening(E,cards,cards.map(c=>c.boxId),E.rotations(cards));assert.equal(plan.length,3);assert.equal(new Set(plan[0].cards.map(c=>c.boxId)).size,3);assert(!plan[1].cards.some(c=>plan[0].cards.some(x=>x.boxId===c.boxId)));assert.equal(plan[2].cards.filter(c=>plan[0].cards.slice(0,2).some(x=>x.boxId===c.boxId)).length,2);assert(!plan[2].cards.some(c=>c.boxId===plan[0].cards[2].boxId));assert.throws(()=>M.opening(E,cards,['1','1','2','3','4','5','6']));assert.throws(()=>M.opening(E,cards.slice(0,6),cards.slice(0,6).map(c=>c.boxId)));
const friend={...cards[0],boxId:'FRIEND-1',_friend:true},seven=[...cards.slice(0,6),friend];assert.equal(M.opening(E,seven,seven.map(c=>c.boxId)).length,3);
const a=E.evaluate(cards.slice(0,6),cards[0],friend,{},['A'],{quick:true}),b={...a,check:{deficit:1,rows:[]},score:a.score+10000};assert.equal(M.compare(a,b).preferred,'A');assert(M.replacement(E,a,a,cards[1],cards[2]).length);
const variant={kind:'ztur',verified:true,available:true,kit:{passive:basic+'\n- Garde activée contre toutes les attaques',leader:cards[0].leader,maxSALevel:15}},raw={...cards[0],zAwakenings:[variant]},projected=C.selectKit(raw,'ztur'),ctx={useZA:true,realProfiles:{'1':P.profile({awakening:'base',potential:79,sa:10,links:{Lien:10}})}};assert.equal(E.combatCard(projected,ctx).passive,basic);assert.equal(E.combatCard(raw,ctx)._kitProjected,undefined);assert(E.preparationScore(raw,ctx)>0);assert.equal(E.preparationScore(raw,{realProfiles:{}}),0);assert(E.preparationScore(raw,ctx)<=12);ctx.realProfiles['1'].awakening='ztur';assert.equal(E.combatCard(raw,ctx)._kitVersion,'ztur');assert.equal(E.combatCard(raw,ctx)._kitProjected,false);
ctx.realProfiles['1'].survivalPassive='*Effets de base*\n- Taux de réduction des dégâts +70 %';ctx.realProfiles['1'].survivalVerified=false;assert.notEqual(E.combatCard(raw,{...ctx,survival:true}).passive,ctx.realProfiles['1'].survivalPassive);ctx.realProfiles['1'].survivalVerified=true;assert.equal(E.combatCard(raw,{...ctx,survival:true}).passive,ctx.realProfiles['1'].survivalPassive);assert.notEqual(E.combatCard(raw,ctx).passive,ctx.realProfiles['1'].survivalPassive);assert.equal(raw.passive,basic);
assert(B.allowed('dokkanos-team-planner-v1'));const saved={version:1,signature:'team',order:seven.map(c=>c.boxId)};assert.doesNotThrow(()=>M.validate(saved));assert.throws(()=>M.validate({...saved,order:['1','1']}));assert.doesNotThrow(()=>B.parseBackup(JSON.stringify({format:'DokkanOS',version:1,createdAt:new Date().toISOString(),entries:{'dokkanos-team-planner-v1':JSON.stringify(saved)}})));
console.log('Planner: quota-first comparison, replacement tradeoffs, legal turns and returns, friend instances, declared kits, bounded readiness, verified-only survival passives, immutable source and portable backup: OK');
