const fs=require('fs'),vm=require('vm'),assert=require('assert'),{parseHTML}=require('linkedom');
const {document,window}=parseHTML(fs.readFileSync('index.html','utf8'));const saved=new Map();window.HTMLElement.prototype.scrollIntoView=function(){};const context={console,window,document,navigator:{onLine:true},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,String(v)),removeItem:k=>saved.delete(k)},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path,'utf8'))}),alert:m=>{console.log('ALERT',m)},setTimeout,clearTimeout,Date,location:{reload(){}}};vm.createContext(context);
vm.runInContext(fs.readFileSync('team-engine.js','utf8'),context);vm.runInContext(fs.readFileSync('app.js','utf8').split('boot().catch(')[0],context);vm.runInContext(fs.readFileSync('event-model.js','utf8'),context);vm.runInContext(fs.readFileSync('team-search.js','teams.js','utf8'),context);vm.runInContext(fs.readFileSync('events.js','utf8'),context);vm.runInContext(fs.readFileSync('catalog-model.js','utf8'),context);vm.runInContext(fs.readFileSync('catalogue.js','utf8'),context);
context.requestAnimationFrame=fn=>setTimeout(fn,0);context.queueMicrotask=queueMicrotask;context.Event=window.Event;context.MutationObserver=class{observe(){}};window.scrollTo=()=>{};window.scrollY=0;vm.runInContext(fs.readFileSync('team-battle-model.js','utf8'),context);vm.runInContext(fs.readFileSync('team-battles.js','utf8'),context);



(async()=>{
 await vm.runInContext('boot()',context);vm.runInContext(fs.readFileSync('verify-search.js','utf8'),context);vm.runInContext(fs.readFileSync('verify-batch.js','utf8'),context);window.DokkanVerifySearch.prepare();vm.runInContext('switchView("verify");verifySelectPosition(verifyPending()[0].boxId)',context);
 const apply=(key,value)=>{const el=document.querySelector('[data-verify-search-filter="'+key+'"]');const option=[...el.options].find(o=>o.value===value);for(const o of el.options)o.removeAttribute('selected');option.setAttribute('selected','');el.dispatchEvent(new window.Event('change',{bubbles:true}));};
 apply('rarity','UR');assert.equal(vm.runInContext('verifyDraft.query',context),'');let rows=vm.runInContext('verifyResults()',context);assert(rows.length>80);assert(rows.every(c=>c.rarity==='UR'));assert.equal(document.querySelectorAll('#verifyResults input').length,12);
 for(let i=0;i<7;i++)document.querySelector('#verifySearchMore').click();assert(document.querySelectorAll('#verifyResults input').length>80);
 apply('type','AGI');apply('class','Super');rows=vm.runInContext('verifyResults()',context);assert(rows.length);assert(rows.every(c=>c.rarity==='UR'&&c.type==='AGI'&&c.class==='Super'));assert.equal(document.querySelectorAll('#verifyResults input').length,Math.min(12,rows.length));
 const selected=document.querySelector('#verifyResults input');selected.dispatchEvent(new window.Event('change',{bubbles:true}));assert(!document.querySelector('#verifyConfirm').disabled);
 apply('type','INT');assert.equal(vm.runInContext('verifyDraft.cardId',context),'');assert(document.querySelector('#verifyConfirm').disabled);rows=vm.runInContext('verifyResults()',context);assert(rows.every(c=>c.rarity==='UR'&&c.type==='INT'&&c.class==='Super'));
 vm.runInContext("verifySetQuery('goku')",context);await new Promise(r=>setTimeout(r,180));rows=vm.runInContext('verifyResults()',context);assert(rows.every(c=>c.rarity==='UR'&&c.type==='INT'&&c.class==='Super'));assert.equal(JSON.parse(saved.get('dokkanos-verify-filters-v1')).type,'INT');
 vm.runInContext('verifySelectPosition(verifyPending()[1].boxId)',context);assert.equal(document.querySelector('#verifyTypeFilter').value,'INT');assert.equal(vm.runInContext('verifyDraft.query',context),'');assert(document.querySelectorAll('#verifyResults input').length);
 document.querySelector('#verifyResetFilters').click();assert.equal(document.querySelectorAll('#verifyResults input').length,0);assert(Object.values(window.DokkanVerifySearch.filters).every(v=>v===''));
 console.log('Verification filters: no-keyword browsing, combined type/class/rarity, beyond 80 results, pagination reset, stale-selection clearing, keyword intersection, saved settings, next-card retention and reset: OK');
})().catch(e=>{console.error(e);process.exitCode=1});
