const assert=require('node:assert/strict'),E=require('../team-engine'),meta=require('../card-meta.json').cards;
const unit=(id,passive='ATT et DÉF +180 %',extra={})=>({id,boxId:id,name:id,type:'INT',class:'Super',categories:['A'],links:['Lien'],rarity:'UR',passive:'*Effets de base*\n- '+passive,...extra});
const a=unit('a'),b=unit('b'),wrong=unit('wrong','ATT et DÉF +180 %',{type:'PUI',class:'Extrême',categories:['B']});
const typed=unit('typed','Ki +3 et ATT et DÉF +40 % pour tous les alliés de type INT');assert.deepEqual(E.supports(typed,[typed,a,b,wrong]).map(x=>x.target.id),['a','b']);
const category=unit('category','ATT et DÉF +50 % pour tous les alliés de catégorie "A"');assert(E.supports(category,[category,a,wrong]).every(x=>x.target.id==='a'));
const named=unit('named','ATT et DÉF +40 % pour soi et tous les persos dont le nom comprend "a"');assert.equal(E.supports(named,[named,a,b]).length,1);
const unreadable=unit('unreadable','ATT et DÉF +40 % pour tous les alliés de catégorie Catégorie non identifiée');assert.equal(E.supports(unreadable,[unreadable,a,b]).length,0);
const slot3=unit('slot3');slot3.passive+='\n*En 3e position*\n- Ki +3 et ATT et DÉF +60 % pour tous les alliés';const rot=[a,b,slot3];assert.equal(E.supports(slot3,rot,{rotation:rot,position:2}).length,0);assert(E.supports(slot3,rot,{rotation:rot,position:3}).every(x=>!x.conditional));assert(E.supports(slot3,rot).every(x=>x.conditional));
const hp=unit('hp');hp.passive+='\n*Si PV à 50 % ou plus*\n- ATT et DÉF +100 % pour tous les alliés';assert(E.supports(hp,[hp,a,b]).every(x=>x.conditional&&x.rule.weight<1));
const future=unit('future');future.passive+='\n*À partir du 5e tour*\n- ATT +100 % pour tous les alliés';assert(E.supportScore(E.supports(future,[future,a,b],{context:{encounter:{duration:'short'}}}))<E.supportScore(E.supports(future,[future,a,b],{context:{encounter:{duration:'long'}}})));
const conditional=unit('conditional');conditional.passive+='\n*S’il y a parmi les alliés attaquants du tour un autre perso de catégorie "B"*\n- Ki +3 pour tous les alliés';assert.equal(E.supports(conditional,[conditional,a,wrong],{rotation:[conditional,a,b]}).length,0);assert.equal(E.supports(conditional,[conditional,a,wrong],{rotation:[conditional,a,wrong]}).length,2);
const special=unit('special');special.superAttack={description:'Inflige des dégâts colossaux ; ATT +30 % pour les alliés pendant 2 tours'};special.ultraSuperAttack={description:'Inflige des dégâts colossaux ; ATT +60 % pour les alliés pendant 2 tours'};const sp=E.supports(special,[special,a,b]);assert(sp.every(x=>x.rule.timing==='special'&&x.conditional));assert.equal(E.supportScore(sp),E.supportScore(sp.filter(x=>x.rule.special==='Ultra-SP')));
const dodge=unit('dodge','Chances d’esquive +20 % pour tous les alliés');assert(E.supports(dodge,[dodge,a]).length);assert.equal(E.supports(dodge,[dodge,a],{context:{disableDodge:true}}).length,0);
const support=unit('support','ATT et DÉF +180 %\n- Ki +3 et ATT et DÉF +60 % pour tous les alliés'),full=[support,a,b,wrong,...Array.from({length:3},(_,i)=>unit('extra'+i))];assert.equal(E.supportScore(E.supports(support,full)),E.supportScore(E.supports(support,[support,a,b])));
// Ranking really changes the team, while all-six category requirements still win.
const leader=unit('leader','ATT et DÉF +200 %\n- Garde activée contre toutes les attaques',{teamRules:{leader:[{kind:'base',known:true,categories:['A'],types:[],classes:[],hp:200,atk:200,def:200}]}}),fixed=Array.from({length:4},(_,i)=>unit('fixed'+i,'ATT et DÉF +200 %\n- Garde activée contre toutes les attaques')),plain=unit('plain'),result=E.build([leader,...fixed,plain,support],leader,{locked:fixed,context:{combat:'synergy'}});assert(result.team.some(x=>x.id==='support'));assert(!result.team.some(x=>x.id==='plain'));
const card=id=>({...meta[id],...meta[id].fr,id,boxId:id}),jeese=card('1034661'),arinsu=card('1034431');assert(E.supports(jeese,[jeese,a]).some(x=>x.rule.special==='SP'&&x.rule.atk===20));const kuu=unit('kuu','ATT et DÉF +180 %',{name:'Majin Kuu'});assert(E.supports(arinsu,[arinsu,kuu,a]).some(x=>x.target.id==='kuu'&&x.rule.reduction===10));assert(!E.supports(arinsu,[arinsu,kuu,a]).some(x=>x.target.id==='a'&&x.rule.reduction===10));
console.log('Support targets by type/category/name, slot 3, HP/turn/rotation conditions, SP alternatives, dodge cancellation, simultaneous-recipient cap, real team selection and sourced kits: OK');
