const assert=require('assert'),M=require('../team-battle-model'),B=require('../companion-model');
const o={event:'event',eventName:'Combat',stage:'stage1',stageName:'Niveau 1',missions:[{id:'m1',title:'Mission A'},{id:'m2',title:'Mission B'}]},team={id:'v1',battleId:'root',name:'Équipe 1',cards:['card1'],leader:'card1',settings:{event:'event'},objective:o};
let rows=M.add([],team,{result:'defeat',count:3,note:'Ki insuffisant'});assert.equal(M.summary(rows,team).status,'review');
const v2={...team,id:'v2',cards:['card2'],name:'Équipe 2'};rows=M.add(rows,v2,{result:'victory',count:2,validated:['m1']});let s=M.summary(rows,v2);assert.equal(s.total,5);assert.equal(s.level,5);assert.equal(s.missions.m1,5);assert.equal(s.missions.m2,undefined);assert.equal(s.status,'review');assert.equal(s.own,2);assert.deepEqual(rows[0].snapshot.cards,['card1']);
rows=M.add(rows,v2,{result:'victory',count:1,validated:['m1','m2']});s=M.summary(rows,v2);assert.equal(s.status,'works');assert.equal(s.missions.m1,5);assert.equal(s.missions.m2,6);assert.equal(s.level,5);
const other={...team,id:'v3',battleId:'other',objective:{...o,stage:'stage2'}};assert.equal(M.summary(rows,other).total,0);assert.notEqual(M.objectiveKey(o),M.objectiveKey(other.objective));assert.equal(M.objectiveKey(o),M.objectiveKey({...o,missions:[...o.missions].reverse()}));
for(const count of [0,-1,1.5,1000,NaN])assert.throws(()=>M.add(rows,team,{count,result:'defeat'}));assert.throws(()=>M.validate([{...rows[0],validated:['m1']}]));assert.throws(()=>M.validate([{...rows[0],snapshot:{cards:null}}]));
const backup={format:'DokkanOS',version:1,createdAt:new Date().toISOString(),entries:{[M.key]:JSON.stringify(rows)}};const valid=B.parseBackup(JSON.stringify(backup));assert.equal(JSON.parse(valid.entries[M.key]).length,3);assert.throws(()=>B.parseBackup(JSON.stringify({...backup,entries:{[M.key]:'[{}]'}})));
console.log('Battle attempts: per version and shared objective, batched first success, independent missions, immutable compositions, stage isolation, invalid entries and backup validation: OK');
